function bt_eval(l,n){try{return window.eval.apply(window,[l])}catch(u){n&&n(u)}}var bt_parameter=function(){var l;return function(n,u){var C=u||document;"undefined"===typeof l&&(l=new BrightTag.HTTP.URL(C.location.href));return l.param(n)}}();function bt_meta(l,n){for(var u,C=(n||document).getElementsByTagName("meta"),H=0,J=C.length;H<J;H++)if(u=C[H],u.getAttribute("name")===l)return u.getAttribute("content");return""}
function bt_cookie(l,n){return(new BrightTag.HTTP.Cookie(n||document)).get(l)||""}function bt_data(l,n){var u=BrightTag.V2_RESPONSE?BrightTag.configuredSites()[0]:BrightTag.instance;return u?u.data(l,n):""}window.bt_data_escaped=bt_data;function bt_log(l){window.console&&console.log&&console.log("BrightTag: "+l)}var bt_handle_exception=bt_log;
window.BrightTag=function(l){function n(a,d){return Object.prototype.toString.call(a)==="[object "+d+"]"}function u(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")}function C(a){return"\n//at-sourceURL=/BrightTag/"+a.replace(/\s+/g,"_")+".js"}function H(a,d){for(var c=0,b=this.length;c<b;c++)a.call(d,this[c],c,this)}function J(a,d,c){for(var b in a)a.hasOwnProperty(b)&&d.call(c,b,a[b],a)}function r(a,d,c){a&&(O(a)?P.call(a,d,c):q.isObject(a)&&J(a,d,c))}function s(a,d){J(d,function(c,b){a[c]=
b});return a}function O(a){return q.isArray(a)||!q.isString(a)&&a.length}function oa(a){return!!a}function pa(a,d){var c=this.slice(),b=[];P.call(c,function(c,e){a.call(d,c,e,this)&&b.push(c)});return b}function T(a,d,c){if(a)return qa.call(O(a)?a:[a],d||oa,c)}function ra(a,d){var c=this.slice(),b=Array(c.length);P.call(c,function(c,e){b[e]=a.call(d,c,e,this)});return b}function A(a,d){var c,b,g=q.isArray(a)?a:[a];c=0;for(b=g.length;c<b;c++)if(g[c]===d)return!0;return!1}function U(a){return!q.isString(a)?
a:a.replace(/%/g,"%25").replace(/#/g,"%23").replace(/&/g,"%26").replace(/'/g,"%27").replace(/;/g,"%3B").replace(/</g,"%3C").replace(/>/g,"%3E")}function V(a){for(var d=5381,c=0,b=a.length;c<b;)d=(d<<5)+d+a.charCodeAt(c++);return d.toString(36)}function W(a){function d(){}function c(a){var b=Array.prototype.slice.call(arguments,1);x.each(r,function(h){var c=[t].concat(b);(h[a]||d).apply(null,c)})}function b(){D=!0;Q=y.length;c("engine:off")}function g(){D&&c("engine:on");D=!1;X=0;(y[Q++]||b)()}function e(a,
b){return{type:a,exception:b}}function f(){c("block:finish");g()}function h(b,h){var c=a.createElement(b.tagName),f=x.extend(x.extend({},b.defaults),h||{});x.each(b.supported,function(a){q.isString(a)&&null!=f[a]?c[a]=f[a]:q.isObject(a)&&null!=f[a.option]&&a.setter(c,f[a.option])});return c}function m(b,d){var m=h(s.iframe,d);m.onerror=function(){c("block:error",e("iframe","Problem loading "+b))};c("block:start",b);m.src=b.toString();a.body.appendChild(m);f()}function k(a,b){var m=h(s.image,b);m.onerror=
function(){c("block:error",e("image","Problem loading "+a))};c("block:start",a);m.src=a.toString();f()}function v(b,m,d){var k=!1,v=h(s.script,d);v.onerror=function(){c("block:error",e("script","Problem loading "+b));k||f()};v.onload=v.onreadystatechange=function(){var a;if(!(a=k)){a:{switch(v.readyState){case void 0:case "loaded":case "complete":a=!0;break a}a=!1}a=!a}a||(k=!0,f())};c("block:start",b);b&&(v.src=b.toString());m&&(v.text=m);m=a.getElementsByTagName("script")[0];m.parentNode.insertBefore(v,
m)}function p(a){var b=Array.prototype.slice.call(arguments,1);return function(){a.apply(null,b)}}function K(b){return function(){try{if(c("block:start",b),q.isString(b)){var h=x.trim(b).replace(/^\x3c!--/,"").replace(/--\x3e$/,"");a.defaultView?a.defaultView.eval.call(window,h):a.parentWindow?a.parentWindow.execScript(h):c("block:error",e("wait","Could not evaluate wait block ["+h+"]"))}else b()}catch(m){c("block:error",e("wait",m))}finally{f()}}}function w(a){y.push(a);D&&g();return t}function l(a){y.splice(Q+
X++,0,a);return t}var t=this,r=[],B={},D=!1,y=[],Q=0,X=0,s={iframe:{tagName:"iframe",defaults:{frameborder:"0",height:"1px",scrolling:"no",width:"1px"},supported:[{option:"display",setter:function(a,b){a.style.display=b}},"frameborder","id","height","scrolling","width"]},image:{tagName:"img",defaults:{},supported:[{option:"display",setter:function(a,b){a.style.display=b}},"id",{option:"height",setter:function(a,b){a.setAttribute("height",b)}},{option:"width",setter:function(a,b){a.setAttribute("width",
b)}}]},script:{tagName:"script",defaults:{type:"text/javascript"},supported:["async","id","type","charset"]}};t.run=function(){c("engine:on");g()};t.options=function(a){x.extend(B,a);return t};t.option=function(a){return B[a]};t.iframe=function(a,b){return w(p(m,a,b))};t.image=function(a,b){return w(p(k,a,b))};t.script=function(a,b,h){return w(p(v,a,b,h))};t.wait=function(a){return w(K(a))};t.preemptCss=function(a,b){return l(p(v,a,b))};t.preemptIframe=function(a,b){return l(p(v,a,b))};t.preemptImage=
function(a,b){return l(p(v,a,b))};t.preemptScript=function(a,b,h){return l(p(v,a,b,h))};t.preemptWait=function(a){return l(K(a))};t.listen=function(a){r.push(a);(a["engine:listen"]||d).apply(null,[t]);return t}}function Y(a){function d(a){e.push(a);h&&!m&&b()}function c(a){a.run()}function b(){var a=e[f];a&&(f++,a.listen(k).run())}var g,e=[],f=0,h=!1,m=!1,k={"engine:on":function(){m=!0},"engine:off":function(){m=!1;b()}};g=d;this.alwaysQueue=function(){g=d};this.neverQueue=function(){g=c};this.push=
function(a){g(a);return a};this.run=function(){h=!0;b()};this.applyListener=function(a){var b,h;b=f;for(h=e.length;b<h;b++)e[b].listen(a)};this.toString=function(){return"Group[name="+a+"; working="+m+"; running="+h+"]"}}function Z(a,d){return{"engine:listen":function(c){c.listen(new sa(a,d))}}}function $(a){function d(a){return g[a]||(g[a]=new Y(a))}function c(a){return b.addToGroup(a,b.newEngine())}var b=this,g={undefined:new Y(void 0)},e=[];g.undefined.neverQueue();b.addGlobalListener=function(a){e.push(a);
r(g,function(b,c){c.applyListener(a)})};b.addToGroup=function(a,b){r(e,function(a){b.listen(a)});return d(a).push(b)};b.newEngine=function(){return new W(a)};b.group=function(a){return c(a)};b.listen=function(){return c().listen.apply(null,arguments)};b.iframe=function(){return c().iframe.apply(null,arguments)};b.image=function(){return c().image.apply(null,arguments)};b.script=function(){return c().script.apply(null,arguments)};b.wait=function(){return c().wait.apply(null,arguments)};b.run=function(a){d(a).run()};
b.alwaysQueue=function(a){d(a).alwaysQueue()};b.neverQueue=function(a){d(a).neverQueue()};b.setOptions=function(){return c()}}function R(a){function d(a){var b,c;a=a.split(/; ?/);g={};for(var d=0,e=a.length;d<e;d++){c=a[d];b=c.indexOf("=");var p=g,l=c.slice(0,b);b=c.slice(b+1);b=unescape(b);p[l]=b}}function c(b,c,m){if(b){m=m||{};b=[b+"="+U(c||"")];if((c=m.expires)||0===c)q.isNumber(c)&&(c=(new Date(c)).toGMTString()),b.push("expires="+c);(c=m.path)&&b.push("path="+c);(c=m.domain)&&b.push("domain="+
c);!0===m.secure&&b.push("Secure");!0===m.httponly&&b.push("HttpOnly");m=b.join(";");if(m.length<e)a.cookie=m;else throw{name:"CookieTooLongError",message:"Cookie reached 4096 byte limit"};d(a.cookie)}}function b(a,b){c(a,"",s(b||{},{expires:1}))}var g={},e=4096;d(a.cookie||"");return{get:function(a){return g[a]},set:c,remove:b,findEach:function(a,b){for(var c in g)g.hasOwnProperty(c)&&c.match(a)&&b(c,g[c])},clear:function(a){var c=s({},g),d;for(d in c)b(d,a)}}}function aa(a){a=R(a);var d=a.set,c=
a.remove;a.set=function(a,c,e){e=s(e||{},{path:"/"});0===e.expires&&(e.expires=+new Date("1/1/2038"));d(a,c,e)};a.remove=function(a,d){c(a,s(d||{},{path:"/"}))};a.purge=function(){};return a}function ba(a,d){function c(a){a=a.expires;return 0!==a&&a<=+new Date}function b(b,c){a.setItem(b,c)}function g(a,b,h){b={value:b,expires:h};c(b)||d.setItem(a,JSON.stringify(b))}function e(a){a=d.getItem(a);try{return a?JSON.parse(a):void 0}catch(b){}}function f(a){a=e(a);var b;return a&&(a.hasOwnProperty("value")&&
a.hasOwnProperty("expires"))&&!c(a)?(b=a.value,delete a.value,[b,a]):[]}function h(a,b,c,d){for(var h,e=0,f=a.length;e<f;e++)h=a.key(e),!c[h]&&(c[h]=h.match(b))&&d(h)}return{set:function(a,c,d){a&&null!=c&&(d=d||{},(null!=d.expires?g:b)(a,c,d.expires))},get:function(b){return a.getItem(b)||f(b)[0]},findEach:function(b,c){var e={};h(a,b,e,function(b){var d=a.getItem(b);null!=d&&c(b,d)});h(d,b,e,function(a){var b=f(a),d=b[0],b=b[1];null!=d&&c(a,d,b)})},remove:function(b){a.removeItem(b);d.removeItem(b)},
purge:function(){for(var a,b,h=d.length;h--;)a=d.key(h),(b=e(a))&&(b.hasOwnProperty("value")&&b.hasOwnProperty("expires"))&&c(b)&&d.removeItem(a)}}}function L(a,d){var c={};c.set=a.set;c.findEach=function(b,c){var e={};a.findEach(b,function(a,b,d){e[a]=!0;c(a,b,d)});d.findEach(b,function(b,d,m){e[b]||(a.set(b,d,m),c(b,d,m))})};c.get=function(b){var c=a.get(b);void 0===c&&(c=d.get(b),void 0!==c&&a.set(b,c));return c};c.remove=function(b){a.remove(b);d.remove(b)};c.purge=function(){a.purge();d.purge()};
return c}function M(a){function d(a){var b={};if(!q.isString(a))return a;r(a.split("&"),function(a){if(""!==a){var c=a.split("=");a=decodeURIComponent(c[0]);c=c[1]&&decodeURIComponent(c[1].replace(/\+/g," "));(null==b[a]?b[a]=[]:b[a]).push(c)}});return b}function c(a,b){var c=[];r(a,function(a){if(q.isObject(a))return!1;a=null==a||""===a?b:a;(q.isString(a)||q.isNumber(a)||q.isBoolean(a))&&c.push(a)});return c}function b(a){return!q.isArray(a)?[a]:a}function g(a,b){var c=encodeURIComponent(a),d=encodeURIComponent(b);
return c+"="+d}var e=this,f={};s(f,d(a));e.param=function(a){a=f[a]||[""];return 1<a.length?a:a[0]};e.params=function(){return f};e.appendParam=function(a,d){if(a){var e=c(b(d));0<e.length&&(f[a]=(null==f[a]?f[a]=[]:f[a]).concat(e))}return this};e.replaceParam=function(a,d){if(a){var e=c(b(d));0<e.length&&(f[a]=(f[a]=[]).concat(e))}return this};e.appendParams=function(a){r(a,e.appendParam);return this};e.alwaysAppendParam=function(a,d){if(a){var e=c(b(d),"");0<e.length&&(f[a]=(null==f[a]?f[a]=[]:
f[a]).concat(e))}return this};e.alwaysReplaceParam=function(a,d){if(a){var e=c(b(d),"");0<e.length&&(f[a]=(f[a]=[]).concat(e))}return this};e.alwaysAppendParams=function(a){r(a,e.alwaysAppendParam);return this};e.appendPartialQueryString=function(a){a&&e.alwaysAppendParams(d(a));return this};e.deleteParam=function(a){delete f[a]};e.toString=function(){var a=[];r(f,function(b,c){r(c,function(c){a.push(g(b,c))})});return a.join("&")}}function E(a){function d(){var a=l.toString();return f+h+(0<a.length?
"?"+a:"")}var c={},b,g,e,f,h,m,k,v,p,l,w=a.match(ta);a=w[1]||"";g=w[2]||"";e=(w[3]||"").substring(1);b=g+(e?":"+e:"");f=a+(b?"//"+b:"");h=w[4]||"";m=(k=h.match(/^(.+?)?\/([^\/]+)?$/))&&k[1]||"";k=k&&k[2]||"";v=(w[5]||"").substring(1);p=(w[6]||"").substring(1);l=new M(v);s(c,l);s(c,{origin:f,scheme:a,host:b,hostname:g,port:e,path:h,pathname:m,scriptname:k,queryString:l.toString,fragment:function(){return p},tooLong:function(){return 2082<d().length},asString:d});c.toString=d;return c}function ca(a,
d,c){function b(){var b=c.createEvent("Event");b.initEvent(d,!0,!1);try{b.currentTarget=b.target=a}catch(e){bt_log("warning: can not set target for ["+d+"] event: "+e)}return b}function g(){var a=c.createEventObject("Event");a.type=d;a.cancelable=!0;a.bubbleable=!1;return a}function e(c){setTimeout(function(){try{(c.handleEvent||c).call(a,f?b():g())}catch(e){bt_log("error: overriding ["+d+"] event: "+e)}},0)}var f=!!a.addEventListener,h=f?"addEventListener":"attachEvent",m=a[h];a[h]=function(b,c,
h){if(c&&("function"==typeof c||"function"==typeof c.handleEvent))if(b==d||b=="on"+d)e(c);else try{f?m.call(a,b,c,h):m(b,c)}catch(g){bt_log("error: proxying ["+b+"] event: "+g)}}}function da(a,d,c){function b(a){a.hasOwnProperty("enabled")&&(v=a.enabled);a.hasOwnProperty("timestamp")&&(l=a.timestamp,v=!0);a.hasOwnProperty("site")&&(m=a.site);a.hasOwnProperty("referrer")&&(k=a.referrer)}function g(c){c&&b(c);p=[];a.remove(d)}function e(){try{return JSON.stringify({site:m,referrer:k,errors:p})}catch(a){bt_log("problem serializing errors: "+
a.message)}return null}function f(a){var b=q.isObject(a)?s({},a):{};b.type=b.type||"unknown";b.message=b.message||a.toString();b.timestamp=l;return b}function h(){g();p.push(f({type:"runtime",message:"Too many errors"}));a.set(d,e())}if(!a)throw Error("ErrorManager requires a store");var m,k,v=!0,p=[],l=+new Date;c&&b(c);return{configure:b,reset:g,hasErrors:function(){return 0<p.length},tooManyErrors:h,processStoredErrors:function(){var b=a.get(d);if(b)try{var c=JSON.parse(b)||{};m=c.site;k=c.referrer;
q.isArray(c.errors)&&(p=p.concat(c.errors))}catch(e){bt_log("problem reading stored errors: "+e.message)}},push:function(b){bt_log("error: "+JSON.stringify(b));if(v&&b&&!(-1>b.tagId||-1>b.pageId))try{p.push(f(b)),a.set(d,e())}catch(c){if("CookieTooLongError"!=c.name)throw c;h()}},toJSON:e,toArray:function(){return p}}}function ea(a,d){return new function(a,b){function d(a){k.wait(a)}function e(a){function b(){m=l.jQuery;d(a)}h="var $ = BrightTag.$; ";l.jQuery?b():k.script(l.instance.baseUri()+"BrightTag.jquery-1.5.1.js").wait(b)}
var f={},h="",m,k=l.Blab.group(b);f.getJQuery=function(){return m};f.ensureJQuery=function(h){f.ensureJQuery=d;m=a.jQuery;(m?d:e)(h);l.Blab.run(b)};f.functionWithAccess=function(a,b){return new Function(a,h+b)};return f}(a,d)}function fa(a){function d(a,c){c&&c.findEach(a,function(a,c){b.appendParam(a,c)})}function c(a,b){return function(c){bt_log("invalid "+a+" expression: "+b+", exception = "+c)}}var b=this,g=a.window,e=a.parentReferrer,f=a.referrer,h=E(0===a.host.length?"":(/^[a-z0-9+.-]+:\/\/.+/.test(a.host)?
"":"//")+a.host+"/tag"),m=a.store?a.store.get("X-BT-InspectSession"):null;s(b,h);b.toString=h.toString;b.appendParams({site:a.site,referrer:f,docReferrer:a.docReferrer,mode:a.mode,H:V(f||a.document.location.href)});m&&b.appendParam("inspect-session",m);f!==e&&b.appendParam("parentReferrer",e);d(/^btps\..+/,new R(a.document));d(/^btpdb\..+/,a.store);b.appendData=function(a){var c=bt_data(a),c=q.isArray(c)||q.isObject(c)?g.JSON.stringify(c):c;return b.alwaysReplaceParam("_cb_"+("bt_data('"+a+"')"),
c)};b.appendJs=function(a){var d=c("client binding expression",a);return b.alwaysReplaceParam("_cb_"+a,z(a,d))};b.cf=function(a){q.isArray(a)||(a=[a]);var c=b.param("cf");c&&(a=Array(c).concat(a));b.replaceParam("cf",a.join());return b};b.addCf=function(a,d){if(!z(d,c("conditional fire",d,"tags/"+a+"-cf.js")))return!1;var e=b.param("cf");b.replaceParam("cf",e?e+","+a:a);return!0};b.length=function(){return b.toString().length};b.isTooLarge=function(){return 2028<b.length()};var k=b.toString();b.hasConditions=
function(){return k!=b.toString()}}function ga(a,d){function c(a,b){r(b,function(b,c){a[a.type+"."+b]=c});d.push(a)}function b(a,b,c){var d=l.instance.serverURL();r(a,function(a){a.trigger(b,c,d)});d.hasConditions()&&(d.appendParam("mode","v1"),l.Blab.script(d.asString()))}function g(a,d,e){function f(b,d){r(k,function(f){var h,g=f.name;try{h=l[f.dbe];if(!h){var k=l,p=f.dbe,w,q=f.dbe,t=C("event-dbes/"+g+"-page-"+(B||"adhoc")+"-event-"+a);w=m.functionWithAccess(["eventObject","eventData"],"return "+
q+";"+t);h=k[p]=w}e.data(g,h.call(b.target,b,d))}catch(r){c({type:"evdbe",message:r.toString(),pageId:B||-1},{name:g,eventName:a})}})}var g={},k=[],l={},B=(d||{}).pageId;g.data=function(a,b){k.push({name:a,dbe:b});return g};g.applyDataBindings=f;g.handler=function(c){var d,e=h[a];e&&0<e.length&&(d=Array.prototype.slice.call(arguments,1),f(c,d),b(e,c,d))};return g}function e(a){function b(a){0<k.length&&(a.cf(k),r(l,function(b){a.appendData(b)}),r(y,function(b){a.appendJs(b)}))}function d(a,b){return function(c){bt_log("Invalid "+
a+" expression: "+b+", exception = "+c)}}var e={},f={},h,g,k=[],l=[],y=[];e.execute=function(b,d){s(f,d||{});if(q.isFunction(b))g=b;else if(q.isString(b))a:{try{var h=C("events/"+a+"-tag-"+(f.tagId||"adhoc"));g=m.functionWithAccess(["eventObject","eventData"],b+h);break a}catch(k){c({type:"evparse",message:k.toString(),tagId:f.tagId||-1},{eventName:a})}g=void 0}else bt_log("when.execute: unknown action: "+b);return e};e.evaluate=function(a){h=a;return e};e.fire=function(a){k.push(a);return e};e.appendData=
function(a){l.push(a);return e};e.appendJs=function(a){y.push(a);return e};e.trigger=function(e,m,k){var l=d("post-event conditional fire",h);if(!h||z(h,l)){try{g&&g.call(e.target,e,m)}catch(y){c({type:"evwait",message:y.toString(),tagId:f.tagId||-1},{eventName:a})}b(k)}};return e}var f={},h={},m=ea(a,"BrightTag.jQuery"),k=/^direct\//i;f.executeActions=b;f.Binder=g;f.bind=function(a,b,c,d){var e=g(a,d,l.instance);m.ensureJQuery(function(){var a=m.getJQuery(),d=a(b);if(q.isString(b)&&!k.test(c)&&(d.on||
d.live))if(d.on)a(document).on(c,b,e.handler);else d.live(c,e.handler);else d.bind(c.split(k).pop(),e.handler)});return e};f.EventAction=e;f.when=function(a){var b=e(a),c=h[a];c||(c=h[a]=[]);c.push(b);return b};return f}function ua(a,d,c,b){function g(b,d,e){var f=a.group(e).options(d||{});f.wait(function(){c.process(f,b)})}var e=!1,f={};f[b]=!0;return{tag:function(c,d){var k;k=d&&d.group;k=!e&&!k?b:k;g(c,d,k);k&&void 0===f[k]&&(f[k]=!0,e&&a.run(k))},run:function(){a.addGlobalListener(Z(d,c));e=!0;
r(f,a.run)}}}function ha(a,d){function c(a){r(q.isArray(a)?a:[a],function(a){q.isFunction(a)?a():p.write('<script type="text/javascript" src="'+a+'">\x3c/script>')})}function b(a){var b=w.group().options({tagId:-2});r(q.isArray(a)?a:[a],function(a){(q.isFunction(a)?b.wait:b.script)(a)})}function g(a){p.write(a)}function e(a,b){B.tag(a,b)}function f(a){k.writeScript=a?c:b;k.appendContent=a?g:e}function h(a){r(a,function(a){if(a.name){var b=s({},a);delete b.name;delete b.value;t.set(a.name,a.value,
b)}})}function m(b){n.hasErrors()&&(b.appendParam("errors",n.toJSON()),b.tooLong()&&(b.deleteParam("errors"),n.tooManyErrors(),b.appendParam("errors",n.toJSON())));n.reset({site:a.site,referrer:a.referrer||p.location.href})}var k=this,v=a.data||{},p=a.document||{},K=a.window||{},w=a.blab||l.Blab,n=a.errorManager,t=a.store,u=ia(p),B=a.asyncTagManager||ua(w,p,u,"domready"),D=ea(window,"jquery");k.referrer=a.referrer;k.parentReferrer=a.parentReferrer;k.docReferrer=a.docReferrer;k.site=a.site;k.host=
a.host;k.loadOnly=!!a.loadOnly;n&&w.addGlobalListener(new ja(n));w.run("serializer");k.load=function(){var a=Array.prototype.slice.call(arguments,0);r(a,function(a){q.isFunction(a)?w.addToGroup("serializer",w.newEngine().wait(function(){a(k)})):q.isObject(a)&&a.src?k.library(a.src,a.options):q.isString(a)&&k.library(a)})};k.library=function(a,b){w.addToGroup("serializer",w.newEngine().options(b||{}).script(a))};f(A(a.mode,"sync"));k.domReady=function(){A(a.mode,"sync")&&f(!1);B.run()};k.parameter=
function(a){return window.bt_parameter(a,p)};k.meta=function(a){return window.bt_meta(a,p)};k.cookie=function(a){return window.bt_cookie(a,p)};k.data=function(a,b){if(void 0!==b)return v[a]=b;b=v[a];return null==b?"":b};k.dbe=function(a,b,c){function d(b){n&&n.push({type:"dbe",message:b.toString(),"dbe.name":a,pageId:(c||{}).pageId||-1})}null==v[a]&&k.data(a,z(b,d,"page-dbes/"+a+"-page-"+(c&&c.pageId||"adhoc")))};k.errors=function(a){l.V2_RESPONSE=!1;n.configure(a)};k.store=t?h:function(){};k.serverURL=
function(){return new fa(a)};k.defaultBaseUri=function(){return("https:"==p.location.protocol?"https:":"http:")+"//s.btstatic.com/"};k.baseUri=function(){var a=/\btag(\.[^.]+|-n)?\.js(#.*)?$/;return d&&d.src&&d.src.replace(a,"")||k.defaultBaseUri()};k.primary=function(){function a(){var b=k.serverURL();n&&(n.processStoredErrors(),m(b));return b.toString()}var b=[];K.JSON?b.push(a()):(b.push(k.baseUri()+"json2.js"),b.push(function(){k.writeScript(a())}));k.writeScript(b)};k.secondary=function(a){var b=
k.serverURL(),c=b.toString();a(b);b.toString()!=c&&(b.appendParam("mode","v1"),n&&m(b),b.isTooLarge()?k.post(b):k.writeScript(b.toString()))};k.post=function(a){D.ensureJQuery(function(){D.getJQuery().ajax({url:"//"+a.host+a.path,type:"POST",dataType:"text",success:bt_eval,data:a.queryString(),xhrFields:{withCredentials:!0}})})}}function F(){var a={},d={};return{on:function(c,b){var d=a[c];d||(d=a[c]=[]);d.push(b)},once:function(a,b){var g=d[a];g||(g=d[a]=[]);g.push(b)},emit:function(c){function b(a){a.apply(this,
g)}var g=Array.prototype.slice.call(arguments,1);r(a[c],b);r(d[c],b);d[c]=[]}}}function va(a){function d(a){return null!=g[a]}function c(a,b){void 0!==b&&(g[a]=b);var c=g[a];return null==c?"":c}var b,g=s({},a);return b=s({dbe:function(a,f,h){if(!d(a)&&(f=z(f,function(c){b.emit("error",c,a,h)}),null!=f))return c(a,f)},data:c,hasData:d},F())}function wa(a){var d,c={},b=["eventObject","eventData","$","bt_data"];return d=s({dbe:function(a,e){try{c[a]=new Function(b,"return "+e+";")}catch(f){f.type="evdbe",
d.emit("error",f,a)}return d},trigger:function(b,e,f){var h=b.target,m=[b,e,f,a.data];r(c,function(b,c){try{a.data(b,c.apply(h,m))}catch(e){e.type="evdbe",d.emit("error",e,b)}})}},F())}function xa(a){function d(a,c){c.type=a;b.emit("error",c)}function c(a){g.push(a);return b}var b,g=[],e=function(){return!0},f=["eventObject","eventData","$","bt_data"];return b=s({fire:function(a){return c(function(b){b.fire(a)})},appendData:function(a){return c(function(b){b.appendData(a)})},appendJs:function(a){return c(function(b){b.appendJs(a)})},
execute:function(e){function g(b,c,e,f){try{p.call(c.target,c,e,f,a.data)}catch(h){d("evwait",h)}}var k;if(q.isString(e))a:{try{k=new Function(f,e);break a}catch(l){d("evparse",l)}k=void 0}else k=e;var p=k;return p?c(g):b},evaluate:function(c){var d=new Function(f,"return "+c);e=function(b,c,e,f){return d.call(c.target,c,e,f,a.data)};return b},trigger:function(a,b,c,d){e(a,b,c,d)&&r(g,function(e){e(a,b,c,d)})}},F())}function ya(a){var d=/^direct\//i,c=!1;return{bind:function(a,c,e){function f(a){var b=
Array.prototype.slice.call(arguments,1);e(a,b,l.jQuery||window.jQuery)}var h=l.jQuery||window.jQuery,m=h(a),k=!q.isString(a)||d.test(c);if(!k&&m.on)h(document).on(c,a,f);else!k&&m.live?m.live(c,f):m.bind(c.split(d).pop(),f)},newBinder:function(a){return wa(a)},newHandler:function(a){return xa(a)},ensureLibrary:function(b){l.jQuery||window.jQuery?b():(c||(c=!0,a.run()),a.wait(b))}}}function za(a,d){function c(b,c,d,m){var k=S(a);r(b,function(a){a.trigger(k,c,d,m)});g.emit("triggered",k)}var b={},g=
F();return s(g,{bind:function(e,f,h,m){function k(a,d,f){l.trigger(a,d,f);c(b[e],a,d,f)}var l=d.newBinder(a,e);l.on("error",function(a,b){g.emit("error",a,{name:b,eventName:e},m)});d.ensureLibrary(function(){try{d.bind(f,h,k)}catch(a){g.emit("error",a,{eventName:e},m)}});return l},handle:function(c,f){var h=d.newHandler(a);h.on("error",function(a){g.emit("error",a,{eventName:c},f)});b[c]=b[c]||[];b[c].push(h);return h}})}function ia(a){function d(a,b){a.src?b.preemptScript(a.src,a.innerHTML):a.innerHTML&&
b.preemptWait(a.innerHTML)}function c(a,b){for(var f=a.childNodes||[],h=0,m=f.length;h<m;h++){var k=f[h];"SCRIPT"==k.tagName?d(k,b):c(k,b)}}var b=a.createElement("div");return{process:function(g,e){if(0!==e.length){b.innerHTML="<br/>"+e;for(var f=b.childNodes||[],h=1,m=f.length;h<m;h++){var k=f[h];if("SCRIPT"==k.tagName)d(k,g);else{try{a.body.appendChild(k.cloneNode(!0))}catch(l){bt_log("error appending content to body: "+l)}c(k,g)}}}}}}function Aa(a){function d(b){a.write(b);return c}var c={tag:d,
script:function(a){return d('<script type="text/javascript" src="'+a+'">\x3c/script>')},wait:function(a){a();return c}};return c}function Ba(a,d){function c(c,d){var h=c&&c.group;d(a.group(h).options(c||{}));h&&void 0===b[h]&&(b[h]=!0,a.run(h))}var b={},g={tag:function(a,b){c(b,function(b){b.wait(function(){d.process(b,a)})});return g},script:a.script,wait:a.wait};return g}function Ca(a,d){var c=d;return{tag:function(a,d){return c.tag(a,d)},script:function(a){return c.script(a)},wait:function(a){return c.wait(a)},
sync:function(){c=a},async:function(){c=d}}}function ja(a){return{dbe:function(d,c,b){a.push({type:"dbe",message:d.toString(),"dbe.name":c,pageId:(b||{}).pageId||-1})},events:function(d,c,b){var g=d.type,e="evdbe"===g?"pageId":"tagId",f={type:g,message:d.toString()};r(c,function(a,b){f[g+"."+a]=b});f[e]=(b||{})[e]||-1;a.push(f)},"block:error":function(d,c){var b,g,e;c&&(b=c.type,g=c.exception||c,e=d.option("tagId")||-1,a.push({type:b,message:g.toString(),tagId:e}))}}}function Da(a){function d(){var b=
new E(a.src),c={},d=b.fragment();c.staticHost=b.host+b.pathname;d&&r((new M(d)).params(),function(a,b){c[a]=1<b.length?b:b[0]});return c}function c(){var b=u(a.innerHTML);return 0===b.length?{}:z("(\n"+b+"\n)",function(a){bt_log("json configuration error: "+a)})}return{isTagjs:function(){return/\/tag(\.[^.]+|-n)?\.js(\?.*)?(#.*)?$/.test(a.src)},toJSON:function(){return s(d(),c())},script:a}}function Ea(a){return{isTagjs:function(){return!0},toJSON:function(){return a||{}},script:{src:void 0}}}function ka(){function a(){return d}
var d;return d={fire:a,appendData:a,appendJs:a,execute:a,when:a}}function S(a){function d(a,b){for(var c in a)if(b(c,a[c]))return!0;return!1}var c,b=[],g={};return c={toJSON:function(){var a=0<b.length?{cf:b.join()}:{};return s(a,g)},fire:function(a){q.isArray(a)||(a=[a]);a=T(a,function(a){return null!=a&&""!==a});b=b.concat(a);return c},appendData:function(b){var d=a.data(b);g["_cb_bt_data('"+b+"')"]=q.isArray(d)||q.isObject(d)?JSON.stringify(d):d;return c},appendJs:function(a){g["_cb_"+a]=z(a);
return c},execute:function(a){a();return c},when:function(b){var d;try{return d=new Function(["bt_data"],"return "+l.trim(b)),d(a.data)?c:ka()}catch(h){bt_log("conditional evaluation error: ["+h.toString()+"] while evaluating ["+b+"]")}return ka()},hasConditions:function(){return 0<b.length||d(g,function(a,b){return null!=b})}}}function Fa(a,d,c,b,g,e){function f(){t=!0;d.async();n.mode=x.filter(n.mode,function(a){return"sync"!==a})}function h(a){if(null==a||a.hasConditions())b.reset({site:n.site,
referrer:n.referrer||window.location.href})}function m(a){var c=E("//"+r+"/tag").appendParams({site:n.site,mode:n.mode,H:n.H,referrer:n.referrer,docReferrer:n.docReferrer}).appendParam("mode","v2").alwaysAppendParams(a);(a=I.get("X-BT-InspectSession"))&&c.appendParam("inspect-session",a);g.findEach(RegExp("^btp(s|db)\\."+n.site+"\\..+"),function(a,b){c.appendParam(a,b)});return c.appendParams({errors:b.hasErrors()?b.toJSON():null})}function k(a){if(null==a)return m();if(a.hasConditions())return m(a.toJSON())}
function q(a){var b=k(a);b?(h(a),b.tooLong()?u.ensure("jQuery",function(){l.jQuery.ajax({url:b.origin+b.path,type:"POST",data:b.queryString(),xhrFields:{withCredentials:!0}})}):d.script(b.toString())):h(a)}var p,n=x.extend({},e),r=n.host||"",s=F(),t=!1,u=new Ga(d,n);c.on("triggered",q);return p=x.extend({config:n,diagnostic:function(a){a&&(n.diagnostic=a,p.emit("diagnostic",a))},errors:function(a){b.configure({timestamp:a})},dbe:function(b,c,d){var e=a.dbe(b,c,d);null!=e&&p.emit("dbe",b,c,e,d)},data:a.data,
dataref:function(a){return null==a?"":'BrightTag.site("'+n.site+'").data("'+a.replace(/"/g,"\\x22")+'")'},store:function(a){x.each(a,function(a){if(a.name){var b=x.extend({},a);delete b.name;delete b.value;g.set(a.name,a.value,b)}})},tag:function(a,b){p.emit("tag",a,b);return d.tag(a,b)},script:d.script,wait:d.wait,events:{bind:function(a,b,d,e){p.emit("event-binding",a,b,d,e);return c.bind(a,b,d,e)},on:c.handle},when:function(b,c){S(a).when(b).execute(function(){c(p)});return p},domready:function(a){if(null==
a)f();else s.once("domready",a);t&&s.emit("domready",p)},primary:function(){u.ensure("JSON",function(){b.processStoredErrors();q()})},secondary:function(b){var c=S(a);b(c);q(c)}},F())}function Ha(a){a=E(a.staticHost+"/BrightTag.jquery-1.5.1.js");return ya((new W(document)).script(a))}function Ia(a,d,c){var b=Aa(document);a=Ba(a,d);b=Ca(b,a);x.contains(c.mode,"sync")&&b.sync();return b}function Ja(a){var d,c,b,g,e,f,h,m;if((h=a.site)&&!N[h])return d=va(a.data),c=new $(document),m=ia(document),b=Ia(c,
m,a),e=za(d,Ha(a)),f=da(G?L(G,I):I,"__bterr_"+h,{site:h,referrer:a.referrer,enabled:!1}),g=ja(f),d.on("error",g.dbe),e.on("error",g.events),c.addGlobalListener(g),l.Events.onDOMReady(function(){c.addGlobalListener(Z(document,m))}),a=N[h]=Fa(d,b,e,f,G?L(I,G):I,a)}function la(a,d,c){try{var b,g,e=a.toJSON();if(!(l.instance&&l.instance.site===e.site)){var f=s({host:"s.thebrighttag.com",staticHost:"s.btstatic.com",H:V(e.referrer||d.location.href),referrer:e.referrer||d.location.href,docReferrer:d.document.referrer},
e);b=Ja(f);if(e.site&&!l.instance&&!ma&&!A(e.mode,"v2")&&!A(e.mode,"v2b")){var h=a.script,m=na();l.EventBinding=ga(m.window,m.errorManager);l.instance=new ha(s(m,e),h);g=l.instance;b.config.loadOnly=!0}else if(b){var k=b.config,n;var p=b.config.mode;n=A(p,"v2")?p:!p?"v2":["v2"].concat(p);k.mode=n}c&&c(b,g);return b}}catch(q){bt_log("error configuring site ["+a.script.src+"]: "+q)}}function Ka(a){var d,c,b=[];if(q.isArray(a))b=a.slice(0);else{d=0;for(c=a.length;d<c;d++)b.push(a[d])}return b}function La(a){if(!ma&&
!A(a.config.mode,"v2")&&!A(a.config.mode,"v2b"))l.Events.onDOMReady(function(d){a.domready()});else a.config.loadOnly||(l.Events.onDOMReady(function(d){a.domready()}),a.primary())}function na(){var a,d=aa(document),c=d,b=d;try{window.localStorage&&window.sessionStorage&&(a=ba(sessionStorage,localStorage),a.purge(),c=L(d,a),b=L(a,d))}catch(g){bt_log("Unable to access DOM storage: "+g)}return{id:Math.random(),loadOnly:!1,window:window,document:document,host:"s.thebrighttag.com",parentReferrer:top!=
self&&self.window?self.window.location.href:null,docReferrer:document.referrer,data:{},store:c,errorManager:da(b,"__bterr")}}if(l)return l;var ma=!1;l={};var q={isString:function(a){return n(a,"String")},isArray:function(a){return n(a,"Array")},isNumber:function(a){return n(a,"Number")},isBoolean:function(a){return n(a,"Boolean")},isFunction:function(a){return n(a,"Function")},isObject:function(a){return null===a||void 0===a?!1:n(a,"Object")}},z=bt_eval,P=Array.prototype.forEach?Array.prototype.forEach:
H,qa=Array.prototype.filter?Array.prototype.filter:pa,Ma=Array.prototype.map?Array.prototype.map:ra,x={contains:A,each:r,extend:s,filter:T,map:function(a,d,c){if(a)return Ma.call(O(a)?a:[a],d,c)},trim:u},sa=function(){function a(){}function d(a,b,c){try{a[b]=c}catch(d){bt_log("warning: could not assign value to 'document."+b+"': "+d)}}var c,b=[],g=function(a){c.push(a)};return function(e,f){var h;this["block:start"]=function(){b.push([c,e.write,e.writeln,e.open,e.close]);c=[];d(e,"write",g);d(e,"writeln",
g);d(e,"open",a);d(e,"close",a)};this["block:finish"]=function(){try{f.process(h,c.join(""))}finally{var a=b.pop();c=a[0];d(e,"write",a[1]);d(e,"writeln",a[2]);d(e,"open",a[3]);d(e,"close",a[4])}};this["engine:listen"]=function(a){h=a}}}(),ta=/^(?:([^:\/]+:)?\/\/)?([^:\/?#]+)?(:[0-9]+)?([^?#]*)(\?[^#]*)?(#.*)?$/,Ga=function(){function a(a,b){this.tagMgrRouter=a;this.config=b}var d={JSON:{object:"JSON",path:"/json2.js"},jQuery:{object:"BrightTag.jQuery",path:"/BrightTag.jquery-1.5.1.js"}};a.prototype=
{ensure:function(a,b){var g=d[a];if(g){var e=g.object.split("."),f=window,h=e.length-1,l,k;for(k=0;k<h;k++){l=e[k];f=f[l];if(!f)throw"DependencyManager: Could not find key "+l;f=f[e[k]]}f?b():this.tagMgrRouter.script(E(this.config.staticHost+g.path)).wait(b)}}};return a}(),N={},G,I=aa(document);try{window.localStorage&&window.sessionStorage&&(G=ba(sessionStorage,localStorage),G.purge())}catch(Na){bt_log("Unable to access DOM storage: "+Na)}l.Escaper={cookie:U,javascript:function(a){return!q.isString(a)?
a:a.replace(/\\/g,"\\\\").replace(/'/g,"\\x27").replace(/"/g,"\\x22").replace(/\n/g,"\\n").replace(/\r/g,"\\r")}};l.Random={integer:function(a){return Math.floor(Math.random()*(a||1E8))}};l.pushIfDefined=function(a,d,c){a&&(a.constructor==Array&&null!=d)&&a.push(c||d)};l.ServerURL=fa;l.Main=function(a){function d(b){(b=(new E(b.src)).fragment())&&r((new M(b)).params(),function(b,c){a[b]=c[0]})}function c(b){function c(a){bt_log("configuration error: "+a)}b=u(b.innerHTML);0!==b.length&&s(a,z("(\n"+
b+"\n)",c,"site-config"))}var b,g=function(){var b,c,d=/\/tag(\.[^.]+|-n)?\.js(#.*)?$/,e=a.document.getElementsByTagName("script");for(b=e.length-1;-1<b;b--)if(c=e[b],d.test(c.src))return c}();g&&(d(g),c(g));if(null!=a.site){l.Events.enablePageReadyOverrides();try{b=new ha(a,g),l.Events.onDOMReady(b.domReady),b.loadOnly||b.primary()}catch(e){bt_log("execution error: "+e)}return b}};l.CookieSync={pushImage:function(a){(new Image).src=a;throw"CookieSync.pushImage no longer supported ["+a+"]";},pushIframe:function(a){throw"CookieSync.pushIframe no longer supported ["+
a+"]";}};l.EventBindingManager=ga;l.defaultConfig=na;l.eval=z;l.Types=q;l.trim=x.trim;l.Util=x;l.each=x.each;l.extend=x.extend;l.HTTP={Cookie:R,QueryString:M,URL:E};l.Blab=new $(document);l.Events=new function(a,d){function c(){}function b(a,b,c){a[r](t+b,c,!1)}function g(a,b,c){a[s](t+b,c,!1)}function e(){var a=d.readyState;if("loading"==a)return!1;if("complete"==a)return!0;a:{try{u("left")}catch(b){a=!1;break a}a=!0}return a}function f(a,b,c){var d=this;setTimeout(function(){a()?b.call(d):f(a,b,
c)},c)}function h(){h=c;n&&ca(d,p,d)}function l(){h();ca(a,q,d)}var k=this,n=!!a.addEventListener,p="DOMContentLoaded",q="load",r=n?"addEventListener":"attachEvent",s=n?"removeEventListener":"detachEvent",t=n?"":"on",u=d.documentElement.doScroll||function(){throw"No doScroll";};k.listen=b;k.unlisten=g;k.onDOMReady=function(c){e()?c.call(this):d.addEventListener?(b(d,p,c),b(d,p,function(){g(a,q,c)}),b(a,q,c)):f(e,c,1)};k.enablePageReadyOverrides=function(){k.enablePageReadyOverrides=c;e()?l():(n&&
b(d,p,h),b(a,q,l))}}(window,document);l.Events.enablePageReadyOverrides();l.Content=new function(a){a=a||l.Blab;return{iframe:a.iframe,image:a.image,link:a.link,script:a.script}}(l.Blab);l.V2_RESPONSE=!0;l.site=function(a,d){try{var c=N[a];c&&d&&d(c);return c}catch(b){bt_log("error while executing site configuration ["+a+"]: "+b)}};l.configureNewSites=function(a,d){r(Ka(a.document.getElementsByTagName("script")),function(c){c=Da(c);c.isTagjs()&&la(c,a,d)})};l.configureSite=function(a,d,c){return la(Ea(a),
d,c)};l.configuredSites=function(){var a=[];x.each(N,function(d,c){a.push(c)});return a};l.initializeSite=function(a,d){d&&(l.Events.onDOMReady(d.domReady),d.loadOnly||d.primary());a&&La(a)};return l}(window.BrightTag);(function(l){l.configureNewSites(window,l.initializeSite);null==l.instance&&setTimeout(function(){null==l.instance&&l.configureNewSites(window,l.initializeSite)},0)})(BrightTag);var _bt_url_prefix,_bt_referrer,_bt_site,_bt_mode;
function btServe(l){var n=BrightTag,u={referrer:_bt_referrer,site:_bt_site,mode:_bt_mode};null!=_bt_url_prefix&&(u.host=_bt_url_prefix);n.configureSite(n.extend(u,l),window,n.initializeSite)};
