window.HAO.https||(alog&&alog("speed.set","c_jl",+new Date),alog.fire&&alog.fire("mark"));
(function(m,e,j,a){function c(b){var g,d,f,h,e,i;g=x[b];if(!g)throw Error('Requiring unknown module "'+b+'"');if(g.hasOwnProperty("exports"))return g.exports;g.exports=b={};d=g.deps;i=d.length;e=-1;for(h=[];++e<i;)f=d[e],h.push("module"===f?g:"exports"===f?b:c(f));if((d=g.factory.apply(null,h))!==a)g.exports=b=d;return b}function d(a,b,c){b=["global","require","module","exports"].concat(b);x[a]={factory:c,deps:b}}function b(a,c,g){var d=Array.prototype.slice;b=function(a,b,c){var g=d.call(arguments,
1);return d.apply(a,g)};return b.apply(this,b(arguments,0))}function f(a,b){b=b||j;return b.getElementById(a)}function g(a){for(var a=a||{},b=arguments,c=b.length,g=0,d,f;++g<c;)for(f in d=b[g],d)d.hasOwnProperty(f)&&(a[f]=d[f]);return a}function h(a,b,c){var d;this instanceof h?(this.constructor=a,g(this,c)):(d=h.prototype,h.prototype=b.prototype,a.prototype=new h(a,b,c),h.prototype=d)}function i(){function a(){for(var b=-1,f;++b<d;)f=c[b],f[0].apply(f[1],f[2]),delete c[b];c=[];d=0;g=null}var c=
[],g=null,d=0;i=function(f,h,e){if(!f)return i;c.push([f,h||this,b(arguments,2)]);d++;null===g&&(g=setTimeout(a,0));return g};return i.apply(this,b(arguments,0))}function k(a){var b,c=j.getElementsByTagName("head");b=c.length&&c[0]||j.body;k=function(a){b.appendChild(a)};return k(a)}function n(b,c){var g=s(b)?[]:{};"function"!=typeof c&&(c=c===a?function(a,b){return!!b}:function(a,b){return b==c});l(b,function(a,b){c(a,b)&&(g[a]=b)});return g}function o(a,b,c){var g,d;g=j.createElement(a);d=g.style;
b&&l(b,function(a,b){g[a]=b});d&&c&&l(c,function(a,b){d[a]=b});return g}function l(a,b){p(a,function(a,c){b(a,c);return!1})}function p(b,c){var g;g=b.length;return(g===a||q(b)?function(a,b){for(var c in a)if(a.hasOwnProperty(c)&&b(c,a[c]))return!0;return!1}:function(a,b){var c;for(c=0;c<g;c++)if(b(c,a[c]))return!0;return!1})(b,c)}function r(a){for(var b="Boolean,Number,String,Function,Array,Date,RegExp,Object".split(","),c=b.length,g=Object.prototype.toString,d={},f;c--;)f=b[c],d["[object "+f+"]"]=
f.toLowerCase();r=function(a){return null==a?""+a:d[g.call(a)]||"object"};return r(a)}function q(a){return"function"===r(a)}function s(a){function b(a){return"array"===r(a)}s=Array.isArray||b;return s(a)}function q(a){return"[object Function]"==Object.prototype.toString.call(a)}function y(a,c){return u(a,c,b(arguments,2))}function u(a,b,c){v.push([a,b,c]);if(!w){for(w=!0;a=v.length;){for(b=0;b<a;b++)c=v[b],c[0].apply(c[1],c[2]);v.splice(0,a)}w=!1}}function A(a,b){var c=[],g=a.length;if("function"!==
typeof b)return a;for(;g--;)c.unshift(b(a[g]));return c}var x={};x.global={exports:m};x.require={exports:c};var t={addHandler:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent?a.attachEvent("on"+b,c):a["on"+b]=c},getEvent:function(a){return a?a:e.event},getTarget:function(a){return a.target||a.srcElement},preventDefault:function(a){a.preventDefault?a.preventDefault():a.returnValue=!1},stopPropagation:function(a){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0},removeHandler:function(a,
b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent?a.detachEvent("on"+b,c):a["on"+b]=null}},v=[],w=!1;d("Arbiter",["global","ErrorUtils"],function(a,c){function d(a){this._listenerMap={};this._setup(a||[])}var a=c("global"),f=c("ErrorUtils");g(d.prototype,{_setup:function(a){for(var b=a.length,c=this._listenerMap;b--;)c[a[b]]={args:null,cbs:[]}},on:function(c,g,d){var f=this._listenerMap[c],h,e;if(!f)return!1;d=d||a;h=b(arguments,3);(e=f.args)?u(g,d,h.concat(e)):f.cbs.push([g,
d,h]);return!0},done:function(a,c){var g=this._listenerMap[a],d,f,h;if(!g)return!0;f=g.cbs;h=f.length;c=b(arguments,1);g.args=c;d=this.emit.apply(this,arguments);g.cbs=f.slice(h);return d},emit:function(a,c){var g=this._listenerMap[a],d,h,e;if(!g)throw Error(a+" has not listened");c=b(arguments,1);g=g.cbs;d=g.length;h=-1;for(e=!0;++h<d;){var i;i=g[h];var k=c,l=i[0],o=i[1],k=i[2].concat(k);i=f.inGuard()?l.apply(o,k):f.applyWithGuard(l,o,k);e=!1!==i&&e}return!!e},undo:function(a){a=this._listenerMap[a];
if(!a)return!1;a.args=null}});return d});d("Resource",["Arbiter","CSSLoader","JSLoader"],function(b,c){function d(a,b){if(this instanceof d)k.call(this,B),this.id=a,this.deps=b,this.loaded=!1,this.state=C;else return f(a)}function f(a){var b,c;if(!(b=l[a]))throw Error('resource "'+a+'" unknow.');if(!(c=b._handler))c=b._handler=new d(a,b.deps||[]),b._loaded&&(c.loaded=!0);return c}function e(a,b){o[a]=b}function i(b,c){var d;if(c!==a)d=l[b]||{},g(d,c),l[b]=d;else for(b in c=b,c)i(b,c[b])}var k=c("Arbiter"),
l={},o={},n={},B=["load","resolve"],C=1;h(d,k,{load:function(){function a(){--g||(k=!0,i&&this.done("resolve"))}function b(){i=!0;this.done("load");k&&this.done("resolve")}var c,g,f,h,e,i,k;if(2<=this.state)return!1;this.state=2;i=this.loaded;k=!0;c=this.deps;f=g=c.length;if(0<f){k=!1;for(h=-1;++h<f;)e=d(c[h]),e.on("resolve",a,this),e.load()}y(function(){var a;if(i)y(b,this);else{a=this.id;var c,g,d;c=l[a];g=c.type;if(!(d=o[g]))throw Error('unknow type "'+g+'"');a=new d(a,c);a.on("load",b,this);a.load()}},
this)}});g(d,{setResourceMap:i,setModuleMap:function(a){g(n,a)},setResourceLoaded:function(a){var b;for(b=a.length;b--;)i(a[b],{_loaded:!0})},moudelToResource:function(a){var b=n[a];if(!b)throw Error('module "'+a+'" unknow.');return f(b)}});e("css",c("CSSLoader"));e("js",c("JSLoader"));return d});d("Pagelet",["Arbiter","Resource"],function(a,b){function c(a){if(this instanceof c)d.call(this,k),this.id=a,this.root=null===a,this.state=l;else{var b;if(null===a)return new c(a);b=o[a];b||(b=new c(a),o[a]=
b);return b}}var d=b("Arbiter"),e=b("Resource"),k="arrive,beforeload,cssresolved,jsresolved,beforedisplay,display,load,afterload,resolved,beforeunload,unload,afterunload".split(","),l=0,o={},n={};h(c,d,{arrive:function(a){g(this,{html:a.html||"",css:a.css||[],js:a.js||[],parent:a.parent?c(a.parent):null,children:a.children||[],state:1});this.afterload=!1;this.done("arrive");this.emit("beforeload")?this.load():(this.afterload=!0,this.done("afterload"))},load:function(){function a(){this.parent.on("display",
b,this)}function b(){this.emit("beforedisplay")&&this.display()}if(2<=this.state)return!1;this.state=2;this.on("cssresolved",this.parent?a:b,this);this._resolve(this.css,"cssresolved");this._resolve(this.js,"jsresolved")},setState:function(){if(3>this.state)return!1;this.state=4;var a,b,g,d;a=this.children;b=a.length;g=-1;if(b)for(;++g<b;)d=a[g],d=c(d),d.setState()},doUnload:function(){function a(){--b||this.emit("beforeunload")&&this.unload()}var b,g,d,f,h;g=this.children;d=b=g.length;f=-1;if(d)for(;++f<
d;)h=g[f],h=c(h),h.on("unload",a,this),h.doUnload();else this.emit("beforeunload")&&this.unload()},remove:function(){if(4==this.state)return!1;this.setState();this.on("unload",this.destroy,this);this.doUnload()},unload:function(){this.done("unload")},destroy:function(){var a,b,g,d;a=this.children;b=a.length;g=-1;if(b)for(;++g<b;)d=a[g],d=c(d),d.destroy();delete o[this.id];this.state=l;i(this.done,this,"afterunload")},isUnloading:function(){return 4==this.state},_resolve:function(a,b){function c(){--g||
this.done(b)}var g,d,f,h;d=g=a.length;f=-1;if(d)for(;++f<d;)h=e(a[f]),h.on("resolve",c,this),h.load();else this.done(b)},display:function(){if(3<=this.state)return!1;this.state=3;this.root||(f(this.id).innerHTML=this.html);this.done("display");this.on("jsresolved",function(){this.done("load");this.afterload||this.done("afterload")},this)},get:function(a,b){return n[a]||b},set:function(a,b){n[a]=b}});g(c,{hasPagelet:function(a){return!!o[a]}});return c});d("BigPipe",["Resource","Emulator","Arbiter",
"Requestor","ErrorUtils"],function(a,b){function c(){i.call(this);this.hooks={}}function d(a){return!a||"string"!=typeof a?a:a.replace(/["'<>\\\/`]/g,function(a){return"&#"+a.charCodeAt(0)+";"})}var g=!1,f=b("Resource"),e=b("Emulator"),i=b("Arbiter"),k=b("Requestor"),l=b("ErrorUtils"),n=!1;h(c,i,{init:function(a){var b=!!a.debug;if(n)throw Error("BigPipe has been initialized.");n=!0;this.emulator=e();this.emulator.listen();this.emulator.on("request",this.request,this);this.requestor=new k(a);l.setConfig("nocatch",
b);if(g=b){var c=!0;this.console=o("ul",null,{cssText:"position:fixed;_position:absolute;top:0;left:0;z-index:999;border:1px solid #ddd;border-bottom:none;font-family:monospace;background:#000;color:#dadada"});this.console.onmouseover=function(){c?(this.style.left="auto",this.style.right="0"):(this.style.left="0",this.style.right="auto");c=!c};j.body.appendChild(this.console)}},onPageletArrive:function(a){var b=a.callback,c,g,d,h,e,i,k=this.hooks;if(b){c=a.hook||{};for(var l in b){g=b[l];d=-1;h=g.length;
for(e=c[l]||[];++d<h;)i=g[d],e.push(k[i]),delete k[i];c[l]=e}a.hook=c}f.setResourceMap(a.map||{});f.setModuleMap(a.mods||{});this.requestor.arrive(a)},request:function(a,b){this.requestor.request(a,b)},sessionStart:function(a){this.requestor.start(a)},sessionEnd:function(a){this.requestor.end(a)},loadModule:function(a,b){var c=f.moudelToResource(a);c.on("resolve",b);c.load()},loadedResource:function(a){f.setResourceLoaded(a)},log:function(){if(g){var a=this.console,b,c,f;if(a){for(c=0,b=arguments.length,
f=[];c<b;c++)f.push(d(""+arguments[c]));a.appendChild(o("li",{innerHTML:f.join(" ")},{cssText:"border-bottom:1px solid #ddd"}))}}}});return c});d("CSSLoader",["Arbiter"],function(a,b){function c(a,b){u.call(this,q);this.id=a;this.url=b.src;this.state=y}function g(a){z||(z=j.createElement("meta"),k(z));v=a||v;z.className=v.join(" ")}function d(a){return!a?!1:(a=e.getComputedStyle?getComputedStyle(a,null):a.currentStyle)&&1<parseInt(a.height,10)}function f(){var a,b,c,h,e,i,k,l,o,n,p,u;b=2<v.length?
d(z):!0;c=0;h=[];e=!1;i=+new Date;for(a in w){k=w[a];l=k[0];o=!1;b&&d(l)&&(o=!0);for(p=1,n=k.length;p<n;p++)u=k[p],o?u[1].call(u[2],!0):u[0]<i&&(u[1].call(u[2],!1),k.splice(p,1),p--,n--);o||1==n?(l.parentNode.removeChild(l),delete w[a],e=!0):(h.push("css_"+a),c++)}c?(e&&g(h),setTimeout(f,20)):(v=[],z&&(z.parentNode.removeChild(z),z=null),s=!1)}function l(a,b,c,d){var h,e;if(!(h=w[a]))e="css_"+a,h=j.createElement("meta"),h.className=e,k(h),h=[h],w[a]=h,v.push(e),g();b=+new Date+b;h.push([b,c,d]);s||
(s=!0,i(f))}function o(a){this.state=a?r:A;this.done("load",a)}function n(){var a=this.id,b=this.url,c=j.createElement("link");c.rel="stylesheet";c.type="text/css";c.href=b;k(c);l(a,m,o,this)}function p(){for(var a=this.id,b=this.url,c=x.length,d=c,g;d--;)if(31>x[d].length){g=t[d];break}0>d&&(g=j.createStyleSheet(),t.push(g),x.push([]),d=c);g.addImport(b);x[d].push(b);l(a,m,o,this)}var u=b("Arbiter"),q=["load"],y=1,r=3,A=4,m=5E3,s=!1,x=[],t=[],w={},v=[],z=null;h(c,u,{load:function(){2>this.state&&
(this.state=2,this._load())},_load:j.createStyleSheet?p:n});return c});d("JSLoader",["Arbiter"],function(b,c){function d(a,b){g.call(this,f);this.id=a;this.url=b.src;this.state=l}var g=c("Arbiter"),f=["load"],l=1,o=3,n=4;h(d,g,{load:function(){function b(h){if(!(c.state>=o)){c.state=h?o:n;c.done("load");e[d]=g;if(g===a)try{delete e[d]}catch(k){}i(function(){f.onerror=null;f.parentNode&&f.parentNode.removeChild(f);f=null})}}var c=this,d,g;if(!(2<=this.state)){this.state=2;var f=j.createElement("script");
f.src=this.url;f.async=!0;f.onerror=function(){b(!1)};d="js_"+this.id;g=e[d];e[d]=b;k(f)}}});return d});d("Emulator",["Arbiter"],function(a,b){function c(a){var b=!1;if(a&&(a=(""+a).replace(/(^\s*)|(\s*$)/g,"")))b=n(a.split(" "),function(a,b){return!!(""+b).replace(/(^\s*)|(\s*$)/g,"")});return b}function d(a){var b,g;for(b="A";a&&a.nodeName!=b;)a=a.parentNode;if(!a)return!1;if(!this.emit("beforetrigger",a))return!0;b=a.href;if(!b)return!1;var f=!1,h=/^\s*(https?|ftp):\/\//i;b==i||0==b.indexOf(i+
"/")?f=b.substring(k)||"/":h.test(b)||(f=b);b=f;if(!b)return!1;(a=a.rel)&&(g=c(a));if(!g)return!1;this.emit("request",b,g);return!0}function g(){if(this instanceof g)f.call(this,l);else return e||(e=new g),e}var f=b("Arbiter"),e,i,k,l=["beforetrigger","request"];i=[location.protocol,"//",location.host].join("");k=i.length;h(g,f,{listen:function(){var a=this;t.addHandler(j.documentElement,"click",function(b){var c,b=t.getEvent(b);c=t.getTarget(b);d.call(a,c)&&t.preventDefault(b)})}});return g});d("Requestor",
["Arbiter","Controller"],function(a,b){function c(a){d.call(this,e);g(this,{ajaxKey:a.ajaxKey,separator:a.separator,sessionKey:a.sessionKey});k||this.init()}var d=b("Arbiter"),f=b("Controller"),e=["arrive","allarrived"],i={},k=!1,n=!1,p=0;h(c,d,{init:function(){k=!0;this.sessionState=this.state=0;this.controller=new f;this.controller.on("arrived",this._onItemArrived,this);this.on("allarrived",this._onSessionEnd,this);this.refCount=0},start:function(a){this.sessionID=a;switch(this.sessionState){case 1:case 2:case 3:this.sessionState=
2;break;case 0:this.sessionState=1}},end:function(){this.sessionState=3;0==this.refCount&&this._onSessionEnd()},arrive:function(a){var b=this.sessionID,c=this.sessionState;i[b-1]&&(i[b-1]=null);2==c||3==c?(i[b]=i[b]||[],i[b].push(a)):(++this.refCount,this.controller.handdleArrive(a))},request:function(a,b){p++;this._ajaxRequest([a,/.*\?.*/.test(a)?"&":"?",this.ajaxKey,b?"="+b.join(this.separator):"","&",this.sessionKey,"=",p].join(""))},_onSessionEnd:function(){this.sessionState=0;var a=i[this.sessionID],
b=this;a&&l(a,function(a,c){b.refCount++;b.controller.handdleArrive(c)})},_onItemArrived:function(){!--this.refCount&&3==this.sessionState&&this.emit("allarrived")},_ajaxRequest:function(a){switch(this.state){case 1:var b=this._ajaxIframe;b&&b.parentNode&&b.parentNode.removeChild(b);this._initAjaxIframe(a);break;case 0:this._initAjaxIframe(a),this.state=1}},_initAjaxIframe:function(a){var b=this;this._ajaxIframe=o("iframe",{src:a},{display:"none"});j.body.appendChild(this._ajaxIframe);clearTimeout(n);
t.addHandler(this._ajaxIframe,"load",function(){1==b.state&&(n=setTimeout(function(){var a=b._ajaxIframe;a&&a.parentNode&&a.parentNode.removeChild(a);b.state=0},100))})}});return c});d("Controller",["Arbiter","Pagelet","Resource"],function(a,b){function c(){g.call(this,i)}function d(a,b){var c=f(a,b),g;if(!(g=c.firstChild)||8!==g.nodeType)return null;g=g.nodeValue;c.parentNode.removeChild(c);g=g.slice(1,-1);return g.replace(/--\\>/g,"--\>").replace(/\\\\/g,"\\")}var g=b("Arbiter"),e=b("Pagelet");
b("Resource");var i=["arrived"];h(c,g,{handdleArrive:function(a){var b,c;c=a.id;e.hasPagelet(c)&&(b=e(c),b.remove());if(e.hasPagelet(c))if(b=e(c),b.isUnloading())b.on("afterunload",this._doArrive,this,a);else throw Error("unbeliveble");else this._doArrive(a)},_doArrive:function(b){var c,g,f,h,i,k,l,o;c=b.id||null;g=b.content?b.content:b.container_id?d(b.container_id,b.doc):null;b.html=g;g=e(c);if(f=b.hook)for(h in f){i=f[h];l=i.length;for(k=-1;++k<l;){o=i[k];try{g.on(h,q(o)?o:new Function("pagelet",
o),a,g)}catch(n){throw Error("Error on add script:"+i[k]);}}}g.arrive(b);g.on("afterload",function(a){this.emit("arrived",a)},this,c)}});return c});d("ErrorUtils",["wrapFunction"],function(a,b,c){function g(a){if(!a)return[];a=a.split(/\n\n/)[0].replace(/[\(\)]|\[.*?\]|^\w+:\s.*?\n/g,"").split("\n");return a=A(a,function(a){var b,c,g,a=a.trim();/(:(\d+)(:(\d+))?)$/.test(a)&&(c=RegExp.$2,g=RegExp.$4,a=a.slice(0,-RegExp.$1.length));if(y.test(a)||/(.*)(@|\s)[^\s]+$/.test(a))a=a.substring(RegExp.$1.length+
1),b=/(at)?\s*(.*)([^\s]+|$)/.test(RegExp.$1)?RegExp.$2:"";a={identifier:b,script:a,line:c,column:g};m&&m(a);a.text="    at"+(a.identifier?" "+a.identifier+" (":" ")+a.script+(a.line?":"+a.line:"")+(a.column?":"+a.column:"")+(a.identifier?")":"");return a})}function d(a){if(a){if(a._originalError)return a}else return{};var b=g(a.stackTrace||a.stack),c=!1;if(a.framesToPop){for(var f=a.framesToPop,h;0<f&&0<b.length;)h=b.shift(),f--,c=!0;j.test(a.message)&&2===a.framesToPop&&h&&q.test(h.script)&&(a.message+=
" at "+h.script+(h.line?":"+h.line:"")+(h.column?":"+h.column:""));delete a.framesToPop}f={line:a.lineNumber||a.line,column:a.columnNumber||a.column,name:a.name,message:a.message,type:a.type,script:a.fileName||a.sourceURL||a.script,stack:A(b,function(a){return a.text}).join("\n"),stackFrames:b,guard:a.guard,guardList:a.guardList,extra:a.extra,snapshot:a.snapshot};"string"!==typeof f.message&&(f.messageObject=f.message,f.message=""+f.message);m&&m(f);c&&(delete f.script,delete f.line,delete f.column);
b[0]&&(f.script=f.script||b[0].script,f.line=f.line||b[0].line,f.column=f.column||b[0].column);f._originalError=a;for(var e in f)null==f[e]&&delete f[e];return f}function f(a){if(v)return!1;0<t.length&&(a.guard=a.guard||t[0],a.guardList=t.slice());a=d(a);s.length>x&&s.splice(x/2,1);s.push(a);v=!0;for(var b=0;b<r.length;b++)try{r[b](a)}catch(c){}v=!1;return!0}function h(a,b,c,g,e){t.unshift(e||n);w=!0;var i;if(o.nocatch||/nocatch/.test(location.search)){try{i=a.apply(b,c||[])}finally{t.shift(),w=0!==
t.length}return i}try{return i=a.apply(b,c||[])}catch(k){b=d(k),g&&g(b),a&&(b.callee=a.toString().substring(0,100)),c&&(b.args=Array.prototype.slice.call(c).toString().substring(0,100)),b.guard=t[0],b.guardList=t.slice(),f(b)}finally{t.shift(),w=0!==t.length}}function i(a,b,c){b=b||a.name||p;return function(){return h(a,c||this,arguments,null,b)}}function k(a,b,c,g,d){d=d||{};d.message=d.message||a;d.script=d.script||b;d.line=d.line||c;d.column=d.column||g;d.guard=u;d.guardList=[u];f(d)}var o={},
n="<anonymous guard>",p="<generated guard>",u="<window.onerror>",q=/^https?:\/\//i,j=/^Type Mismatch for/,y=/(.*?)(\s)(?:Unknown script code|Function code|eval code)$/,r=[],m,s=[],x=50,t=[],w=!1,v=!1;b("wrapFunction").setWrapper(i,"entry");e.onerror=k;c.exports={ANONYMOUS_GUARD_TAG:n,GENERATED_GUARD_TAG:p,GLOBAL_ERROR_HANDLER_TAG:u,addListener:function(a,b){r.push(a);b||l(s,a)},setSourceResolver:function(a){m=a},applyWithGuard:h,guard:i,history:s,inGuard:function(){return w},normalizeError:d,onerror:k,
reportError:f,setConfig:function(a,b){o[a]=b}}});d("wrapFunction",[],function(a,b,c){function g(a,b,c){b=b||"default";return function(){var a=b in d?d[b](a,c):a;return a.apply(this,arguments)}}var d={};g.setWrapper=function(a,b){d[b||"default"]=a};c.exports=g});var D=c("BigPipe");m.BigPipe=new D;m.BigPipe.ErrorUtils=c("ErrorUtils")})(this,window,document);
(function(m,e){function j(b,c,g,d){var f,h,e;h=c.length;f=k[b]||{};f.name=b;f.factory=g;f.deps=c;f.flag=d||o;f.waiting=h;i[b]=f;delete k[b];for(g=0;g<h;g++)e=c[g],(d=i[e])?e=d.waiting:(d=k[e]=k[e]||{},e=!0),e?(d=d.refs=d.refs||[],d.push(b)):f.waiting--;f.waiting||a(f)}function a(b){var g=b.refs,d=b.name,f;b.flag&l&&(c(d),delete i[d]);if(g)for(d=0,f=g.length;d<f;d++)(b=i[g[d]])&&b.waiting&&(--b.waiting||a(b))}function c(a){var b,g,d,f,h,e,k;b=i[a];if(!b)throw Error('Requiring unknown module "'+a+'"');
if(b.error)throw Error('Requiring module "'+a+'" which threw an exception');if(b.waiting)throw Error('Requiring module "'+a+'" with unresolved dependencies');if(b.hasOwnProperty("exports"))return b.exports;b.exports=g={};a=b.deps;e=a.length;h=-1;for(f=[];++h<e;)d=a[h],f.push("module"===d?b:"exports"===d?g:c(d));p&&!p.inGuard()?p.applyWithGuard(function(){k=b.factory.apply(this,f);void 0!==k&&k!==g&&(b.exports=k)},this,f):(k=b.factory.apply(this,f),void 0!==k&&k!==g&&(b.exports=k));return b.exports}
function d(a,b){function g(){--h||d()}function d(){var g=[],h;for(h=0;h<f;h++)g.push(c(a[h]));b&&b.apply(this,g)}var f,h,i,k;if(h=f=a.length)for(i=0;i<f;i++)k=a[i],e.loadModule(k,g);else d()}function b(a,b){s?(j("__mod_"+r++,a,b,l),d(a)):n.push([a,b])}function f(){if(!s){s=!0;b.onready&&b.onready();var a,c,g,f;for(a=0,c=n.length;a<c;a++)g=n[a],f=g[0],g=g[1],j("__mod_"+r++,f,g,l),d(f);n=null}}function g(a,b){i[a]={exports:b,waiting:0}}function h(){e.log.apply(e,arguments)}var i={},k={},n=[],o=0,l=
1,p=e.ErrorUtils,r=0,q,s=!1;document.addEventListener?q=function(){document.removeEventListener("DOMContentLoaded",q,!1);f()}:document.attachEvent&&(q=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",q),f())});c.__debug__=i;c.__waiting__=k;document.addEventListener?(document.addEventListener("DOMContentLoaded",q,!1),window.addEventListener("load",f,!1)):document.attachEvent&&(document.attachEvent("onreadystatechange",q),window.attachEvent("onload",f));g("global",
m);g("module",1);g("exports",1);g("require",c);g("requireAsync",d);g("requireLazy",b);m.define=j;m.require=c;m.requireAsync=d;m.requireLazy=b;m.__d=function(a,b,c){return j(a,"global,module,exports,require,requireAsync,requireLazy".split(",").concat(b),c)};m.console||(m.console={log:h,error:h,dir:h})})(window,BigPipe);
__d("common.js.parseUrl",[],function(m,e,j){function a(a,b){for(var c=decodeURI(a),c=i[b?"strict":"loose"].exec(c),f={attr:{},param:{},seg:{}},h=14;h--;)f.attr[g[h]]=c[h]||"";f.param.query=d(f.attr.query);f.param.fragment=d(f.attr.fragment);f.seg.path=f.attr.path.replace(/^\/+|\/+$/g,"").split("/");f.seg.fragment=f.attr.fragment.replace(/^\/+|\/+$/g,"").split("/");f.attr.base=f.attr.host?(f.attr.protocol?f.attr.protocol+"://"+f.attr.host:f.attr.host)+(f.attr.port?":"+f.attr.port:""):"";return f}function c(a,
b,g,d){var h=a.shift();if(h){var e=b[g]=b[g]||[];if("]"==h)if(f(e))""!==d&&e.push(d);else if("object"==typeof e){var b=a=e,g=[],i;for(i in b)b.hasOwnProperty(i)&&g.push(i);a[g.length]=d}else b[g]=[b[g],d];else{~h.indexOf("]")&&(h=h.substr(0,h.length-1));if(!k.test(h)&&f(e))if(0===b[g].length)e=b[g]={};else{i={};for(var j in b[g])i[j]=b[g][j];e=b[g]=i}c(a,e,h,d)}}else f(b[g])?b[g].push(d):b[g]="object"==typeof b[g]?d:"undefined"==typeof b[g]?d:[b[g],d]}function d(a){return b((""+a).split(/&|;/),function(a,
b){try{b=decodeURIComponent(b.replace(/\+/g," "))}catch(g){}var d=b.indexOf("="),h;a:{for(var e=b.length,i,n=0;n<e;++n)if(i=b[n],"]"==i&&(h=!1),"["==i&&(h=!0),"="==i&&!h){h=n;break a}h=void 0}e=b.substr(0,h||d);h=b.substr(h||d,b.length);h=h.substr(h.indexOf("=")+1,h.length);""===e&&(e=b,h="");d=e;e=h;if(~d.indexOf("]")){var j=d.split("[");c(j,a,"base",e)}else{if(!k.test(d)&&f(a.base)){h={};for(j in a.base)h[j]=a.base[j];a.base=h}""!==d&&(j=a.base,h=j[d],"undefined"===typeof h?j[d]=e:f(h)?h.push(e):
j[d]=[h,e])}return a},{base:{}}).base}function b(a,b,c){for(var g=0,d=a.length>>0;g<d;)g in a&&(c=b.call(void 0,c,a[g],g,a)),++g;return c}function f(a){return"[object Array]"===Object.prototype.toString.call(a)}var g="source,protocol,authority,userInfo,user,password,host,port,relative,path,directory,file,query,fragment".split(","),h={anchor:"fragment"},i={strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*):?([^:@]*))?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*):?([^:@]*))?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/},
k=/^[0-9]+$/;e.exports=function(b,c){1===arguments.length&&!0===b&&(c=!0,b=void 0);b=b||window.location.toString();return{data:a(b,c||!1),attr:function(a){a=h[a]||a;return"undefined"!==typeof a?this.data.attr[a]:this.data.attr},param:function(a){return"undefined"!==typeof a?this.data.param.query[a]:this.data.param.query},fparam:function(a){return"undefined"!==typeof a?this.data.param.fragment[a]:this.data.param.fragment},segment:function(a){if("undefined"===typeof a)return this.data.seg.path;a=0>
a?this.data.seg.path.length+a:a-1;return this.data.seg.path[a]},fsegment:function(a){if("undefined"===typeof a)return this.data.seg.fragment;a=0>a?this.data.seg.fragment.length+a:a-1;return this.data.seg.fragment[a]}}};return j});
__d("common.js.jquery_slides",[],function(m,e,j){(function(){(function(a,c,d){var b,f;f={width:940,height:528,start:1,navigation:{active:!0,effect:"slide"},pagination:{active:!0,effect:"slide"},play:{active:!1,effect:"slide",interval:5E3,auto:!1,swap:!0,pauseOnHover:!1,restartDelay:2500},effect:{slide:{speed:500},fade:{speed:300,crossfade:!0}},callback:{loaded:function(){},start:function(){},complete:function(){}}};b=function(){return function(b,c){this.element=b;this.options=a.extend(!0,{},f,c);
this._defaults=f;this._name="slidesjs";this.init()}}();b.prototype.init=function(){var b,d,f,e,n=this;b=a(this.element);this.data=a.data(this);a.data(this,"animating",!1);a.data(this,"total",b.children().not(".slidesjs-navigation",b).length);a.data(this,"current",this.options.start-1);a.data(this,"vendorPrefix",this._getVendorPrefix());"undefined"!==typeof TouchEvent&&(a.data(this,"touch",!0),this.options.effect.slide.speed/=2);b.css({overflow:"hidden"});b.slidesContainer=b.children().not(".slidesjs-navigation",
b).wrapAll("<div class='slidesjs-container'>",b).parent().css({overflow:"hidden",position:"relative"});a(".slidesjs-container",b).wrapInner("<div class='slidesjs-control'>",b).children();a(".slidesjs-control",b).css({position:"relative",left:0});a(".slidesjs-control",b).children().addClass("slidesjs-slide").css({position:"absolute",top:0,left:0,width:"100%",zIndex:0,display:"none",webkitBackfaceVisibility:"hidden"});a.each(a(".slidesjs-control",b).children(),function(b){return a(this).attr("slidesjs-index",
b)});this.data.touch&&(a(".slidesjs-control",b).on("touchstart",function(a){return n._touchstart(a)}),a(".slidesjs-control",b).on("touchmove",function(a){return n._touchmove(a)}),a(".slidesjs-control",b).on("touchend",function(a){return n._touchend(a)}));b.fadeIn(0);this.update();this.data.touch&&this._setuptouch();a(".slidesjs-control",b).children(":eq("+this.data.current+")").eq(0).fadeIn(0,function(){return a(this).css({zIndex:10})});this.options.navigation.active&&(d=this.options.navigation.nextButton?
a(this.options.navigation.nextButton):a("<a>",{"class":"slidesjs-next slidesjs-navigation",href:"#",title:"\u4e0b\u4e00\u4e2a",text:"\u4e0b\u4e00\u4e2a"}).appendTo(b),e=this.options.navigation.prevButton?a(this.options.navigation.prevButton):a("<a>",{"class":"slidesjs-previous slidesjs-navigation",href:"#",title:"\u4e0a\u4e00\u4e2a",text:"\u4e0a\u4e00\u4e2a"}).appendTo(b));d.click(function(a){a.preventDefault();n.stop(!0);return n.next(n.options.navigation.effect)});e.click(function(a){a.preventDefault();
n.stop(!0);return n.previous(n.options.navigation.effect)});this.options.play.active&&(d=a("<a>",{"class":"slidesjs-play slidesjs-navigation",href:"#",title:"Play",text:"Play"}).appendTo(b),e=a("<a>",{"class":"slidesjs-stop slidesjs-navigation",href:"#",title:"Stop",text:"Stop"}).appendTo(b),d.click(function(a){a.preventDefault();return n.play(!0)}),e.click(function(a){a.preventDefault();return n.stop(!0)}),this.options.play.swap&&e.css({display:"none"}));this.options.pagination.active&&(f=a("<ul>",
{"class":"slidesjs-pagination"}).appendTo(b),a.each(Array(this.data.total),function(b){var c;c=a("<li>",{"class":"slidesjs-pagination-item"}).appendTo(f);return a("<a>",{href:"#","data-slidesjs-item":b,html:b+1}).appendTo(c).click(function(b){b.preventDefault();n.stop(!0);return n.go2(1*a(b.currentTarget).attr("data-slidesjs-item")+1)})}));a(c).bind("resize",function(){});this._setActive();this.options.play.auto&&this.play();return this.options.callback.loaded(this.options.start)};b.prototype._setActive=
function(b){var c;c=a(this.element);this.data=a.data(this);b=-1<b?b:this.data.current;a(".active",c).removeClass("active");return a(".slidesjs-pagination li:eq("+b+") a",c).addClass("active")};b.prototype.update=function(){var b,c,d;b=a(this.element);this.data=a.data(this);a(".slidesjs-control",b).children(":not(:eq("+this.data.current+"))").css({display:"none",left:0,zIndex:0});d=b.width();c=this.options.height/this.options.width*d;this.options.width=d;this.options.height=c;return a(".slidesjs-control, .slidesjs-container",
b).css({width:d,height:c})};b.prototype.next=function(b){a(this.element);this.data=a.data(this);a.data(this,"direction","next");void 0===b&&(b=this.options.navigation.effect);return"fade"===b?this._fade():this._slide()};b.prototype.previous=function(b){a(this.element);this.data=a.data(this);a.data(this,"direction","previous");void 0===b&&(b=this.options.navigation.effect);return"fade"===b?this._fade():this._slide()};b.prototype.go2=function(b){var c;a(this.element);this.data=a.data(this);void 0===
c&&(c=this.options.pagination.effect);b>this.data.total?b=this.data.total:1>b&&(b=1);if("number"===typeof b)return"fade"===c?this._fade(b):this._slide(b);if("string"===typeof b){if("first"===b)return"fade"===c?this._fade(0):this._slide(0);if("last"===b)return"fade"===c?this._fade(this.data.total):this._slide(this.data.total)}};b.prototype._setuptouch=function(){var b,c,d;b=a(this.element);this.data=a.data(this);d=a(".slidesjs-control",b);b=this.data.current+1;c=this.data.current-1;0>c&&(c=this.data.total-
1);b>this.data.total-1&&(b=0);d.children(":eq("+b+")").css({display:"block",left:this.options.width});return d.children(":eq("+c+")").css({display:"block",left:-this.options.width})};b.prototype._touchstart=function(b){var c;a(this.element);this.data=a.data(this);c=b.originalEvent.touches[0];this._setuptouch();a.data(this,"touchtimer",Number(new Date));a.data(this,"touchstartx",c.pageX);a.data(this,"touchstarty",c.pageY);return b.stopPropagation()};b.prototype._touchend=function(b){var c,d,f,e,j,
l,m=this;c=a(this.element);this.data=a.data(this);e=a(".slidesjs-control",c);e.position().left>0.5*this.options.width||e.position().left>0.1*this.options.width&&250>Number(new Date)-this.data.touchtimer?(a.data(this,"direction","previous"),this._slide()):e.position().left<-(0.5*this.options.width)||e.position().left<-(0.1*this.options.width)&&250>Number(new Date)-this.data.touchtimer?(a.data(this,"direction","next"),this._slide()):(f=this.data.vendorPrefix,l=f+"Transform",d=f+"TransitionDuration",
j=f+"TransitionTimingFunction",e[0].style[l]="translateX(0px)",e[0].style[d]=0.85*this.options.effect.slide.speed+"ms");e.on("transitionend webkitTransitionEnd oTransitionEnd otransitionend MSTransitionEnd",function(){f=m.data.vendorPrefix;l=f+"Transform";d=f+"TransitionDuration";j=f+"TransitionTimingFunction";e[0].style[l]="";e[0].style[d]="";return e[0].style[j]=""});return b.stopPropagation()};b.prototype._touchmove=function(b){var c,d,f;c=a(this.element);this.data=a.data(this);f=b.originalEvent.touches[0];
d=this.data.vendorPrefix;c=a(".slidesjs-control",c);d+="Transform";a.data(this,"scrolling",Math.abs(f.pageX-this.data.touchstartx)<Math.abs(f.pageY-this.data.touchstarty));!this.data.animating&&!this.data.scrolling&&(b.preventDefault(),this._setuptouch(),c[0].style[d]="translateX("+(f.pageX-this.data.touchstartx)+"px)");return b.stopPropagation()};b.prototype.play=function(b){var c,d=this;c=a(this.element);this.data=a.data(this);if(!this.data.playInterval&&(b&&(this.data.direction="next","fade"===
this.options.play.effect?this._fade():this._slide()),clearInterval(this.data.playInterval),a.data(this,"playInterval",setInterval(function(){d.data.direction="next";return"fade"===d.options.play.effect?d._fade():d._slide()},this.options.play.interval)),b=a(".slidesjs-container",c),this.options.play.pauseOnHover&&(b.unbind(),b.bind("mouseenter",function(){return d.stop()}),b.bind("mouseleave",function(){return d.options.play.restartDelay?a.data(d,"restartDelay",setTimeout(function(){return d.play(!0)},
d.options.play.restartDelay)):d.play()})),a.data(this,"playing",!0),a(".slidesjs-play",c).addClass("slidesjs-playing"),this.options.play.swap))return a(".slidesjs-play",c).hide(),a(".slidesjs-stop",c).show()};b.prototype.stop=function(b){var c;c=a(this.element);this.data=a.data(this);this.options.play.pauseOnHover&&b&&a(".slidesjs-container",c).unbind();clearInterval(this.data.playInterval);clearTimeout(this.data.restartDelay);a.data(this,"playInterval",null);a.data(this,"playing",!1);a(".slidesjs-play",
c).removeClass("slidesjs-playing");if(this.options.play.swap)return a(".slidesjs-stop",c).hide(),a(".slidesjs-play",c).show()};b.prototype._slide=function(b){var c,d,f,e,j,l,m,r,q=this;c=a(this.element);this.data=a.data(this);if(!this.data.animating&&b!==this.data.current+1){a.data(this,"animating",!0);d=this.data.current;-1<b?(b-=1,r=b>d?1:-1,f=b>d?-this.options.width:this.options.width,j=b):(r="next"===this.data.direction?1:-1,f="next"===this.data.direction?-this.options.width:this.options.width,
j=d+r);-1===j&&(j=this.data.total-1);j===this.data.total&&(j=0);this._setActive(j);l=a(".slidesjs-control",c);-1<b&&l.children(":not(:eq("+d+"))").css({display:"none",left:0,zIndex:0});l.children(":eq("+j+")").css({display:"block",left:r*this.options.width,zIndex:10});this.options.callback.start(d+1);return this.data.vendorPrefix?(b=this.data.vendorPrefix,m=b+"Transform",e=b+"TransitionDuration",l[0].style[m]="translateX("+f+"px)",l[0].style[e]=this.options.effect.slide.speed+"ms",l.on("transitionend webkitTransitionEnd oTransitionEnd otransitionend MSTransitionEnd",
function(){l[0].style[m]="";l[0].style[e]="";l.children(":eq("+j+")").css({left:0});l.children(":eq("+d+")").css({display:"none",left:0,zIndex:0});a.data(q,"current",j);a.data(q,"animating",!1);l.unbind("transitionend webkitTransitionEnd oTransitionEnd otransitionend MSTransitionEnd");l.children(":not(:eq("+j+"))").css({display:"none",left:0,zIndex:0});q.data.touch&&q._setuptouch();return q.options.callback.complete(j+1)})):l.stop().animate({left:f},this.options.effect.slide.speed,function(){l.css({left:0});
l.children(":eq("+j+")").css({left:0});return l.children(":eq("+d+")").css({display:"none",left:0,zIndex:0},a.data(q,"current",j),a.data(q,"animating",!1),q.options.callback.complete(j+1))})}};b.prototype._fade=function(b){var c,d,f,e,j,l=this;c=a(this.element);this.data=a.data(this);if(!this.data.animating&&b!==this.data.current+1){a.data(this,"animating",!0);d=this.data.current;b?(b-=1,j=b>d?1:-1,f=b):(j="next"===this.data.direction?1:-1,f=d+j);-1===f&&(f=this.data.total-1);f===this.data.total&&
(f=0);this._setActive(f);e=a(".slidesjs-control",c);e.children(":eq("+f+")").css({display:"none",left:0,zIndex:10});this.options.callback.start(d+1);return this.options.effect.fade.crossfade?(e.children(":eq("+this.data.current+")").stop().fadeOut(this.options.effect.fade.speed),e.children(":eq("+f+")").stop().fadeIn(this.options.effect.fade.speed,function(){e.children(":eq("+f+")").css({zIndex:0});a.data(l,"animating",!1);a.data(l,"current",f);return l.options.callback.complete(f+1)})):e.children(":eq("+
d+")").stop().fadeOut(this.options.effect.fade.speed,function(){e.children(":eq("+f+")").stop().fadeIn(l.options.effect.fade.speed,function(){return e.children(":eq("+f+")").css({zIndex:10})});a.data(l,"animating",!1);a.data(l,"current",f);return l.options.callback.complete(f+1)})}};b.prototype._getVendorPrefix=function(){var a,b,c,f;b=(d.body||d.documentElement).style;c="transition";f=["Moz","Webkit","Khtml","O","ms"];c=c.charAt(0).toUpperCase()+c.substr(1);for(a=0;a<f.length;){if("string"===typeof b[f[a]+
c])return f[a];a++}return!1};return a.fn.slidesjs=function(c){return this.each(function(){if(!a.data(this,"plugin_slidesjs"))return a.data(this,"plugin_slidesjs",new b(this,c))})}})(jQuery,window,document)}).call(this);return j});
__d("common.js.simplePagination",[],function(m,e,j){(function(a){var c={init:function(d){var b=a.extend({items:1,itemsOnPage:1,pages:0,displayedPages:5,edges:2,currentPage:1,hrefTextPrefix:"#page-",hrefTextSuffix:"",prevText:"Prev",nextText:"Next",ellipseText:"&hellip;",cssStyle:"light-theme",selectOnClick:!0,onPageClick:function(){},onInit:function(){}},d||{}),f=this;b.pages=b.pages?b.pages:Math.ceil(b.items/b.itemsOnPage)?Math.ceil(b.items/b.itemsOnPage):1;b.currentPage-=1;b.halfDisplayed=b.displayedPages/
2;this.each(function(){f.addClass(b.cssStyle+" simple-pagination").data("pagination",b);c._draw.call(f)});b.onInit();return this},selectPage:function(a){c._selectPage.call(this,a-1);return this},prevPage:function(){var a=this.data("pagination");0<a.currentPage&&c._selectPage.call(this,a.currentPage-1);return this},nextPage:function(){var a=this.data("pagination");a.currentPage<a.pages-1&&c._selectPage.call(this,a.currentPage+1);return this},getPagesCount:function(){return this.data("pagination").pages},
getCurrentPage:function(){return this.data("pagination").currentPage+1},destroy:function(){this.empty();return this},redraw:function(){c._draw.call(this);return this},disable:function(){var a=this.data("pagination");a.disabled=!0;this.data("pagination",a);c._draw.call(this);return this},enable:function(){var a=this.data("pagination");a.disabled=!1;this.data("pagination",a);c._draw.call(this);return this},_draw:function(){var d=this.data("pagination"),b=c._getInterval(d),f;c.destroy.call(this);var g=
"UL"===this.prop("tagName")?this:a("<ul></ul>").appendTo(this);d.prevText&&c._appendItem.call(this,d.currentPage-1,{text:d.prevText,classes:"prev"});if(0<b.start&&0<d.edges){var h=Math.min(d.edges,b.start);for(f=0;f<h;f++)c._appendItem.call(this,f);d.edges<b.start&&1!=b.start-d.edges?g.append('<li class="disabled"><span class="ellipse">'+d.ellipseText+"</span></li>"):1==b.start-d.edges&&c._appendItem.call(this,d.edges)}for(f=b.start;f<b.end;f++)c._appendItem.call(this,f);if(b.end<d.pages&&0<d.edges){d.pages-
d.edges>b.end&&1!=d.pages-d.edges-b.end?g.append('<li class="disabled"><span class="ellipse">'+d.ellipseText+"</span></li>"):1==d.pages-d.edges-b.end&&c._appendItem.call(this,b.end++);for(f=Math.max(d.pages-d.edges,b.end);f<d.pages;f++)c._appendItem.call(this,f)}d.nextText&&c._appendItem.call(this,d.currentPage+1,{text:d.nextText,classes:"next"})},_getInterval:function(a){return{start:Math.ceil(a.currentPage>a.halfDisplayed?Math.max(Math.min(a.currentPage-a.halfDisplayed,a.pages-a.displayedPages),
0):0),end:Math.ceil(a.currentPage>a.halfDisplayed?Math.min(a.currentPage+a.halfDisplayed,a.pages):Math.min(a.displayedPages,a.pages))}},_appendItem:function(d,b){var f=this,g,h;h=f.data("pagination");var e=a("<li></li>"),k=f.find("ul"),d=0>d?0:d<h.pages?d:h.pages-1;g=a.extend({text:d+1,classes:""},b||{});d==h.currentPage||h.disabled?(h.disabled?e.addClass("disabled"):e.addClass("active"),h=a('<span class="current">'+g.text+"</span>")):(h=a('<a href="'+h.hrefTextPrefix+(d+1)+h.hrefTextSuffix+'" class="page-link">'+
g.text+"</a>"),h.click(function(a){return c._selectPage.call(f,d,a)}));g.classes&&h.addClass(g.classes);e.append(h);k.length?k.append(e):f.append(e)},_selectPage:function(a,b){var f=this.data("pagination");f.currentPage=a;f.selectOnClick&&c._draw.call(this);return f.onPageClick(a+1,b)}};a.fn.pagination=function(d){if(c[d]&&"_"!=d.charAt(0))return c[d].apply(this,Array.prototype.slice.call(arguments,1));if("object"===typeof d||!d)return c.init.apply(this,arguments);a.error("Method "+d+" does not exist on jQuery.pagination")}})(jQuery);
return j});__d("common.js.animationFrame",[],function(m,e,j){return j=function(){return m.requestAnimationFrame||m.webkitRequestAnimationFrame||m.mozRequestAnimationFrame||m.oRequestAnimationFrame||m.msRequestAnimationFrame||function(a){m.setTimeout(a,30)}}()});
__d("widget.playerCore.tangram",[],function(){var m,e=m=e||{version:"1.5.0"};e.guid="$BAIDU$";window[e.guid]=window[e.guid]||{};e.fn=e.fn||{};e.fn.blank=function(){};e.string=e.string||{};e.string.format=function(a,c){var a=""+a,d=Array.prototype.slice.call(arguments,1),b=Object.prototype.toString;return d.length?(d=1==d.length?null!==c&&/\[object Array\]|\[object Object\]/.test(b.call(c))?c:d:d,a.replace(/#\{(.+?)\}/g,function(a,c){var e=d[c];"[object Function]"==b.call(e)&&(e=e(c));return"undefined"==
typeof e?"":e})):a};e.format=e.string.format;e.object=e.object||{};e.object.each=function(a,c){var d,b;if("function"==typeof c)for(b in a)if(a.hasOwnProperty(b)&&(d=a[b],d=c.call(a,d,b),!1===d))break;return a};e.extend=e.object.extend=function(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d]);return a};e.number=e.number||{};e.number.pad=function(a,c){var d="",b=0>a,f=""+Math.abs(a);f.length<c&&(d=Array(c-f.length+1).join("0"));return(b?"-":"")+d+f};e.platform=e.platform||{};e.platform.isAndroid=
/android/i.test(navigator.userAgent);e.platform.isIpad=/ipad/i.test(navigator.userAgent);e.platform.isIphone=/iphone/i.test(navigator.userAgent);e.swf=e.swf||{};e.browser=e.browser||{};e.browser.ie=e.ie=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:void 0;e.array=e.array||{};e.array.remove=function(a,c){for(var d=a.length;d--;)d in a&&a[d]===c&&a.splice(d,1);return a};e.lang=e.lang||{};e.lang.isArray=function(a){return"[object Array]"==Object.prototype.toString.call(a)};
e.lang.isFunction=function(a){return"[object Function]"==Object.prototype.toString.call(a)};e.lang.toArray=function(a){if(null===a||void 0===a)return[];if(e.lang.isArray(a))return a;if("number"!==typeof a.length||"string"===typeof a||e.lang.isFunction(a))return[a];if(a.item){for(var c=a.length,d=Array(c);c--;)d[c]=a[c];return d}return[].slice.call(a)};e.swf.getMovie=function(a){var c=document[a],d;return 9==e.browser.ie?c&&c.length?1==(d=e.array.remove(e.lang.toArray(c),function(a){return"embed"!=
a.tagName.toLowerCase()})).length?d[0]:d:c:c||window[a]};e.swf.version=function(){var a=navigator;if(a.plugins&&a.mimeTypes.length){var c=a.plugins["Shockwave Flash"];if(c&&c.description)return c.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")+".0"}else if(window.ActiveXObject&&!window.opera)for(a=12;2<=a;a--)try{if(c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+a))return c.GetVariable("$version").replace(/WIN/g,"").replace(/,/g,".")}catch(d){}}();e.string.encodeHTML=function(a){return(""+
a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")};e.encodeHTML=e.string.encodeHTML;e.swf.createHTML=function(a){var a=a||{},c=e.swf.version,d=a.ver||"6.0.0",b,f,g,h;g={};var i=e.string.encodeHTML;for(h in a)g[h]=a[h];a=g;if(c){c=c.split(".");d=d.split(".");for(g=0;3>g&&!(b=parseInt(c[g],10),f=parseInt(d[g],10),f<b);g++)if(f>b)return""}else return"";g=a.vars;d="classid,codebase,id,width,height,align".split(",");a.align=a.align||"middle";
a.classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000";a.codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0";a.movie=a.url||"";delete a.vars;delete a.url;if("string"==typeof g)a.flashvars=g;else{b=[];for(h in g)c=g[h],b.push(h+"="+encodeURIComponent(c));a.flashvars=b.join("&")}b=["<object "];for(g=0,f=d.length;g<f;g++)c=d[g],b.push(" ",c,'="',i(a[c]),'"');b.push(">");g={wmode:1,scale:1,quality:1,play:1,loop:1,menu:1,salign:1,bgcolor:1,base:1,allowscriptaccess:1,
allownetworking:1,allowfullscreen:1,seamlesstabbing:1,devicefont:1,swliveconnect:1,flashvars:1,movie:1};for(h in a)c=a[h],h=h.toLowerCase(),g[h]&&(c||!1===c||0===c)&&b.push('<param name="'+h+'" value="'+i(c)+'" />');a.src=a.movie;a.name=a.id;delete a.id;delete a.movie;delete a.classid;delete a.codebase;a.type="application/x-shockwave-flash";a.pluginspage="http://www.macromedia.com/go/getflashplayer";b.push("<embed");var k;for(h in a)if((c=a[h])||!1===c||0===c)/^salign$/i.test(h)?k=c:b.push(" ",h,
'="',i(c),'"');k&&b.push(' salign="',i(k),'"');b.push("></embed></object>");return b.join("")};e.swf.create=function(a,c){var a=a||{},d=e.swf.createHTML(a)||a.errorMessage||"";c&&"string"==typeof c&&(c=document.getElementById(c));c?c.innerHTML=d:document.write(d)};(function(){var a=window[e.guid];e.lang.guid=function(){return"TANGRAM__"+(a._counter++).toString(36)};a._counter=a._counter||1})();window[e.guid]._instances=window[e.guid]._instances||{};e.lang.Class=function(a){this.guid=a||e.lang.guid();
window[e.guid]._instances[this.guid]=this};window[e.guid]._instances=window[e.guid]._instances||{};e.lang.Class.prototype.dispose=function(){delete window[e.guid]._instances[this.guid];for(var a in this)e.lang.isFunction(this[a])||delete this[a];this.disposed=!0};e.lang.Class.prototype.toString=function(){return"[object "+(this._className||"Object")+"]"};e.lang.isString=function(a){return"[object String]"==Object.prototype.toString.call(a)};e.isString=e.lang.isString;e.lang.Event=function(a,c){this.type=
a;this.returnValue=!0;this.target=c||null;this.currentTarget=null};e.lang.Class.prototype.addEventListener=function(a,c,d){if(e.lang.isFunction(c)){!this.__listeners&&(this.__listeners={});var b=this.__listeners,f;if("string"==typeof d&&d){if(/[^\w\-]/.test(d))throw"nonstandard key:"+d;f=c.hashCode=d}0!=a.indexOf("on")&&(a="on"+a);"object"!=typeof b[a]&&(b[a]={});f=f||e.lang.guid();c.hashCode=f;b[a][f]=c}};e.lang.Class.prototype.removeEventListener=function(a,c){if(!("undefined"!=typeof c&&(e.lang.isFunction(c)&&
!(c=c.hashCode)||!e.lang.isString(c)))){!this.__listeners&&(this.__listeners={});0!=a.indexOf("on")&&(a="on"+a);var d=this.__listeners;if(d[a])if("undefined"!=typeof c)d[a][c]&&delete d[a][c];else for(var b in d[a])delete d[a][b]}};e.lang.Class.prototype.dispatchEvent=function(a,c){e.lang.isString(a)&&(a=new e.lang.Event(a));!this.__listeners&&(this.__listeners={});var c=c||{},d;for(d in c)a[d]=c[d];var b=this.__listeners,f=a.type;a.target=a.target||this;a.currentTarget=this;0!=f.indexOf("on")&&(f=
"on"+f);e.lang.isFunction(this[f])&&this[f].apply(this,arguments);if("object"==typeof b[f])for(d in b[f])b[f][d].apply(this,arguments);return a.returnValue};e.lang.createClass=function(a,c){var c=c||{},d=c.superClass||e.lang.Class,b=function(){d!=e.lang.Class?d.apply(this,arguments):d.call(this);a.apply(this,arguments)};b.options=c.options||{};var f=function(){},g=a.prototype;f.prototype=d.prototype;var f=b.prototype=new f,h;for(h in g)f[h]=g[h];"string"==typeof c.className&&(f._className=c.className);
f.constructor=g.constructor;b.extend=function(a){for(var c in a)b.prototype[c]=a[c];return b};return b};e.lang.inherits=function(a,c,d){var b,f,g=a.prototype;f=new Function;f.prototype=c.prototype;f=a.prototype=new f;for(b in g)f[b]=g[b];a.prototype.constructor=a;a.superClass=c.prototype;"string"==typeof d&&(f._className=d)};e.inherits=e.lang.inherits;e.lang.isBoolean=function(a){return"boolean"===typeof a};e.lang.isElement=function(a){return!(!a||!(a.nodeName&&1==a.nodeType))};e.lang.isNumber=function(a){return"[object Number]"==
Object.prototype.toString.call(a)&&isFinite(a)};e.lang.isObject=function(a){return"function"==typeof a||!!(a&&"object"==typeof a)};e.isObject=e.lang.isObject;e.fn.bind=function(a,c){var d=2<arguments.length?[].slice.call(arguments,2):null;return function(){var b=e.lang.isString(a)?c[a]:a,f=d?d.concat([].slice.call(arguments,0)):arguments;return b.apply(c||b,f)}};e.each=e.array.forEach=e.array.each=function(a,c,d){var b,f,g=a.length;if("function"==typeof c)for(f=0;f<g&&!(b=a[f],b=c.call(d||a,b,f),
!1===b);f++);return a};e.array.some=function(a,c,d){for(var b=0,f=a.length;b<f;b++)if(b in a&&c.call(d||a,a[b],b))return!0;return!1};e.browser.chrome=/chrome\/(\d+\.\d+)/i.test(navigator.userAgent)?+RegExp.$1:void 0;e.browser.firefox=/firefox\/(\d+\.\d+)/i.test(navigator.userAgent)?+RegExp.$1:void 0;e.browser.isWebkit=/webkit/i.test(navigator.userAgent);try{/(\d+\.\d+)/.test(external.max_version)&&(e.browser.maxthon=+RegExp.$1)}catch(j){}(function(){var a=navigator.userAgent;e.browser.safari=/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(a)&&
!/chrome/i.test(a)?+(RegExp.$1||RegExp.$2):void 0})();e.dom=e.dom||{};e.dom.g=function(a){return"string"==typeof a||a instanceof String?document.getElementById(a):a&&a.nodeName&&(1==a.nodeType||9==a.nodeType)?a:null};e.g=e.G=e.dom.g;e.dom._styleFixer=e.dom._styleFixer||{};e.dom._styleFilter=e.dom._styleFilter||[];e.dom._styleFilter.filter=function(a,c,d){for(var b=0,f=e.dom._styleFilter,g;g=f[b];b++)if(g=g[d])c=g(a,c);return c};e.string.toCamelCase=function(a){return 0>a.indexOf("-")&&0>a.indexOf("_")?
a:a.replace(/[-_][^-_]/g,function(a){return a.charAt(1).toUpperCase()})};e.dom.setStyle=function(a,c,d){var b=e.dom,f,a=b.g(a),c=e.string.toCamelCase(c);if(f=b._styleFilter)d=f.filter(c,d,"set");(f=b._styleFixer[c])&&f.set?f.set(a,d):a.style[f||c]=d;return a};e.setStyle=e.dom.setStyle;e.dom.setStyles=function(a,c){var a=e.dom.g(a),d;for(d in c)e.dom.setStyle(a,d,c[d]);return a};e.setStyles=e.dom.setStyles;e.dom._NAME_ATTRS=function(){var a={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",
rowspan:"rowSpan",valign:"vAlign",usemap:"useMap",frameborder:"frameBorder"};8>e.browser.ie?(a["for"]="htmlFor",a["class"]="className"):(a.htmlFor="for",a.className="class");return a}();e.dom.setAttr=function(a,c,d){a=e.dom.g(a);"style"==c?a.style.cssText=d:(c=e.dom._NAME_ATTRS[c]||c,a.setAttribute(c,d));return a};e.setAttr=e.dom.setAttr;e.dom.setAttrs=function(a,c){var a=e.dom.g(a),d;for(d in c)e.dom.setAttr(a,d,c[d]);return a};e.setAttrs=e.dom.setAttrs;e.dom.create=function(a,c){var d=document.createElement(a);
return e.dom.setAttrs(d,c||{})};return m});
__d("widget.playerCore.player",["widget.playerCore.tangram"],function(m,e,j,a){var c=a("widget.playerCore.tangram"),d=d||{};c.extend(d,{namespace:function(){var a=arguments,c=null,g,e,i,k;for(g=0,k=a.length;g<k;g++){i=(""+a[g]).split(".");c=d;for(e="mbox"==i[0]?1:0;e<i.length;e+=1)c[i[e]]=c[i[e]]||{},c=c[i[e]]}return c},Fuze:function(){var a,c,d;a=[];c=function(c){d?c():a.push(c)};c.fire=function(){for(;a.length;)a.shift()();d=!0};c.extinguish=function(){d=!1};c.wettish=function(){this.fire();this.extinguish()};
c.clear=function(){for(;a.length;)a.shift();this.extinguish()};return c},convertTime:function(a){var d,a=Math.round(a/1E3);d=Math.floor(a/60);a%=60;return c.number.pad(d,2)+":"+c.number.pad(a,2)},Timer:function(a){var c=function(a,b){this._timer=function(){};this._listener=function(){};this._timerComplete=function(){};this._timerID=null;this._delay=this._remain=a;this._repeatCount=b||0;this._currentCount=0;this._isRunning=!1;this._startTime=this._endTime=0;this.EVENTS={TIMER:"timer",COMPLETE:"timerComplete"}};
c.prototype={_createTimer:function(c,d){var f=this;return 1==d?function(){return a.setTimeout(function(){f.reset();f._listener(f._delay,d);f._timerComplete()},c)}:function(){return a.setInterval(function(){0!=d&&f._currentCount>=d?(f.reset(),f._timerComplete()):(f._currentCount++,f._listener(c,f._currentCount))},c)}},addEventListener:function(a,b){"timer"==a?(this._listener=b,this._timer=this._createTimer(this._delay,this._repeatCount)):"timerComplete"==a&&(this._timerComplete=b)},reset:function(){this.stop();
1==this._repeatCount&&(this._timer=this._createTimer(this._delay,this._repeatCount));this._currentCount=0;this._remain=this._delay;this._startTime=this._endTime=0},start:function(){this._timerID||(this._timerID=this._timer(),1==this._repeatCount&&(this._startTime=(new Date).getTime()),this._isRunning=!0)},stop:function(){this._timerID&&(1==this._repeatCount?a.clearTimeout(this._timerID):a.clearInterval(this._timerID),this._timerID=null,this._isRunning=!1)},pause:function(){1==this._repeatCount?this._timerID&&
(this.stop(),this._endTime=(new Date).getTime(),this._remain-=this._endTime-this._startTime,0<this._remain?this._timer=this._createTimer(this._remain,1):this.reset()):this.stop()},getCurrentCount:function(){return this._currentCount},isRunning:function(){return this._isRunning}};return c}(window),StopWatch:function(){var a=0,c=function(){this.startTime=0;this.isRunning=!1;this.isReset=!0;this.passedTime=0;a++};c.prototype={reset:function(){this.passedTime=this.pauseTime=this.startTime=0;this.isRunning=
!1;this.isReset=!0},start:function(){this.isReset?(this.reset(),this.startTime=(new Date).getTime()):this.isRunning||(this.startTime=(new Date).getTime());this.isRunning=!0;this.isReset=!1},pause:function(){!this.isReset&&this.isRunning&&(this.pauseTime=(new Date).getTime(),this.passedTime+=this.pauseTime-this.startTime,this.isRunning=!1)},isRunning:function(){return this.isRunning},isReset:function(){return this.isReset},getTime:function(){return this.isReset?0:this.isRunning?(new Date).getTime()-
this.startTime+this.passedTime:this.passedTime},getCounts:function(){return a}};return c}(window)});d.namespace("mbox.lang");c.extend(d.lang,{createClass:function(a,d){var g=c.lang.createClass(a,d);g.extend=function(a){for(var b in a)g.prototype[b]=function(a,b){return c.lang.isFunction(a)?function(){this.dispatchEvent(b,{name:b,arguments:arguments});return a.apply(this,arguments)}:a}(a[b],b);return g};return g}});d.CONF={engineArg:{audio:{constructorName:"mbox.PlayEngine_Audio"},fmp:{constructorName:"mbox.PlayEngine_FMP_MP3",
args:{swfPath:"http://play.baidu.com/player/static/flash/fmp.swf",instanceName:"window.mbox.player"}}}};d.PlayEngine_Interface=d.lang.createClass(function(){var a=0,d=function(a){this.STATES={INIT:"init",READY:"ready",STOP:"stop",PLAY:"play",PAUSE:"pause",END:"end",BUFFERING:"buffering",PREBUFFER:"pre-buffer",ERROR:"error"};this.EVENTS={STATECHANGE:"player_playStateChange",POSITIONCHANGE:"player_positionChange",PROGRESS:"player_progress",ERROR:"player_error",INIT:"player_initSuccess",INITFAIL:"player_initFail"};
a=a||{};this.mute="undefined"==typeof a.mute?!1:!!a.mute;this.volume="undefined"==typeof a.volume?50:a.volume;this.ready=!1;this.url="";this.state=this.STATES.INIT;this.engineType="";this.stateStack=[this.STATES.INIT];this.supportMimeType=[]};d.prototype={newId:function(){return"_m3_"+a++},init:function(){},reset:function(){},setUrl:function(){},getUrl:function(){return this.url},play:function(){},pause:function(){},stop:function(){},setMute:function(){},getMute:function(){return this.mute},setVolume:function(){},
getVolume:function(){return this.volume},getState:function(){return""},setCurrentPosition:function(){},getCurrentPosition:function(){return 0},getLoadedPercent:function(){return 0},getLoadedBytes:function(){return 0},getTotalBytes:function(){return 0},getTotalTime:function(){return 0},getVersion:function(){return""},getEngineType:function(){return this.engineType},canPlayType:function(a){var b=this.getSupportMimeTypeList();return c.array.some(b,function(b){return a==b})},getSupportMimeTypeList:function(){return this.supportMimeType},
setEventListener:function(a,b){var d=c.fn.bind(function(){return b.apply(this,arguments)},this);this.addEventListener(a,d)}};return d}(window),{superClass:c.lang.Class,className:"PlayEngine_Interface"});d.PlayEngine_Audio=d.lang.createClass(function(){this.engineType="audio";this.contentType={mp3:["audio/mpeg","audio/mp3"],mp4:["audio/mp4","audio/MP4A-LATM","video/mpeg4","audio/mpeg4-generic"],m4a:["audio/mp4","audio/MP4A-LATM","video/mpeg4","audio/mpeg4-generic"],aac:["audio/aac","audio/aacp"],"3gp":["audio/3gpp",
"audio/3gpp2"],ogg:["audio/ogg","video/ogg","application/ogg","audio/vorbis"],oga:["audio/ogg","application/ogg","audio/vorbis"],wma:["audio/x-ms-wma"]};this.supportAudio="undefined"!=typeof Audio;this.supportMimeType=[];this.supportAudio&&(this.audio=new Audio,"function"==typeof this.audio.canPlayType&&c.object.each(this.contentType,c.fn.bind(function(a,c){for(var d=0;d<a.length;d++){var e=this.audio.canPlayType(a[d]);if("probably"==e||"maybe"==e){this.supportMimeType.push(c);break}}},this)),this.supportMimeType.length||
(this.supportAudio=!1));this.supportVolume=c.fn.bind(function(){return this.supportAudio?(this.audio.volume=0.5,1>this.audio.volume):!1},this)()},{superClass:d.PlayEngine_Interface,className:"PlayEngine_Audio"}).extend({test:function(a){!this.supportAudio&&a&&this.dispatchEvent(this.EVENTS.INITFAIL,{engineType:this.engineType});return this.supportAudio},init:function(){this.lastState=this.STATES.INIT;this.muted=this.audio.muted=!1;this.volume=50;this.audio.volume=0.5;this.url="";this._definedEvents();
this.state=this.STATES.READY;this.dispatchEvent(this.EVENTS.INIT,{engineType:this.engineType,engine:this.audio})},reset:function(){this.supportAudio&&(this.url="",this.audio.pause(),this.lastState=this.state="ready")},setUrl:function(a){this.supportAudio&&(this.url=a,this.audio.src=a,this.audio.load(),this._firePlayStateChange(this.STATES.PREBUFFER))},play:function(){if(this.supportAudio&&"ready"!=this.state)if(c.platform.isAndroid&&c.browser.isWebkit&&3>this.audio.readyState){var a=c.fn.bind(function(){this.audio.play();
this.audio.removeEventListener("canplay",a,!1)},this);this.audio.addEventListener("canplay",a,!1)}else this.audio.play()},pause:function(){this.supportAudio&&this.state!=this.STATES.STOP&&this.state!=this.STATES.READY&&this.state!=this.STATES.END&&(this.audio.pause(),this._firePlayStateChange(this.STATES.PAUSE))},stop:function(){this.supportAudio&&this.state!=this.STATES.READY&&(0!=this.audio.currentTime&&(this.audio.currentTime=0),this.audio.pause(),this._firePlayStateChange(this.STATES.STOP))},
setMute:function(a){this.supportAudio&&(this.audio.muted=this.mute=a)},setVolume:function(a){this.supportAudio&&(a=c.lang.isNumber(a)?a:50,this.volume=a=Math.max(Math.min(a,100),0),this.audio.volume=a/100)},setCurrentPosition:function(a){if(this.supportAudio&&this.getUrl())if(c.platform.isAndroid&&3>this.audio.readyState){var d=c.fn.bind(function(){this.audio.currentTime=a/1E3;this.audio.play();this.audio.removeEventListener("canplay",d,!1)},this);this.audio.addEventListener("canplay",d,!1)}else this.audio.currentTime=
a/1E3,this.audio.play()},getCurrentPosition:function(){return!this.supportAudio?0:Math.round(1E3*this.audio.currentTime)},getLoadedPercent:function(){try{var a=this.audio.buffered.end(0),c=this.audio.duration,c=isNaN(c)?0:c;return Math.round(100*(a/c))/100}catch(d){return 0}},getTotalTime:function(){if(!this.supportAudio)return 0;var a=this.audio.duration,a=isNaN(a)?0:a;return Math.round(1E3*a)},getState:function(){return this.state},_firePlayStateChange:function(a){this.state!=a&&(this.lastState=
this.state,this.state=a,this.dispatchEvent(this.EVENTS.STATECHANGE,{newState:a,oldState:this.lastState,engineType:this.engineType}))},_definedEvents:function(){this.audio.addEventListener("error",c.fn.bind(function(){this._firePlayStateChange(this.STATES.ERROR);this.dispatchEvent(this.EVENTS.ERROR,{engineType:this.engineType})},this),!1);this.audio.addEventListener("ended",c.fn.bind(function(){this._firePlayStateChange(this.STATES.END)},this),!1);this.audio.addEventListener("playing",c.fn.bind(function(){this._firePlayStateChange(this.STATES.PLAY)},
this),!1);this.audio.addEventListener("pause",c.fn.bind(function(){this.getState()==this.STATES.PLAY&&this._firePlayStateChange(this.getCurrentPosition()?this.STATES.PAUSE:this.STATES.STOP)},this),!1);this.audio.addEventListener("waiting",c.fn.bind(function(){this._firePlayStateChange(this.getCurrentPosition()?this.STATES.BUFFERING:this.STATES.PREBUFFER)},this),!1)}});d.PlayEngine_FMP_MP3=d.lang.createClass(function(a){a=a||{};this.supportMimeType=["mp3"];this.engineType="fmp_mp3";this.swfPath="fmp_mp3.swf";
this.flashVersionRequire=a.flashVersionRequire||"9.0.0";this.versionErrorMessage=a.versionErrorMessage||"";this.stateCode={"-2":this.STATES.INIT,"-1":this.STATES.READY,"0":this.STATES.STOP,1:this.STATES.PLAY,2:this.STATES.PAUSE,3:this.STATES.END,4:this.STATES.BUFFERING,5:this.STATES.PREBUFFER,6:this.STATES.ERROR};this.flashLoaded=!1;this.flashReady=new d.Fuze},{superClass:d.PlayEngine_Interface,className:"PlayEngine_FMP_MP3"}).extend({test:function(a){return this._checkPlayer(a)},init:function(a){var a=
a||{},d=a.el;this.instanceName=a.instanceName;this.swfPath=a.swfPath||this.swfPath;var g=this.newId();c.lang.isString(d)&&(d=c.g(d));d||(d=c.dom.create("div"),document.body.appendChild(d));a=c.dom.create("div");d.appendChild(a);this.swfPath+="?"+g+"_"+Math.random();c.swf.create({id:this.flashObjectId=g,width:"1px",height:"1px",ver:this.flashVersionRequire,errorMessage:this.versionErrorMessage,allowscriptaccess:"always",url:this.swfPath,bgcolor:"#ffffff",wmode:"window",scale:"noscale",vars:{_instanceName:this.instanceName+
"",_buffertime:2E3}},a);this.flashObject=c.swf.getMovie(this.flashObjectId)},reset:function(){this.stop();this.state!=this.STATES.INIT&&(this.url="",this.state=this.STATES.READY,this.stateStack=[this.STATES.READY])},setUrl:function(a){this.flashReady(c.fn.bind(function(){this.url=a;this.flashObject.closeStream();this.flashObject.f_load(a)},this))},play:function(){this.flashReady(c.fn.bind(function(){this.state!=this.STATES.PLAY&&this.flashObject.f_play()},this))},pause:function(){this.flashReady(c.fn.bind(function(){this.state==
this.STATES.PAUSE||this.state==this.STATES.STOP||this.state==this.STATES.END||this.flashObject.f_pause()},this))},stop:function(){this.flashReady(c.fn.bind(function(){this.state!=this.STATES.STOP&&this.flashObject.f_stop()},this))},setMute:function(a){this.flashReady(c.fn.bind(function(){this.mute=a;this.flashObject.setData("mute",a)},this))},setVolume:function(a){this.flashReady(c.fn.bind(function(){this.volume=a;this.flashObject.setData("volume",a)},this))},setCurrentPosition:function(a){this.flashReady(c.fn.bind(function(){this.flashObject.f_play(a)},
this))},getCurrentPosition:function(){return this.flashLoaded?this.flashObject.getData("currentPosition"):0},getLoadedPercent:function(){return this.flashLoaded?this.flashObject.getData("loadedPct"):0},getTotalTime:function(){return this.flashLoaded?this.flashObject.getData("length"):0},getState:function(a){return c.lang.isNumber(a)?this.stateCode[a]:this.state},getVersion:function(){return c.swf.version},_firePlayStateChange:function(a){if(this.state!=a){this.state=a;this.stateStack.push(a);var c=
this.stateStack.shift();this.dispatchEvent(this.EVENTS.STATECHANGE,{newState:a,oldState:c,engineType:this.engineType})}},_onLoad:function(){this.state=this.STATES.READY;this.stateStack=[this.state];this.dispatchEvent(this.EVENTS.INIT,{engineType:this.engineType,engine:this.flashObject});setTimeout(c.fn.bind(function(){this.flashReady.fire();this.flashLoaded=!0},this),0)},_onPlayStateChange:function(a){setTimeout(c.fn.bind(function(){this._firePlayStateChange(this.getState(a))},this),0)},_checkPlayer:function(a){var a=
!!a,d=c.swf.version,g=this.flashVersionRequire;if(d){d=d.split(".");g=g.split(".");if(0<=d[0]-g[0]&&0<=d[1]-g[1])return!0;a&&this.dispatchEvent(this.EVENTS.INITFAIL,{engineType:this.engineType});return!1}a&&this.dispatchEvent(this.EVENTS.INITFAIL,{engineType:this.engineType});return!1}});d.PlayEngine=d.lang.createClass(function(a){a=a||{};this.subEnginesConf=[];this.subEnginesInitAr