(function(g){var window=this;var mKa=function(a,b,c){g.um(a,b,c,null)||g.ob(g.sa(b,a))},nKa=function(){var a=L3;
return new g.gm(function(b,c){var d=a.length,e=[];if(d)for(var h=function(a,c){d--;e[a]=c;0==d&&b(e)},k=function(a){c(a)},n=0,r;n<a.length;n++)r=a[n],mKa(r,g.sa(h,n),k);
else b(e)})},M3=function(a){var b=g.t("YPC_LOADER_CSS",void 0),c=g.t("YPC_LOADER_JS",void 0);
oKa&&(c="www/ypc_core");L3.length||(L3.push(new g.gm(function(a){g.kf(b,a)})),L3.push(new g.gm(function(a){g.Fc(c,a)})));
nKa().then(function(){a&&a()})},O3=function(a,b,c,d,e){if(g.yr())M3(function(){g.m("yt.www.ypc.checkout.showYpcOverlay")(a,b,c,d,e)});
else{var h={ypc_it:a,ypc_ii:b,ypc_ft:c};d&&(h.ypc_irp=d);e&&(h.ypc_cc=e);h=N3(h);g.Ae(h)}},pKa=function(a,b){if(g.yr())M3(function(){g.m("yt.www.ypc.checkout.showYpcOverlayForInnertubeRequestParams")(a,b)});
else{var c=N3({ypc_ft:a,ypc_irp:b});g.Ae(c)}},qKa=function(a,b,c,d,e,h){if(g.yr())M3(function(){g.m("yt.www.ypc.checkout.offerpurchaser.purchaseOffer")(a,b,c,"D",d,e,h)});
else{var k={ypc_it:b,ypc_ii:c,ypc_ft:"D"};h&&(k.ypc_irp=h);k=N3(k);g.Ae(k)}},rKa=function(a,b){if(g.yr())M3(function(){g.m("yt.www.ypc.subscription.openUnsubscribeOverlay")(a,b)});
else throw Error("Unsubscribe triggered when user not signed in.");},N3=function(a){a=g.rk(window.location.href,a);
var b=g.t("YPC_SIGNIN_URL",void 0),c=g.sk(b)["continue"],c=g.rk(c,{next:a});return g.rk(b,{"continue":c})},sKa=function(a){var b=a.currentTarget;
if(b){a=g.w(b,"ypc-offer-id");var c=g.w(b,"ypc-item-type"),d=g.w(b,"ypc-item-id"),e=g.w(b,"ypc-offer-jwt"),h=g.w(b,"ypc-offer-encrypted-purchase-params"),b=g.w(b,"ypc-irp");qKa(a,c,d,e,h,b)}},uKa=function(a){(a=a.currentTarget)&&tKa(a)},vKa=function(a){M3(a.Zb)},wKa=function(a){var b;
P3("container-button-click-attempt");b=g.z("ypc-checkout-button",a.A);a=g.z("ytr-purchase-button",a.A);if(b||a&&a.href)a&&a.href?g.Be(a.href):b&&tKa(b)},xKa=function(a){var b=a.A;
a=b.itemId;var c=b.itemType,b=b.flowType;P3("paid-subscribe-button-click",{itemType:c,itemId:a});O3(c,a,b)},tKa=function(a){var b=g.w(a,"ypc-item-type"),c=g.w(a,"ypc-item-id"),d=g.w(a,"ypc-flow-type");
a=g.w(a,"ypc-irp")||void 0;g.yr()?P3("purchase-button-click",{itemId:c,itemType:b}):P3("signin-button-click");O3(b,c,d,a)},yKa=function(a){var b=a.currentTarget;
a=g.w(b,"ypc-item-type");b=g.w(b,"ypc-item-id");a&&b&&(P3("unsubscribe-button-click",{itemId:b,itemType:a}),rKa(a,b))},zKa=function(a){var b=a.A;
a=b.itemType;b=b.itemId;P3("paid-unsubscribe-button-click",{itemType:a,itemId:b});rKa(a,b)},P3=function(a,b){var c={};
g.Xa(c,{label:a,pageName:g.t("PAGE_NAME")});b&&g.Xa(c,b);c=g.sd(c);g.Vi("ypc-checkout",c,void 0)},R3=function(a,b,c){this.D=this.B=this.A=null;
this.C=a;this.G=Q3?b:null;this.R=c||window;this.F=this.R.location;this.H=this.F.href.split("#")[0];this.M=(0,g.p)(this.O,this)},S3=function(a){a=a.F.href;
var b=a.indexOf("#");return 0>b?"":a.substring(b+1)},AKa=function(a,b){var c=a.H+"#"+b,d=a.F.href;
d!=c&&d+"#"!=c&&g.Ac(a.F,c)},T3=function(a,b){var c=a.G.contentWindow.document,d="#"+g.va(b);
if((c.body?c.body.innerHTML:"")!=d){var e=g.yc(g.xc("title",{},window.document.title||""),g.xc("body"));c.open("text/html");c.write(g.sc(e));g.oh(c.body,d);c.close()}},U3=function(a,b){this.C=this.G=this.A=null;
this.D=a;this.F=b||window;this.B=this.F.location;this.M=(0,g.p)(this.R,this)},CKa=function(){var a=BKa("state");
a.setEnabled.call(a,!0,!0)},DKa=function(a){var b=BKa();
b.replace.call(b,a,window.history&&window.history.state,!0)},BKa=function(a){a=a||"hash";
var b=g.m("yt.history.instance_");b||("state"==a?(b=new U3(EKa),U3.prototype.setEnabled=U3.prototype.Db,U3.prototype.add=U3.prototype.Y,U3.prototype.replace=U3.prototype.replace):(b=new R3(EKa,g.x("legacy-history-iframe")),R3.prototype.setEnabled=R3.prototype.Db,R3.prototype.add=R3.prototype.Y,R3.prototype.replace=R3.prototype.Y),FKa=b,g.l("yt.history.instance_",FKa,void 0));return b},EKa=function(a,b){g.v("navigate",a,b)},IKa=function(){var a=g.sk(window.location.href);
if(GKa){g.Qa(HKa,function(b){g.Ta(a,b)});
var b=g.td(window.location.href.split("?",2)[0],a);CKa();DKa(b)}},L3=[],oKa=!1;var V3=[],W3=[];var FKa,JKa=g.A&&8<=window.document.documentMode||g.De&&g.Oc("1.9.2")||g.$c&&g.Oc("532.1"),Q3=g.A&&!JKa;R3.prototype.Db=function(a,b){this.B&&(g.Oi(this.B),delete this.B);this.D&&(g.Db(this.D),delete this.D);if(a){this.A=S3(this);if(Q3){var c=this.G.contentWindow.document.body;c&&c.innerHTML||T3(this,this.A)}b||this.C(this.A);JKa?this.B=g.F(this.R,"hashchange",this.M):this.D=g.Bb(this.M,200)}};
R3.prototype.O=function(){if(Q3){var a;a=(a=this.G.contentWindow.document.body)?g.Bh(g.Hk(a).substring(1)):"";a!=this.A?(this.A=a,AKa(this,a),this.C(a)):(a=S3(this),a!=this.A&&(this.A=a,T3(this,a),this.C(a)))}else a=S3(this),a!=this.A&&(this.A=a,this.C(a))};
R3.prototype.Y=function(a,b,c){this.A=""+a;Q3&&T3(this,a);AKa(this,a);c||this.C(this.A)};var GKa=!!window.history.pushState&&(!g.$c||g.$c&&g.Oc("534.11"));U3.prototype.Db=function(a,b){this.C&&(g.Oi(this.C),delete this.C);this.G&&(g.Db(this.G),delete this.G);a&&GKa&&(this.A=this.B.href,b||this.D(this.A),this.C=g.F(this.F,"popstate",this.M))};
U3.prototype.R=function(a){var b=this.B.href;if((a=a.state)||b!=this.A)this.A=b,this.D(b,a)};
U3.prototype.Y=function(a,b,c){if(a||b)a=a||this.B.href,this.F.history.pushState(b,"",a),this.A=a,c||this.D(a,b)};
U3.prototype.replace=function(a,b,c){if(a||b)a=a||this.B.href,this.F.history.replaceState(b,"",a),this.A=a,c||this.D(a,b)};var HKa={eS:"ypc_cc",rS:"ypc_ft",OS:"ypc_irp",WS:"ypc_ii",XS:"ypc_it"};g.Zb(g.Uk({name:"www/ypc_bootstrap",deps:["www/common"],page:"feed index results watch channel playlist subscription_manager unlimited".split(" "),init:function(){oKa=!0;g.z("ypc-delayedloader-target")&&M3();var a=g.sk(window.location.href),b=a.ypc_it,c=a.ypc_ii,d=a.ypc_ft||"D",e=a.ypc_irp,h=a.ypc_cc;"channel"==g.t("PAGE_NAME")&&"fan_fund"in a&&(d="T",b="U",c=g.t("CHANNEL_ID",void 0));"channel"==g.t("PAGE_NAME")&&"ypc_cc"in a&&(b="U",c=g.t("CHANNEL_ID",void 0));if(e||c&&b)IKa(),c&&b?O3(b,c,d,e,h):
pKa(d,e);V3.push(g.Wj(window.document.body,"click",uKa,"ypc-checkout-button"),g.Wj(window.document.body,"click",sKa,"ypc-offer-button"),g.Wj(window.document.documentElement,"click",yKa,"ypc-unsubscribe-link"),g.Wj(window.document.documentElement,"click",yKa,"ypc-unsubscribe-button"));W3.push(g.vk(g.nv,vKa),g.vk(g.Hka,wKa),g.vk(g.ov,xKa),g.vk(g.rv,zKa))},
dispose:function(){L3.length=0;g.Oi(V3);V3.length=0;g.uk(W3);W3.length=0}}));
g.l("yt.www.ypc.bootstrap.api.loadOffers",O3,void 0);g.l("yt.www.ypc.bootstrap.api.loadOffersForInnertubeRequestParams",pKa,void 0);})(_yt_www);
