(function(g){var window=this;var opa=function(a,b,c){g.jm(a,b,c,null)||g.Ml(g.r(b,a))};var ppa=function(){var a=J1;return new g.Vl(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},k=function(a){c(a)},l=0,p;p=a[l];l++)opa(p,g.r(f,l),k);else b(e)})};var K1=function(a){var b=g.x("YPC_LOADER_CSS"),c=g.x("YPC_LOADER_JS");L1&&(c="www/ypc_core");J1.length||(J1.push(new g.Vl(function(a){g.ff(b,a)})),J1.push(new g.Vl(function(a){g.gc(c,a)})));ppa().then(function(){a&&a()})};
var M1=function(a,b,c,d,e){if(g.nq())K1(function(){g.n("yt.www.ypc.checkout.showYpcOverlay")(a,b,c,d,e)});else{var f={ypc_it:a,ypc_ii:b,ypc_ft:c};d&&(f.ypc_irp=d);e&&(f.ypc_cc=e);f=N1(f);g.ce(f)}};var O1=function(a,b){if(g.nq())K1(function(){g.n("yt.www.ypc.subscription.openUnsubscribeOverlay")(a,b)});else throw Error("Unsubscribe triggered when user not signed in.");};
var P1=function(a,b){if(g.nq())K1(function(){g.n("yt.www.ypc.checkout.showYpcRedeemGiftOverlay")(a,b)});else{var c=N1({ypc_grc:a,ypc_ft:b});g.ce(c)}};var N1=function(a){a=g.ek(window.location.href,a);var b=g.x("YPC_SIGNIN_URL"),c=g.fk(b)["continue"],c=g.ek(c,{next:a});return g.ek(b,{"continue":c})};var qpa=function(a){(a=a.currentTarget)&&Q1(a)};var rpa=function(a){K1(a.lc)};var spa=function(a){R1("container-button-click-attempt");(a=g.F("ypc-checkout-button",a.j))&&Q1(a)};
var tpa=function(a){var b=a.j;a=b.itemId;var c=b.itemType,b=b.flowType;R1("paid-subscribe-button-click",{itemType:c,itemId:a});M1(c,a,b)};var Q1=function(a){var b=g.C(a,"ypc-item-type"),c=g.C(a,"ypc-item-id"),d=g.C(a,"ypc-flow-type");a=g.C(a,"ypc-irp")||void 0;g.nq()?R1("purchase-button-click",{itemId:c,itemType:b}):R1("signin-button-click");M1(b,c,d,a)};
var S1=function(a){var b=a.currentTarget;a=g.C(b,"ypc-item-type");b=g.C(b,"ypc-item-id");a&&b&&(R1("unsubscribe-button-click",{itemId:b,itemType:a}),O1(a,b))};var upa=function(a){var b=a.j;a=b.itemType;b=b.itemId;R1("paid-unsubscribe-button-click",{itemType:a,itemId:b});O1(a,b)};var R1=function(a,b){var c={};g.Cb(c,{label:a,pageName:g.x("PAGE_NAME")});b&&g.Cb(c,b);c=g.Zc(c);g.Hi("ypc-checkout",c,void 0)};
var T1=function(a,b,c){this.l=a;U1&&(this.C=b);this.L=c||window;this.A=this.L.location;this.G=this.A.href.split("#")[0];this.D=(0,g.q)(this.K,this)};var V1=function(a){a=a.A.href;var b=a.indexOf("#");return 0>b?"":a.substring(b+1)};var W1=function(a,b){var c=a.G+"#"+b,d=a.A.href;d!=c&&d+"#"!=c&&g.cc(a.A,c)};
var X1=function(a,b){var c=a.C.contentWindow.document,d="#"+g.va(b);if((c.body?c.body.innerHTML:"")!=d){var e=g.ac(g.Yb("title",{},window.document.title||""),g.Yb("body"));c.open("text/html");c.write(g.Vb(e));g.ch(c.body,d);c.close()}};var Y1=function(a,b){this.A=a;this.B=b||window;this.l=this.B.location;this.D=(0,g.q)(this.L,this)};var vpa=function(){var a=Z1("state");a.setEnabled.call(a,!0,!0)};var wpa=function(a){var b=Z1();b.replace.call(b,a,window.history&&window.history.state,!0)};
var Z1=function(a){a=a||"hash";var b=g.n("yt.history.instance_");b||("state"==a?(b=new Y1($1),Y1.prototype.setEnabled=Y1.prototype.Gb,Y1.prototype.add=Y1.prototype.add,Y1.prototype.replace=Y1.prototype.replace):(b=new T1($1,g.E("legacy-history-iframe")),T1.prototype.setEnabled=T1.prototype.Gb,T1.prototype.add=T1.prototype.add,T1.prototype.replace=T1.prototype.add),a2=b,g.m("yt.history.instance_",a2,void 0));return b};var $1=function(a,b){g.B("navigate",a,b)};
var b2=function(a){var b=g.fk(window.location.href);c2&&(g.wb(a,function(a){g.zb(b,a)}),a=g.$c(window.location.href.split("?",2)[0],b),vpa(),wpa(a))};var J1=[],L1=!1;var d2=[],e2=[];var a2,f2=g.D&&8<=window.document.documentMode||g.oc&&g.sc("1.9.2")||g.qc&&g.sc("532.1"),U1=g.D&&!f2;T1.prototype.Gb=function(a,b){this.B&&(g.M(this.B),delete this.B);this.F&&(g.Za(this.F),delete this.F);if(a){this.j=V1(this);if(U1){var c=this.C.contentWindow.document.body;c&&c.innerHTML||X1(this,this.j)}b||this.l(this.j);f2?this.B=g.L(this.L,"hashchange",this.D):this.F=g.Wa(this.D,200)}};
T1.prototype.K=function(){if(U1){var a;a=(a=this.C.contentWindow.document.body)?g.th(g.sk(a).substring(1)):"";a!=this.j?(this.j=a,W1(this,a),this.l(a)):(a=V1(this),a!=this.j&&(this.j=a,X1(this,a),this.l(a)))}else a=V1(this),a!=this.j&&(this.j=a,this.l(a))};T1.prototype.add=function(a,b,c){this.j=""+a;U1&&X1(this,a);W1(this,a);c||this.l(this.j)};var c2=!!window.history.pushState&&(!g.qc||g.qc&&g.sc("534.11"));Y1.prototype.Gb=function(a,b){this.C&&(g.M(this.C),delete this.C);this.F&&(g.Za(this.F),delete this.F);a&&c2&&(this.j=this.l.href,b||this.A(this.j),this.C=g.L(this.B,"popstate",this.D))};Y1.prototype.L=function(a){var b=this.l.href;if((a=a.state)||b!=this.j)this.j=b,this.A(b,a)};Y1.prototype.add=function(a,b,c){if(a||b)a=a||this.l.href,this.B.history.pushState(b,"",a),this.j=a,c||this.A(a,b)};
Y1.prototype.replace=function(a,b,c){if(a||b)a=a||this.l.href,this.B.history.replaceState(b,"",a),this.j=a,c||this.A(a,b)};var xpa={yK:"ypc_cc",Ov:"ypc_ft",eL:"ypc_irp",mL:"ypc_ii",nL:"ypc_it"},ypa={VK:"ypc_grc",Ov:"ypc_ft"};g.tb(g.Kk({name:"www/ypc_bootstrap",deps:["www/common"],page:"feed index results watch channel playlist subscription_manager unlimited".split(" "),init:function(){L1=!0;g.F("ypc-delayedloader-target")&&K1();var a=g.fk(window.location.href),b=a.ypc_it,c=a.ypc_ii,d=a.ypc_ft||"D",e=a.ypc_irp,f=a.ypc_cc;"channel"==g.x("PAGE_NAME")&&"fan_fund"in a&&(d="T",b="U",c=g.x("CHANNEL_ID"));"channel"==g.x("PAGE_NAME")&&"ypc_cc"in a&&(b="U",c=g.x("CHANNEL_ID"));"RG"==d?(a=a.ypc_grc,b2(ypa),P1(a,d)):c&&b&&(b2(xpa),
M1(b,c,d,e,f));d2.push(g.R(window.document.body,"click",qpa,"ypc-checkout-button"),g.R(window.document.documentElement,"click",S1,"ypc-unsubscribe-link"),g.R(window.document.documentElement,"click",S1,"ypc-unsubscribe-button"));e2.push(g.ik(g.rt,rpa),g.ik(g.bG,spa),g.ik(g.tt,tpa),g.ik(g.wt,upa))},dispose:function(){J1.length=0;g.M(d2);d2.length=0;g.hk(e2);e2.length=0}}));g.m("yt.www.ypc.bootstrap.api.loadOffers",M1,void 0);g.m("yt.www.ypc.bootstrap.api.loadRedeemGiftOverlay",P1,void 0);})(_yt_www);
