__d("common.js.setHome",[],function(j,k,h){function a(){f||(f=document.createElement("div"),f.style.display="none",f.style.behavior="url(#default#homePage)",document.body.appendChild(f));return f}function g(d){try{return a().isHomePage(d)}catch(c){return!1}}var f=!1;k.exports={set:function(d,c){a().setHomePage(d);g(d)?c&&c(!0):c&&c(!1)},getHomePageUrl:function(){var a,c,m;a=["http://",""];c=["www.hao123.com","3w.hao123.com","ww.hao123.com","hao123.com","z.hao123.com"];m=["","/","/?from=hao123","/?f=vip",
"/?from=newhome"];for(var e=[],b=0;b<m.length;b++)for(var l=0;l<c.length;l++)for(var i=0;i<a.length;i++)e.push(a[i]+c[l]+m[b]);a=-1;for(c=e.length;++a<c;)if(m=e[a],g(m))return m;return!1},isHomePage:g};return h});
__d("widget.popup.mask",["common.js.browser"],function(j,k,h,a){function g(){var a=c.body;return Math.max(c.documentElement.scrollHeight,a.scrollHeight,("BackCompat"==c.compatMode?a:c.documentElement).clientHeight)+"px"}var f=a("common.js.browser"),d=null,c=j.document;return h={show:function(){d||(d=c.createElement("div"),d.className="popup-mask",c.body.appendChild(d));6==f.ie&&(d.style.height=g());d.style.display=""},hide:function(){d&&(d.style.display="none")},refresh:function(){d&&(d.style.height=
g())},remove:function(){d&&(d.parentNode.removeChild(d),d=null)}}});__d("common.js.refer",["common.js.browser","common.js.setHome"],function(j,k,h,a){var g=a("common.js.browser"),f=a("common.js.setHome");k.exports={getUserType:function(){return g.ie&&11>parseInt(g.ie)?f.getHomePageUrl()?0:1:g.isHao123()?2:3}};return h});
__d("common.js.homeLog",["common.js.log","common.js.config","common.js.refer","common.js.browser"],function(j,k,h,a){var g=a("common.js.log"),j=a("common.js.config"),f=a("common.js.refer"),k=a("common.js.browser"),a=window.location.search.match(/[?&](tn|src)=([^&<>'"]+)/)?1:0,k=k.ie?1:0;j.get("pageId");var d={pageId:j.get("pageId"),ie:k,tn:a,type:"ubclick"};return function(a){for(var m in d)d.hasOwnProperty(m)&&!(m in a)&&(a[m]=d[m]);a.ho=f.isIENotHome()?0:1;"set"in a&&(a.set=Number(a.set),a.set=
a.position+""+a.set,delete a.position);g(a)}});
__d("widget.popup.base",["widget.popup.mask","common.js.browser","common.js.pageEvents","common.js.widget"],function(j,k,h,a){function g(a){var a=a||c.getViewport(),e=a.width,b=(a.height-this.height)/2;6==d.ie&&(f.refresh(),b+=a.scrollTop);this.element&&this.element.css({left:(e-this.width)/2,top:b})}var f=a("widget.popup.mask"),d=a("common.js.browser"),c=a("common.js.pageEvents");a("common.js.widget");$.widget("lottery.popup",{_baseCreate:function(){this.element.addClass(this.options.className);this._appendToBody=
!1},_baseShow:function(a){this._appendToBody||(this.element.appendTo("body"),this._appendToBody=!0);this.height=this.element.height();this.width=this.element.width();0<arguments.length&&"function"==typeof a?(g.call(this),a(this.element)):this.element.show();this.options.isModel&&f.show();c.on("viewport.deferchange",g,this);g.call(this)},_baseHide:function(a){var e=this;0<arguments.length&&"function"==typeof a?a(this.element,function(){e.element.hide();e.options.isModel&&f.hide()}):(this.element.hide(),
this.options.isModel&&f.hide())},remove:function(a){var e=this;0<arguments.length&&"function"==typeof a?a(this.element,function(){e.element.remove();e.options.isModel&&f.remove()}):(this.element.remove(),this.options.isModel&&f.remove())}});return h});
__d("widget.popup.sethome",["widget.popup.base","common.js.log","widget.popup.getTpl","common.js.cookie"],function(j,k,h,a){a("widget.popup.base");var g=a("common.js.log"),f=a("widget.popup.getTpl"),d=a("common.js.cookie");$.widget("hao123.sethome",$.lottery.popup,{options:{className:"popup-sethome",isModel:!0},_create:function(){this._baseCreate();var a=this.element,g=this;$(".js_close",a).click(function(){g._baseHide();return!1});$(".js_ok",a).click(function(){g._baseHide();$(".widget-topbanner").attr("data-is")&&
"popup_active_cj"!=$(this).attr("id")&&($(f("active")).sethome().sethome("show"),$(".popup-sethome-title-active").addClass("browser"),d.get("ss_active")||d.set("ss_active","1"))}).text(g.options.okText)},show:function(){this._baseShow();g({type:"sethomeshow"})}});return h});
__d("widget.popup.getTpl",["common.js.format"],function(j,k,h,a){var g=a("common.js.format"),f={head:'<div class="popup-head"><a class="js_close" href="javascript:void(0);"></a><span class="js_title"></span></div>',confirm:"<div class='popup-body'><i></i><div><strong class='js_text'></strong> <p><button class='button js_ok'  ></button><button class='button js_cancel' >\u53d6\u6d88</button></p></div></div>",alert:"<div class='popup-alert-w'><p class='popup-alert-text js_text'></p><p class='popup-alert-control'><button class='button js_ok'>\u786e\u5b9a</button></p></div>",
sethome:"<div class='popup-sethome' monkey='homefail'><p class='popup-sethome-title'></p><p class='popup-sethome-text'>\u60a8\u53ef\u80fd\u6b63\u906d\u53d7\u6076\u610f\u8f6f\u4ef6\u7684\u5f3a\u884c\u7be1\u6539<br/>\u5efa\u8bae\u60a8\u5b89\u88c5hao123\u6d4f\u89c8\u5668\uff0c\u4fdd\u62a4\u60a8\u7684\u4e3b\u9875</p><p class='popup-sethome-hint'>\u4ec5\u97002\u79d2\u5373\u53ef\u5b8c\u6210</p><a class='popup-sethome-close js_close' href='###'></a><a class='popup-sethome-ok js_ok' href='http://update.123juzi.net/dl.php?edition=hao123_juzi_canal&cid=94906731_o2_hao_' title='\u4e0b\u8f7dhao123\u6d4f\u89c8\u5668'></a></div>",
upload:'<div class="popup-upload-w g_clr"><div class="g-ib popup-upload-ct"><p class="popup-upload-select"><button class="popup-upload-btns"></button><span class="btnselect js_select"></span><span class="tip js_text"></span></p><div class="popup-upload-desk js_cutter"></div><div class="popup-upload-state" style="display:none;"><span class="state-txt js_stattxt"></span></div><p class="popup-upload-caijian"><button class="popup-upload-btncj js_ok"></button></p></div></div>',sethomeNotie:"<div class='popup-sethome' monkey=sethomeNotie'><p class='popup-sethome-title-notie'></p><p class='popup-sethome-text' style='color:#F46417'>\u60a8\u7684\u6d4f\u89c8\u5668\u4e0d\u652f\u6301\u4e00\u952e\u8bbe\u4e3a\u4e3b\u9875<br/>\u5efa\u8bae\u4e0b\u8f7dhao123\u6d4f\u89c8\u5668\uff0c\u4e0a\u7f51\u66f4\u5feb\u66f4\u7b80\u5355</p><p class='popup-sethome-hint-notie-w'><a class='popup-sethome-hint-notie' href='#{openUrl}'>#{helpText}\u6d4f\u89c8\u5668\u4e2d\uff0c\u5982\u4f55\u8bbehao123\u4e3a\u4e3b\u9875\uff1f</a></p><a class='popup-sethome-close js_close' href='###'></a><a class='popup-sethome-ok js_ok' title='\u4e0b\u8f7dhao123\u6d4f\u89c8\u5668' href='http://update.123juzi.net/dl.php?edition=hao123_juzi_canal&cid=94906731_o2_hao_'></a></div>",
active:'<div class="popup-sethome" monkey="active"><p class="popup-sethome-title-active"></p><p class="popup-sethome-text-active"></p><a class="popup-sethome-close js_close" href="###"></a><a id="popup_active_cj" class="popup-sethome-ok js_ok" title="\u5feb\u53bb\u62bd\u5956\u5427" href="http://www.hao123.com/sethome"></a></div>',tpl:"<div class='popup'>#{head}#{content}</div>"};return function(a){return"sethome"==a||"sethomeNotie"==a||"active"==a?f[a]:g(f.tpl,{head:f.head,content:f[a]})}});
__d("common.js.home","widget.popup.mask,common.js.browser,widget.popup.getTpl,common.js.refer,common.js.format,common.js.homeLog,common.js.log,common.js.cookie,widget.popup.sethome".split(","),function(j,k,h,a){function g(e,a,i){try{return i&&(f.show(),n.show()),e.style.behavior="url(#default#homepage)",e.setHomePage(a),i&&(f.hide(),n.hide()),e.isHomePage(a)}catch(b){return!1}}var f=a("widget.popup.mask"),d=a("common.js.browser"),c=a("widget.popup.getTpl"),m=a("common.js.refer"),e=a("common.js.format"),
b=a("common.js.homeLog"),l=a("common.js.log"),i=a("common.js.cookie"),o=null,s=null;a("widget.popup.sethome");var n={_element:null,show:function(){this._element||(this._element=document.createElement("div"),this._element.className=$(".widget-topbanner").attr("data-is")?"sethomehint-isset":"sethomehint");var e,a;e=document.documentElement.clientHeight;a=document.documentElement.clientWidth;this._element.style.top=parseInt(e/2)-80+document.documentElement.scrollTop+"px";this._element.style.left=parseInt(a/
2)-480+"px";1E3<a&&6<d.ie&&document.body.appendChild(this._element)},hide:function(){this._element.parentNode.removeChild(this._element)}};return h={set:function(e,a,d){b({link:d});if("length"in e){if(0>=e.length)return!1;e=e[0]}e=g(e,a,!0);b({set:e,position:d});m.refresh();m.isIENotHome()?(o||(o=$(c("sethome")).sethome()),o.sethome("show"),l({page:"index",level:1,type:"auto",monkey:"m-sethome-failure",k:"m-sethome-failure"})):(l({page:"index",level:1,type:"auto",monkey:"m-sethome-success",k:"m-sethome-success"}),
$(".widget-topbanner").attr("data-is")&&($(c("active")).sethome().sethome("show"),$("#popup_active_cj").on("click",function(){i.get("ss_active")||i.set("ss_active","1")})));return!0},setNotie:function(a){s||(s=$(e(c("sethomeNotie"),a)).sethome());s.sethome("show");l({page:"index",level:1,type:"auto",monkey:"m-sethome-failure",k:"m-sethome-failure"})},is:function(e){try{return homePageDom||(homePageDom=document.createElement("div"),homePageDom.style.display="none",homePageDom.style.behavior="url(#default#homePage)",
document.body.appendChild(homePageDom)),homePageDom.isHomePage(e)}catch(a){}}}});
__d("widget.baiduIcon.baiduIcon",["common.js.widget","common.js.browser","common.js.log"],function(j,k,h,a){a("common.js.widget");var g=a("common.js.browser"),f=a("common.js.log");$.widget("hao123.baiduIcon",{_create:function(){if(g.isBaidu){g=window.location.search.match(/[?&]browser=([^&<>'"]+)/);var a=this;g&&"baidu"==g[1]&&$(function(){var c=a.element;$(".hao123-header-right",c).css({position:"absolute",right:100});$(c).before(" <a id='baidubrowser' href='bdbrowser://tabpage/#source=hao123' target='_self' style='position:absolute; z-index:999;left:50%;margin-left:412px;top:6px;width:58px; font-size:12px;background:url(http://s0.hao123img.com/res/img/baidulink.png) no-repeat; padding-left:20px;line-height:18px'>\u6700\u5e38\u8bbf\u95ee</a>");
$("#baidubrowser").click(function(){f({level:1,page:window.pageId,type:"baidubrowser"})})})}}});return h});
__d("widget.hao123Startup.hao123Startup",["common.js.widget"],function(j,k,h,a){a("common.js.widget");$.widget("hao123.hao123Startup",{_create:function(){if(!(0>window.location.search.indexOf("browser=startup"))){var a=$('<div class="hao123startup-welcome"></div>').appendTo(this.element),f=$('<div class="hao123startup-hint"></div>');$("body div:first").before(f);window.setTimeout(function(){a.animate({height:0},1E3,function(){})},3E3);window.setTimeout(function(){f.fadeOut()},33E3)}}});return h});
__d("widget.ad2012.ad2012",["common.js.widget"],function(j,k,h,a){a("common.js.widget");$.widget("hao123.ad2012",{_create:function(){function a(){i-=b;-i>m*l&&(i=-m*l,l++,window.clearInterval(o),o=null,l>d&&(l=1,i=0));c.element.css({top:i})}function f(){null===o&&(o=window.setInterval(a,e))}var d=this.element.children().length-1,c=this;if(!(2>d)){var m=30,e=16,b=1,l=1,i=0,o=null,h=null;c.element.append($("<div></div>").append(c.element.get(0).children[0].innerHTML));h=window.setInterval(f,5E3);c.element.find("a").hover(function(){window.clearInterval(h);
h=null},function(){null===h&&(h=window.setInterval(f,5E3))})}}});return h});
__d("site.searchLog",["common.js.log","common.js.config"],function(j,k,h,a){var g=a("common.js.log"),f=a("common.js.config");return function(a){a.on("searchfloatsubmit",function(){g({type:"floatsubmit"})});a.on("searchspecialshow",function(){g({type:"suggestspecialshow"})});a.on("searchsecialsubmit",function(a,f){g({type:"special",hit:f.hit,from:f.from,toerji:f.toerji,index:f.index})});a.on("searchsubmit",function(a,d){var e={type:"submit",position:d.tab,title:d.query,pageId:f.get("pageId")};void 0!==
d.ssl_type&&d.ssl_tn&&(e.ssl_type=d.ssl_type,e.ssl_tn=d.ssl_tn);switch(d.action){case "button":e.btnclick=1;break;case "select":e.sug=1}g(e)}).on("searchsubmit",function(a,d){var e={type:"clicksug",flag:1,pageId:f.get("pageId")};e.src={input:2,suggest:2,hotword:{web:1,image:3}}[d.from][d.tab]||2;e.sugposition=d.suggestIndex;e.title=d.query;g(e)}).on("searchhotwordshow",function(){g({sugposition:1,pageId:f.get("pageId")})})}});
__d("site.swayLogo",["common.js.home","common.js.cookie","common.js.refer"],function(j,k,h,a){var g=a("common.js.home"),f=a("common.js.cookie"),d=a("common.js.refer"),c=null;return h={init:function(a,e){c=a;var b=e.height()-12,d=$('<span  style="background:url(http://s0.hao123img.com/res/images/swayLogo.gif);position:absolute;cursor:pointer; width:169px; height:90px; top:'+b+'px; left:-20px;"></span>');c.append(d);var i=$('<span style="background:url(http://s0.hao123img.com/res/images/swaylogo-close.png?r=1) no-repeat;cursor:pointer; width:16px; height:16px; position:absolute; top:'+
(b+19)+'px; right:30px;"></span>');c.append(i);i.click(function(){d.hide();i.hide();f.set("swaylogo",1);return!1});i.mousedown(function(){return!1})},onClick:function(){g.set(c,"http://www.hao123.com/?f=amusing",4);return!1},check:function(){return f.has("swaylogo")||!d.isIENotHome()?!1:!0}}});
__d("common.js.dns",["common.js.log","common.js.jquery","common.js.cookie","common.js.parseUrl"],function(j,k,h,a){var g,f,d;function c(){var e="";1>=Math.ceil(100*Math.random())&&(e=o("html").html()||"",setTimeout(function(){o.ajax({url:"/api/postcontent",type:"POST",data:{c:s,content:e||""}})},1E4))}function m(){p=!1;var a={},b={},a=e();top!=window&&(parent.document?(a.p_t=0,b=e(parent.document),a.p_code=b.code,b&&b.s&&(a.p_s=b.s),b&&b.f&&(a.p_f=b.f),b&&b.fs&&(a.p_fs=b.fs)):a.p_t=1);if(r||p)a.kfcst=
q,i(a);(1==a.code||1==a.p_code)&&c()}function e(e){var a=e||document,e=a.getElementsByTagName("iframe"),b=a.getElementsByTagName("script"),a=a.getElementsByTagName("frame"),i={iframes:[],scripts:[],frames:[]},l={type:"KFC"},c=function(e,a){if(e){var b=!1,l;l=n;var c=e;-1<c.indexOf("#")&&(c=c.substr(0,c.indexOf("#")));-1<c.indexOf("?")&&(c=c.substr(0,c.indexOf("?")));c=l(c);switch(a){case "scripts":l=g;break;case "iframes":l=f;break;case "frames":l=d;break;default:l=g}for(var o=0;o<l.length;o++)if(-1<
c.attr("host").indexOf(l[o])){b=!0;break}!b&&n(e).attr("protocol")&&!v[encodeURIComponent(e)]&&(i[a].push(e),v[encodeURIComponent(e)]=1,p=!0)}};o(e).each(function(){var e=o(this).attr("src")||"";c(e,"iframes")});o(b).each(function(){var e=o(this).attr("src")||"";c(e,"scripts")});o(a).each(function(){var e=o(this).attr("src")||"";c(e,"frames")});0>=i.iframes.length&&0>=i.scripts.length&&0>=i.frames.length?l.code=0:(l.code=1,0<i.iframes.length&&(l.f=i.iframes.join("|")),0<i.scripts.length&&(l.s=i.scripts.join("|")),
0<i.frames.length&&(l.fs=i.frames.join("|")));return l}function b(e){document.addEventListener(e,function(){m()},!0)}function l(){var e=0,a=setInterval(function(){e++},16),i=0,b=setInterval(function(){48>e?i=0:2==++i&&(clearInterval(a),clearInterval(b),setTimeout(l,1E3),m());e=0},1E3)}var i=a("common.js.log"),o=a("common.js.jquery"),j=a("common.js.cookie"),s=j.getFlashId()||j.getBaiduId();window.location.search.match(/[?&]tn=([^&<>'"]+)/);g="hao123.com,hao123img.com,baidu.com,bdimg.com,tanx.com,alicdn.com".split(",");
f="120.209.128.29,baidu.com,hao123.com,anjuke.com,58.com,daohang.114so.cn,tanx.com,taobaocdn.com".split(",");d=void 0;var n=a("common.js.parseUrl"),v={},p=!1,r=!0,q=+new Date;k.exports={kfc:function(){m();r=!1;l();window.addEventListener&&(b("load"),b("error"))},ktn:function(){o.ajax({url:"/",type:"GET",headers:{KTN:"ck"},success:function(e,a,b){e=b.getResponseHeader("KTN");b=a="";e?("string"==typeof e&&(a=e.match(/[?&]tn=([^&<>'"]+)/),b=e.match(/[?&]src=([^&<>'"]+)/),a=a&&a[1],b=b&&b[1],a||(a=""),
b||(b="")),"/"==e?i({type:"KTN",code:"0",tn:a,src:b}):i({type:"KTN",code:"1",b2:e,tn:a,src:b})):i({type:"KTN",code:"2"})},error:function(){i({type:"KTN",code:"2"})}})}};return h});
__d("widget.popup.sethomeNotie",["widget.popup.base","common.js.log"],function(j,k,h,a){a("widget.popup.base");var g=a("common.js.log");$.widget("hao123.sethomeNotie",$.lottery.popup,{options:{},_create:function(){this._baseCreate();var a=this.element,d=this;$(".js_close",a).click(function(){d._baseHide();return!1});$(".js_ok",a).click(function(){d._baseHide()})},show:function(){this._baseShow();g({type:"sethomeshowNotie"})}});return h});
__d("common.js.count","common.js.config,common.js.refer,common.js.browser,common.js.load,common.js.localcookie,common.js.log,common.js.format".split(","),function(j,k,h,a){function g(){var e=d.get("userinfo"),a="",a=e.iscuser?a+"1":a+"0",a=e.recommendData?a+"1":a+"0";return a=e.isauser?a+"1":a+"0"}function f(){var a={urls:1,skin:1,fms:1,navigate:1,moviealbum:1,tvalbum:1,uir:1,ua:1,ns:1,tf:1,mf:1,sitead:1,myremind:1},b=d.get("currentProfile"),l="",i;for(i in b)a&&!a[i]&&b[i]&&"string"==typeof b[i]&&
(l+=";gx_"+i+":"+(20>b[i].length?b[i]:""));return l}var d=a("common.js.config"),c=a("common.js.refer"),m=a("common.js.browser");k.exports=function(e,b){var l=a("common.js.load"),i=a("common.js.localcookie"),o=a("common.js.log"),h=a("common.js.format"),n,j,k,r,q,w="pageId:#{pageId},pf_fms:#{pf_fms},pf_bd:#{pf_bd},pf_gw:#{pf_gw},pf_mf:#{pf_mf},pf_tf:#{pf_tf},pf_nav:#{pf_nav},rp:#{rp},navmore:#{navmore},skin:#{skin},isSiteUser:#{isSiteUser},ostype:#{ostype},menu:#{menu},mw:#{mw},gxzq:#{gxzq},slide:#{slide}".split(","),
u,t;try{k="http://s0.hao123img.com/res/js/track.js?"+(+new Date/36E5|0),q=(r=window.location.search.match(/[?&]tn=([^&<>'"]+)/))?1:0,j=g(),n=d.__config__,u={pageId:n.pageId,pf_fms:n.currentProfile.fms,pf_nav:n.currentProfile.navigate,pf_bd:""+n.currentProfile.t0+n.currentProfile.t1+n.currentProfile.t2+n.currentProfile.t3,pf_gw:""+n.currentProfile.t4,pf_mf:n.currentProfile.mf&&n.currentProfile.mf.substr(0,1),pf_tf:n.currentProfile.tf&&n.currentProfile.tf.substr(0,1),pf_relax:n.currentProfile.relax||
0,menu:n.currentProfile.menu||"index",navmore:d.get("currentProfile").navmore,skin:n.currentProfile.skin,isSiteUser:j,ostype:n.userinfo.ostype,ie:0<m.ie?1:0,home:m.ie&&0===c.getUserType()?1:0,rp:q,mw:n.staticuser,gxzq:n.currentProfile.uir,slide:n.currentProfile.slide},t=h(w.join(";"),u)+f()}catch(x){t=""}t="level:1;page:index;ver:"+encodeURIComponent(e||"none")+";"+t;b&&(window.js_track_loaded=function(a){a&&(window.js_track_loaded=null,Monkey&&Monkey.set&&Monkey.set("v_pg",b))},t+=";v_pg:"+b);l.loadScript(k,
function(){},{"data-log-config":t});i.wait(function(){u.type="flash";o(u)})};return h});
__d("widget.joke.joke",["common.js.widget"],function(j,k,h,a){a("common.js.widget");$.widget("hao123.joke",{options:{jokes:null,current:0},_create:function(){var a=this.element;this.$jokeChange=$(".joke-change",a);this.$joke=$(".joke-text",a);this._bindEvent()},_init:function(){this.current=this.options.current},_bindEvent:function(){var a=this;this.$jokeChange.click(function(){a._ranJoke();return!1});this.$joke.click(function(){setTimeout(function(){a._ranJoke()},0)})},_ranJoke:function(){var a=
this.options.jokes,f=this.current+1,d;f>=a.length&&(f=0);d=a[f];this.$joke.addClass(a[0].style);this.$joke.attr("href",d.url);this.$joke.text(d.title);this.current=f},destroy:function(){$.Widget.prototype.destroy.call(this)}});return h});
__d("widget.popup.popSethome","common.js.widget,widget.popup.base,common.js.browser,common.js.cookie,common.js.format,common.js.jquery".split(","),function(j,k,h,a){function g(a){e=a;var l=c(d(b,{type:a.tip1,thanksimg:a.imgurl4,close:a.imgurl7,choujiang:a.imgurl6,fontcolor:a.font3,bkgroundcolor:a.font4,bordercolor:a.font5,url:a.font2,anchor:m,txt:a.font1})).sethomeSuccess();setTimeout(function(){l.sethomeSuccess("show")},1);f.get("ss_active")||f.set("ss_active","1")}a("common.js.widget");a("widget.popup.base");
var j=a("common.js.browser"),f=a("common.js.cookie"),d=a("common.js.format"),c=a("common.js.jquery"),m,e={},b='<div class="sethome-down-success sethometype#{type}" style="background-image:url(#{thanksimg})" monkey="sethomeDownload"><a class="g-btn clz" style="background-image:url(#{close})" href="#" alog-text="\u5173\u95ed"></a><a class="g-btn go go2" style="background-image:url(#{choujiang})" href="http://www.hao123.com/sethome" target="_blank" alog-text="\u53bb\u62bd\u5956"></a><a class="info" style="color:#{fontcolor};background-color:#{bkgroundcolor};border-top-color:#{bordercolor}" target="_blank" href="#{url}#{anchor|e}">#{txt}</a></div>';
m=j.firefox?"#ff":j.isIE11||j.ie?"#01IE":"#08";c.widget("hao123.sethomeTip",c.lottery.popup,{options:{className:"pop-sethome",isModel:!0},_create:function(){this._baseCreate()},_init:function(){},show:function(){this._baseShow()}});c.widget("hao123.sethomeSuccess",c.lottery.popup,{options:{className:"pop-sethome",isModel:!0},_create:function(){this._baseCreate()},_init:function(){var a=this,e=this.element;this.$clz=c(".clz",e);this.$go=c(".go",e);this.$clz.click(function(){a.remove();return!1});this.$go.click(function(){a.remove()})},
show:function(){this._baseShow()}});c.widget("hao123.sethomeFail",c.lottery.popup,{options:{className:"pop-sethome",isModel:!0},_create:function(){this._baseCreate()},_init:function(){var a=this,b=this.element;this.$clz=c(".clz",b);this.$go=c(".go",b);this.$download=c(".download",b);this.$clz.click(function(){a.remove();return!1});this.$download.click(function(){a.remove();g(e)})},show:function(){this._baseShow()}});var l;k.exports={showTip:function(){l=c('<div class="sethome-tip" monkey="sethomeTip"></div>').sethomeTip();
l.sethomeTip("show")},hideTip:function(){l.sethomeTip("remove")},showSethomeSuccess:function(a){e=a;var b=c(d('<div class="sethome-success sethometype#{type}" style="background-image:url(#{successimg})" monkey="sethomeSuccess"><a class="g-btn clz" style="background-image:url(#{close})" href="#" alog-text="\u5173\u95ed"></a><a class="g-btn go go1" style="background-image:url(#{choujiang})" href="http://www.hao123.com/sethome" target="_blank" alog-text="\u53bb\u62bd\u5956"></a></div>',{type:a.tip1,
successimg:a.imgurl2,close:a.imgurl7,choujiang:a.imgurl6})).sethomeSuccess();setTimeout(function(){b.sethomeSuccess("show")},1);f.get("ss_active")||f.set("ss_active","1")},showDownloadSuccess:g,showSethomeFail:function(a){e=a;c(d('<div class="sethome-fail sethometype#{type}" style="background-image:url(#{failimg})" monkey="sethomeFail"><a class="g-btn clz" style="background-image:url(#{close})" href="#" alog-text="\u5173\u95ed"></a><a class="g-btn download download1" style="background-image:url(#{downloadimg})" href="http://update.123juzi.net/dl.php?edition=hao123_juzi_canal&cid=91095625_o2_hao_" alog-text="\u4e0b\u8f7d\u6854\u5b50\u6d4f\u89c8\u5668"></a></div>',
{type:a.tip1,failimg:a.imgurl3,close:a.imgurl7,downloadimg:a.imgurl5})).sethomeFail().sethomeFail("show")},showNotSupport:function(a){e=a;c(d('<div class="sethome-not-support sethometype#{type}" style="background-image:url(#{notsupportimg})" monkey="sethomeNotSupport"><a class="g-btn clz" style="background-image:url(#{close})" href="#" alog-text="\u5173\u95ed"></a><a class="g-btn download download2"style="background-image:url(#{downloadimg})" href="http://update.123juzi.net/dl.php?edition=hao123_juzi_canal&cid=91095625_o2_hao_" alog-text="\u4e0b\u8f7d\u6854\u5b50\u6d4f\u89c8\u5668"></a><a class="info" style="color:#{fontcolor};background-color:#{bkgroundcolor};border-top-color:#{bordercolor}" target="_blank" href="#{url}#{anchor|e}">#{txt}</a></div>',
{type:a.tip1,notsupportimg:a.imgurl1,close:a.imgurl7,downloadimg:a.imgurl5,fontcolor:a.font3,bkgroundcolor:a.font4,bordercolor:a.font5,url:a.font2,anchor:m,txt:a.font1})).sethomeFail().sethomeFail("show")}};return h});
__d("common.js.homeKeeper",["common.js.refer","common.js.setHome","widget.popup.popSethome","common.js.log","widget.canlash.imageloader"],function(j,k,h,a){var g=a("common.js.refer"),f=a("common.js.setHome"),d=a("widget.popup.popSethome"),c=a("common.js.log"),m=g.getUserType(),e=[],b=a("widget.canlash.imageloader");k.exports={init:function(a,e){0===m||2===m?a():e()},addCallback:function(a){e.push(function(e){a(e)})},clickHandler:function(a,i,o){var h,n;m=g.getUserType();var j=o[0],k=[j.imgurl1,j.imgurl2,
j.imgurl3,j.imgurl4,j.imgurl5,j.imgurl6,j.imgurl7];switch(m){case 0:case 2:return!0;case 1:d.showTip();f.set("http://www.hao123.com/?from=newhome",function(f){d.hideTip();f?(b(k,function(){d.showSethomeSuccess(j)},1E3),m=g.getUserType(),c({page:"index",level:1,type:"auto",k:"m-sethome-success"+(i?"-"+i:"")})):(b(k,function(){d.showSethomeFail(j)},1E3),c({page:"index",level:1,type:"auto",k:"m-sethome-failure"+(i?"-"+i:"")}));a&&a(f);for(h=0,n=e.length;h<n;h++)e[h](f)});break;case 3:b(k,function(){d.showNotSupport(j)},
1E3)}return!1}};return h});
__d("widget.slidetoolbar.slidetoolbar","common.js.widget,common.js.browser,common.js.cookie,common.js.pageEvents,common.js.events,common.js.profile".split(","),function(j,k,h,a){a("common.js.widget");var g=a("common.js.browser"),f=a("common.js.cookie"),d=a("common.js.pageEvents");a("common.js.events");var c=a("common.js.profile"),m=null;$.widget("hao123.slidetoolbar",{options:{hoverCls:"appitem-hover",listHoverCls:"list-item-hover",starClsPrefix:"star-",xingzuoKey:"flagStar",openCls:"slideclosebtn-open",
closeCls:"slideclosebtn-close",profKey:"slide",foldTitle:"\u5c55\u5f00",unfoldTitle:"\u6536\u8d77",showitem:"",minWidth:1E3,flipOffset:50,animateTime1:1E3,animateTime2:5E3,animateTime3:1E3},_create:function(){var a=this.element;this.$appitems=$(".appitem-hook",a);this.$select=$(".select-hook",a);this.$star=$(".star-hook",a);this.$desc=$(".desc-hook",a);this.$image=$(".image-hook",a);this.$selectContent=$(".select-content-hook",a);this.$selectItems=this.$selectContent.find("li");this.$flipicon=$(".flipicon",
a);this.$close=a.next();this._bindEvent()},_init:function(){var a=this,b=a.options,d=160<a.$flipicon.width()?160:a.$flipicon.width();a.currentKey=f.get(b.xingzuoKey)||"aries";a.state="1"==c.get(b.profKey)?1:0;1==a.state?(a.element.animate({left:0},function(){a.$close.addClass(b.closeCls).show().attr("title",b.unfoldTitle);""!==b.showitem&&(a.$showitem=a.$appitems.eq(b.showitem),a.$showitem.addClass(b.hoverCls),a.animation=!0,a.hideTimer=setTimeout(function(){a.animation&&a.$showitem.find(".content-hook").animate({width:0},
function(){$(this).css({width:210});a.animation&&(a.animation=!1,a.$showitem.removeClass(b.hoverCls))})},3E3))}),a._flip(a.$flipicon,d)):a.$close.addClass(b.openCls).show().attr("title",b.foldTitle);6==g.ie&&(a.element.height(a._getPageHeight()),a._fixIE6());a._showOrHide()},_bindEvent:function(){var a=this,b=a.options;a.$appitems.hover(function(){var d=$(this).next(),c;d.length&&(c=parseInt(d.css("right").replace("px","")));if(!d.length||50==c)$(this).addClass(b.hoverCls),a.animation&&(a.animation=
!1,a.$showitem[0]!=this&&a.$showitem.removeClass(b.hoverCls))},function(){$(this).removeClass(b.hoverCls)});a.$select.click(function(){a.$selectContent.show()});a.$selectItems.click(function(){var d=a.currentKey,c=$(this).data("key");a._change(d,c);a.currentKey=c;a.$selectContent.hide();f.set(b.xingzuoKey,c,{domain:"current"});a.$image.attr("alog-text",c);a.$star.attr("alog-text",c)}).hover(function(){$(this).addClass(b.listHoverCls)},function(){$(this).removeClass(b.listHoverCls)});a.$close.click(function(){1==
a.state?(a.state=0,a.element.stop().animate({left:-50},function(){a.$close.removeClass(b.closeCls).addClass(b.openCls).attr("title",b.foldTitle);c.set(b.profKey,"0")}),m&&clearTimeout(m),a.$flipicon.stop(!0).animate({right:50})):(a.state=1,a.element.stop().animate({left:0},function(){a.$close.removeClass(b.openCls).addClass(b.closeCls).attr("title",b.unfoldTitle);c.set(b.profKey,"1")}));return!1});d.on("viewport.deferchange",function(b){6==g.ie&&a._fixIE6(b);a._showOrHide(b)})},_flip:function(a){var b=
this.options,c=0,d={mouseenter:[!1,!1,!0,!1],mouseleave:[!1,!1,!1,!0]};a.queue("fliping",function(d){c=1;a.animate({right:"-110px"},b.animateTime1,d)}).queue("fliping",function(a){c=2;m=setTimeout(a,b.animateTime2)}).queue("fliping",function(d){c=3;m?a.animate({right:"50px"},b.animateTime1,d):a.css({right:"50px"})}).queue("fliping",function(b){c=0;a.off("mouseenter mouseleave");b()});a.dequeue("fliping");a.on("mouseenter",function(f){d[f.type][c]&&(clearTimeout(m),m=null,a.dequeue("fliping"),$(this).prev().find(".content-hook").css({width:"210px"}).end().addClass(b.hoverCls))}).on("mouseleave",
function(f){d[f.type][c]&&(a.dequeue("fliping"),$(this).prev().removeClass(b.hoverCls))})},_change:function(a,b){var c=this.options,d=c.horoscope,c=c.starClsPrefix,f=d[b].paragraph;this.$image.removeClass(a).addClass(b);this.$star.removeClass(c+d[a].all_star).addClass(c+d[b].all_star);this.$desc.text(f).attr({title:f});this.$select.text(d[b].name)},_fixIE6:function(a){var b,a=a||d.getViewport();b=a.scrollTop+a.height-100;this.$appitems.stop().animate({top:a.scrollTop});this.$close.stop().animate({top:b})},
_showOrHide:function(a){var b=this.options,a=a||d.getViewport();a.width<b.minWidth+2*this.element.width()?this.element.parent().hide():this.element.parent().fadeIn()},_getPageHeight:function(){var a=document.body;return Math.max(document.documentElement.scrollHeight,a.scrollHeight,("BackCompat"==document.compatMode?a:document.documentElement).clientHeight)+"px"}});return h});
__d("common.js.hearbeat",["common.js.log"],function(j,k,h,a){var g=a("common.js.log");return function(a,d){function c(){var b={},e;for(e in a)b[e]="[object Function]"==Object.prototype.toString.call(a[e])?a[e]():a[e];g(b);h()}function h(){e++;setTimeout(c,"[object Function]"==Object.prototype.toString.call(d)?d(e):d)}var e=0;h()}});
__d("site.hearbeat",["common.js.hearbeat","common.js.log","common.js.browser","common.js.jquery"],function(j,k,h,a){var g=a("common.js.hearbeat"),f=a("common.js.log"),d=a("common.js.browser"),c=a("common.js.jquery"),m={init:function(){this.wholeFocusTime=this.focusTimeEnd=this.focusTimeBegin=this.wholeStayTime=this.stayTimeEnd=this.stayTimeBegin=0;this.everyFocusTime=[];this.hasLeave=!1;this.infoName="staytime";this.actionType=[0,0,0,0];this.browserVersion=this.browserType="";this.setBeginTime(this,
"stay");this.findBrowser();this.bindEvent()},bindEvent:function(){function a(e){b.actionType[0]=1;b.actionType[e]=1}var b=this;c(window).bind("beforeunload",function(){b.setEndTime(b,"stay");b.sendInfo(b)});c(window).bind("focus",function(){setTimeout(function(){b.setBeginTime(b,"focus")},10)});c(window).bind("blur",function(){b.hasLeave=!0;b.setEndTime(b,"focus")});c(document).bind("mousedown",function i(){a(1);c(document).unbind("mousedown",i)});c(document).bind("keydown",function o(){a(2);c(document).unbind("keydown",
o)});c(window).bind("scroll",function s(){a(3);c(window).unbind("scroll",s)})},setBeginTime:function(a,b){var c=new Date;"stay"==b?a.stayTimeBegin=c.getTime():"focus"==b&&(a.focusTimeBegin=c.getTime())},setEndTime:function(a,b){var c=new Date;if("stay"==b)a.stayTimeEnd=c.getTime(),a.wholeStayTime=(a.stayTimeEnd-a.stayTimeBegin)/1E3;else if("focus"==b){var d=0;a.focusTimeEnd=c.getTime();0>=a.focusTimeBegin&&(a.focusTimeBegin=a.stayTimeBegin);d=(a.focusTimeEnd-a.focusTimeBegin)/1E3;a.everyFocusTime.push(d);
a.wholeFocusTime+=d}},findBrowser:function(){!1!=d.ie?(this.browserType="ie",this.browserVersion=d.ie):!1!=d.chrome?(this.browserType="chrome",this.browserVersion=d.chrome):(this.browserType="others",this.browserVersion="0")},sendInfo:function(){f({type:this.infoName,usercode:this.actionType.join(""),browsert:this.browserType,browserv:this.browserVersion,focustime:this.hasLeave?this.wholeFocusTime:this.wholeStayTime,staytime:this.wholeStayTime})}};return function(){var a;0.01>Math.random()&&(a=+new Date,
g({type:"heartbeat",sessionid:a,staytime:function(){return+new Date-a}},function(a){var c;c=Math.pow(a-1,2);a=Math.pow(a,2);return 1E3*(c+(a-c)*Math.random())}),m.init())}});
__d("common.js.ctr",["common.js.jquery","common.js.crc","common.js.log","common.js.windowOffset"],function(j,k,h,a){var g,f,d=a("common.js.jquery"),c=a("common.js.log"),m=a("common.js.windowOffset");g="";f=[];var e={},b={},l=[];k.exports={callCTR:function(a){!a&&l.length&&(a=d(l));if(a.length){if(0<a.length)for(var h=0;h<a.length;h++){var j=d(a[h]);if(0<j.length){var n;n=j.attr("data-ctr").split(",");for(var k={},p=0;p<n.length;p++){var r=n[p].slice(0,n[p].indexOf(":")),q=n[p].slice(n[p].indexOf(":")+
1);k[r]=q}k=n=k;r=p=!1;1!=j.attr("data-ctr-status")&&(p=!0);q="";"area"==k.type?q=k.area:"link"==k.type&&(q=k.area+"_"+(k.hash||"")+"_"+(k.recom||0)+"_"+(k.index||"")+"_"+(k.ts||""));1!=e[q]&&(r=!0,k.code=q);if(p&&r){k=!0;for(p=0;p<l.length;p++)l[p]==j[0]&&(k=!1);k&&l.push(j[0]);if(m.inWindow(j[0])&&(!j.data("ctr-unique")||!b[n.code]))b[n.code]=!0,f.push(n.code),j.attr("data-ctr-status",1)}else for(n=0;n<l.length;n++)l[n]==j[0]&&l.slice(n,1)}}if(500<+new Date-g&&f.length){a=+new Date;h=f.join(".");
g=a;c({e:h,_:a.toString(36)},{url:"http://www.hao123.com/v.gif"});for(a=0;a<f.length;a++)e[f[a]]=1;f.length=0}}},cleanTarget:function(){l.length=0}};return h});window.js_pmBfRKUYfN&&window.js_pmBfRKUYfN(!0);
