/* JS */ gapi.loaded_0(function(_){var window=this;
var sa,ua;_.q=function(a){return function(){return _.da[a].apply(this,arguments)}};_._DumpException=function(a){throw a;};_.da=[];_.ea=_.ea||{};_.r=this;_.ia=function(a){return void 0!==a};
_.ja=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.ma=function(a){return"array"==_.ja(a)};_.t=function(a){return"string"==typeof a};_.pa="closure_uid_"+(1E9*Math.random()>>>0);sa=function(a,b,c){return a.call.apply(a.bind,arguments)};
ua=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.u=function(a,b,c){_.u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?sa:ua;return _.u.apply(null,arguments)};
_.va=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.wa=Date.now||function(){return+new Date};_.A=function(a,b){var c=a.split("."),d=_.r;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&_.ia(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}};
_.D=function(a,b){function c(){}c.prototype=b.prototype;a.S=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Cw=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};
_.xa=function(a,b){return b};_.E=function(a,b){b=_.xa(a,b);_.A(a,b)};_.ya=window.gadgets||{};_.Ba=window.osapi=window.osapi||{};_.google=window.google||{};window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:!1,rms:"migrated"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},udc_webconsentflow:{url:"https://myaccount.google.com/webconsent?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,"pos.plusones.getSignupState":!0},
requestCache:{enabled:!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:!0},transport:{isProxyShared:!0},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4}});
_.Da=window;_.Fa=window.document;_.Ga=_.Da.location;_.Ha=/\[native code\]/;_.Ja=function(a,b,c){return a[b]=a[b]||c};_.Ka=function(){var a;if((a=Object.create)&&_.Ha.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.Ma=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.Oa=function(a,b){if(!a)throw Error(b||"");};_.Ra=_.Ja(_.Da,"gapi",{});
_.Ta=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(e){}return c};_.Xa=function(a,b,c){_.Ua(a,b,c,"add","at")};_.Ua=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.Ya=_.Ja(_.Da,"___jsl",_.Ka());_.Ja(_.Ya,"I",0);_.Ja(_.Ya,"hel",10);var $a,ab,bb,cb,db,fb;$a=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};ab=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};bb=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};cb=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&(a[c]&&b[c]&&"object"===typeof a[c]&&"object"===typeof b[c]&&!bb(a[c])&&!bb(b[c])?cb(a[c],b[c]):b[c]&&"object"===typeof b[c]?(a[c]=bb(b[c])?[]:{},cb(a[c],b[c])):a[c]=b[c])};
db=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var b;try{b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return"object"===typeof b?b:{}}};
fb=function(a){ab(!0);var b=window.___gcfg,c=$a("cu");if(b&&b!==window.___gu){var d={};cb(d,b);c.push(d);window.___gu=b}var b=$a("cu"),e=window.document.scripts||window.document.getElementsByTagName("script")||[],d=[],f=[];f.push.apply(f,$a("us"));for(var g=0;g<e.length;++g)for(var k=e[g],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",
!0),(f=d[e])?(g=f.nodeType,f=3==g||4==g?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=db(f))&&b.push(f));a&&(d={},cb(d,a),c.push(d));d=$a("cd");a=0;for(b=d.length;a<b;++a)cb(ab(),d[a]);d=$a("ci");a=0;for(b=d.length;a<b;++a)cb(ab(),d[a]);a=0;for(b=c.length;a<b;++a)cb(ab(),c[a])};_.I=function(a,b){if(!a)return ab();for(var c=a.split("/"),d=ab(),e=0,f=c.length;d&&"object"===typeof d&&e<f;++e)d=d[c[e]];return e===c.length&&void 0!==d?d:b}; _.gb=function(a,b){var c=a;if("string"===typeof a){for(var d=c={},e=a.split("/"),f=0,g=e.length;f<g-1;++f)var k={},d=d[e[f]]=k;d[e[f]]=b}fb(c)};
var ib=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.Ja(_.Ya,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};ib&&ib();fb();_.E("gapi.config.get",_.I);_.E("gapi.config.update",_.gb);
var nb,ob,qb,rb,sb,tb,ub,vb,wb,yb,zb,Ab,Db,Eb,Ib;_.kb=function(a){return!!a&&"object"===typeof a&&_.Ha.test(a.push)};_.lb=function(a,b,c){if(a){_.Oa(_.kb(a),"arrayForEach was called with a non array value");for(var d=0;d<a.length;d++)b.call(c,a[d],d)}};_.mb=function(a,b,c){if(a)if(_.kb(a))_.lb(a,b,c);else{_.Oa("object"===typeof a,"objectForEach was called with a non object value");c=c||a;for(var d in a)_.Ma(a,d)&&void 0!==a[d]&&b.call(c,a[d],d)}};
nb=function(a){a=a.sort();for(var b=[],c=void 0,d=0;d<a.length;d++){var e=a[d];e!=c&&b.push(e);c=e}return b};ob=function(){var a=[],b=_.Ya.H;b&&_.mb(b,function(b){a.push.apply(a,b.L)});return nb(a)};_.pb=function(a){if(_.Ha.test(Object.keys))return Object.keys(a);var b=[],c;for(c in a)_.Ma(a,c)&&b.push(c);return b};vb={};wb=0;yb=_.Ka();zb=_.Ka();Ab=function(a){return"number"===typeof a&&a>Math.random()};
_.Cb=function(a){if("undefined"===typeof qb){var b=_.I("report")||{},c=b.rate;tb=b.timeout||1E3;rb=b.host||"https://plus.google.com";sb=b.path||"/_/widget/report";qb=[];Ab(c)&&(qb=b.apis||[]);var b=b.apiRate||{},d;for(d in b)Ab(b[d])&&qb.push(d)}for(d=0;d<qb.length;++d)if((new RegExp("^"+qb[d]+"$")).test(a))return!0;return!1};Db=function(a){delete vb[a]};
Eb=function(){ub&&(_.Da.clearTimeout(ub),ub=0);ub=_.Da.setTimeout(function(){var a;a=window.document.location;a=a.protocol+"//"+a.host+a.pathname;var b=_.pb(zb).join(":");a=[rb,sb,"?api=",(0,window.encodeURIComponent)(b),"&url=",(0,window.encodeURIComponent)(a),"&loaded=",(0,window.encodeURIComponent)(ob().join(":"))].join("");zb=_.Ka();var b=new window.Image,c=wb++;vb[c]=b;b.onload=b.onerror=_.va(Db,c);b.src=a;ub=0},tb)};_.Gb=function(a){yb[a]||(zb[a]=!0,yb[a]=!0,Eb())};Ib=_.xa; _.xa=function(a,b){var c=Ib(a,b);"function"===typeof b&&_.Cb(a)&&(c=function(c){_.Gb(a);return b.apply(this,arguments)});return c};

_.bj=window.googleapis&&window.googleapis.server||{};
var Tb={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},Ub=function(a){var b,c,d;b=/[\"\\\x00-\x1f\x7f-\x9f]/g;if(void 0!==a){switch(typeof a){case "string":return b.test(a)?'"'+a.replace(b,function(a){var b=Tb[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?String(a):"null";case "boolean":case "null":return String(a);case "object":if(!a)return"null";b=[];if("number"===
typeof a.length&&!a.propertyIsEnumerable("length")){d=a.length;for(c=0;c<d;c+=1)b.push(Ub(a[c])||"null");return"["+b.join(",")+"]"}for(c in a)!/___$/.test(c)&&_.Ma(a,c)&&"string"===typeof c&&(d=Ub(a[c]))&&b.push(Ub(c)+":"+d);return"{"+b.join(",")+"}"}return""}},Vb=function(a){if(!a)return!1;if(/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}return!1}, Wb=!1,Xb;try{Wb=!!window.JSON&&'["a"]'===window.JSON.stringify(["a"])&&"a"===window.JSON.parse('["a"]')[0]}catch(a){}Xb=function(a){try{return window.JSON.parse(a)}catch(b){return!1}};_.Yb=Wb?window.JSON.stringify:Ub;_.ac=Wb?Xb:Vb;

_.Rj=function(){var a=/\s*;\s*/;return{get:function(b,c){for(var d=b+"=",e=(window.document.cookie||"").split(a),f=0,g;g=e[f];++f)if(0==g.indexOf(d))return g.substr(d.length);return c}}}();
_.Mb=function(){function a(a,b){if(!(a<c)&&d)if(2===a&&d.warn)d.warn(b);else if(3===a&&d.error)try{d.error(b)}catch(g){}else d.log&&d.log(b)}var b=function(b){a(1,b)};_.Kb=function(b){a(2,b)};_.Jb=function(b){a(3,b)};_.Lb=function(){};b.INFO=1;b.WARNING=2;b.NONE=4;var c=1,d=window.console?window.console:window.opera?window.opera.postError:void 0;return b}();

_.K=_.K||{};
_.K=_.K||{};(function(){var a=[];_.K.yX=function(b){a.push(b)};_.K.LX=function(){for(var b=0,c=a.length;b<c;++b)a[b]()}})();
_.Nb=function(a,b){var c=_.Ja(_.Ya,"watt",_.Ka());_.Ja(c,a,b)};_.K=_.K||{};
(function(){var a=null;_.K.Ub=function(b){var c="undefined"===typeof b;if(null!==a&&c)return a;var d={};b=b||window.location.href;var e=b.indexOf("?"),f=b.indexOf("#");b=(-1===f?b.substr(e+1):[b.substr(e+1,f-e-1),"&",b.substr(f+1)].join("")).split("&");for(var e=window.decodeURIComponent?window.decodeURIComponent:window.unescape,f=0,g=b.length;f<g;++f){var k=b[f].indexOf("=");if(-1!==k){var l=b[f].substring(0,k),k=b[f].substring(k+1),k=k.replace(/\+/g," ");try{d[l]=e(k)}catch(m){}}}c&&(a=d);return d}; _.K.Ub()})();
_.E("gadgets.util.getUrlParameters",_.K.Ub);
_.Ob=window.console;_.Pb=function(a){_.Ob&&_.Ob.log&&_.Ob.log(a)};_.Rb=function(){};
_.Sb=function(){var a=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;a&&_.gb(a());return{register:function(a,c,d){d&&d(_.I())},get:function(a){return _.I(a)},update:function(a,c){if(c)throw"Config replacement is not supported";_.gb(a)},Rb:function(){}}}();
_.E("gadgets.config.register",_.Sb.register);_.E("gadgets.config.get",_.Sb.get);_.E("gadgets.config.init",_.Sb.Rb);_.E("gadgets.config.update",_.Sb.update);
_.E("gadgets.json.stringify",_.Yb);_.E("gadgets.json.parse",_.ac);_.Ta(_.Da.location.href,"rpctoken")&&_.Xa(_.Fa,"unload",function(){});
var bc,ec;bc=function(){var a=_.Fa.readyState;return"complete"===a||"interactive"===a&&-1==window.navigator.userAgent.indexOf("MSIE")};_.cc=function(a){if(bc())a();else{var b=!1,c=function(){if(!b)return b=!0,a.apply(this,arguments)};_.Da.addEventListener?(_.Da.addEventListener("load",c,!1),_.Da.addEventListener("DOMContentLoaded",c,!1)):_.Da.attachEvent&&(_.Da.attachEvent("onreadystatechange",function(){bc()&&c.apply(this,arguments)}),_.Da.attachEvent("onload",c))}};_.dc=function(a,b){if(!bc())try{a()}catch(c){}_.cc(b)}; ec=ec||{};ec.mB=null;ec.Yz=null;ec.Pn=null;ec.frameElement=null;
ec=ec||{};
ec.Iu||(ec.Iu=function(){function a(a){"undefined"!=typeof window.addEventListener?window.addEventListener("message",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onmessage",a);window.___jsl=window.___jsl||{};var b=window.___jsl;b.RPMQ=b.RPMQ||[];b.RPMQ.push(a)}function b(a){var b=(0,_.ac)(a.data);if(b&&b.f){(0,_.Lb)("gadgets.rpc.receive("+window.name+"): "+a.data);var d=_.L.vg(b.f);e&&("undefined"!==typeof a.origin?a.origin!==d:a.domain!==/^.+:\/\/([^:]+).*/.exec(d)[1])?_.Jb("Invalid rpc message origin. "+
d+" vs "+(a.origin||"")):c(b,a.origin)}}var c,d,e=!0;return{Hi:function(){return"wpm"},I:function(){return!0},Rb:function(f,g){_.Sb.register("rpc",null,function(a){"true"===String((a&&a.rpc||{}).disableForceSecure)&&(e=!1)});c=f;d=g;a(b);d("..",!0);return!0},Ob:function(a){d(a,!0);return!0},call:function(a,b,c){var d=_.L.vg(a),e=_.L.nw(a);d?window.setTimeout(function(){var a=(0,_.Yb)(c);(0,_.Lb)("gadgets.rpc.send("+window.name+"): "+a);e.postMessage(a,d)},0):".."!=a&&_.Jb("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message"); return!0}}}());
ec=ec||{};
ec.Um||(ec.Um=function(){function a(a,b){G[b]=G[b]||function(){a.apply({},arguments)}}function b(){if(null===v&&window.document.body&&l){var a=l+"?cb="+Math.random()+"&origin="+B+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="___xpcswf" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+a+
'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;v=c.firstChild}++x;null!==w&&(null!==v||50<=x)?window.clearTimeout(w):w=window.setTimeout(b,100)}function c(){H[".."]||(k(".."),y++,50<=y&&null!==C?(window.clearTimeout(C),C=null):C=window.setTimeout(c,100))}function d(){if(null!==v&&v.setup)for(;0<z.length;){var a=z.shift(),b=a.CN;v.setup(a.wj,".."===b?_.L.Kp:b,".."===b?"INNER":"OUTER")}null!==w&&window.clearTimeout(w);w=null}function e(){H[".."]||null!==
C||(C=window.setTimeout(c,100))}function f(a,b,c){b=_.L.vg(a);var d=_.L.lh(a);v["sendMessage_"+(".."===a?_.L.Kp:a)+"_"+d+"_"+(".."===a?"INNER":"OUTER")].call(v,(0,_.Yb)(c),b);return!0}function g(a,b){var c=(0,_.ac)(a),d=c._scr;d?(p(d,!0),H[d]=!0,".."!==d&&k(d,!0)):window.setTimeout(function(){n(c,b)},0)}function k(a,b){var c=_.L.Kp,d={};d._scr=b?"..":c;d._pnt=c;f(a,0,d)}var l=null,m=!1,n=null,p=null,v=null,z=[],w=null,x=0,y=0,C=null,H={},B=window.location.protocol+"//"+window.location.host,G;window.___jsl=
window.___jsl||{};G=window.___jsl._fm={};_.Sb.register("rpc",null,function(a){m&&(l=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});a(d,"ready");a(e,"setupDone");a(g,"receiveMessage");return{Hi:function(){return"flash"},I:function(){return!0},Rb:function(a,b){n=a;p=b;return m=!0},Ob:function(a,c){z.push({wj:c,CN:a});null===v&&null===w&&(w=window.setTimeout(b,100));return!0},call:f,WF:g,J:d,K:e}}());
if(window.gadgets&&window.gadgets.rpc)"undefined"!=typeof _.L&&_.L||(_.L=window.gadgets.rpc,_.L.config=_.L.config,_.L.register=_.L.register,_.L.unregister=_.L.unregister,_.L.aB=_.L.registerDefault,_.L.DC=_.L.unregisterDefault,_.L.tx=_.L.forceParentVerifiable,_.L.call=_.L.call,_.L.Dk=_.L.getRelayUrl,_.L.If=_.L.setRelayUrl,_.L.Qo=_.L.setAuthToken,_.L.Cl=_.L.setupReceiver,_.L.lh=_.L.getAuthToken,_.L.wt=_.L.removeReceiver,_.L.Zx=_.L.getRelayChannel,_.L.Jo=_.L.receive,_.L.XA=_.L.receiveSameDomain,_.L.Wa=
_.L.getOrigin,_.L.vg=_.L.getTargetOrigin,_.L.nw=_.L._getTargetWin,_.L.VF=_.L._parseSiblingId);else{_.L=function(){function a(a,b){if(!ba[a]){var c=qa;b||(c=O);ba[a]=c;for(var d=fa[a]||[],e=0;e<d.length;++e){var f=d[e];f.t=H[a];c.call(a,f.f,f)}fa[a]=[]}}function b(){function a(){la=!0}ta||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",a,!1):"undefined"!=typeof window.attachEvent&&window.attachEvent("onunload",a),ta=!0)}function c(a,c,d,e,f){H[c]&&H[c]===d||(_.Jb("Invalid gadgets.rpc token. "+
H[c]+" vs "+d),ka(c,2));f.onunload=function(){J[c]&&!la&&(ka(c,1),_.L.wt(c))};b();e=(0,_.ac)((0,window.decodeURIComponent)(e))}function d(b,c){if(b&&"string"===typeof b.s&&"string"===typeof b.f&&b.a instanceof Array)if(H[b.f]&&H[b.f]!==b.t&&(_.Jb("Invalid gadgets.rpc token. "+H[b.f]+" vs "+b.t),ka(b.f,2)),"__ack"===b.s)window.setTimeout(function(){a(b.f,!0)},0);else{b.c&&(b.callback=function(a){_.L.call(b.f,(b.g?"legacy__":"")+"__cb",null,b.c,a)});if(c){var d=e(c);b.origin=c;var f=b.r,g;try{g=e(f)}catch(k){}f&&
g==d||(f=c);b.referer=f}d=(x[b.s]||x[""]).apply(b,b.a);b.c&&"undefined"!==typeof d&&_.L.call(b.f,"__cb",null,b.c,d)}}function e(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a)throw Error("b");
var c="",d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1),b=b.substring(0,d);if("http"===a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c}function f(a){if("/"==a.charAt(0)){var b=a.indexOf("|");return{id:0<b?a.substring(1,b):a.substring(1),origin:0<b?a.substring(b+1):null}}return null}function g(a){if("undefined"===typeof a||".."===a)return window.parent;var b=f(a);if(b)return window.top.frames[b.id];a=String(a);return(b=window.frames[a])?b:(b=window.document.getElementById(a))&&b.contentWindow?
b.contentWindow:null}function k(a,b){if(!0!==J[a]){"undefined"===typeof J[a]&&(J[a]=0);var c=g(a);".."!==a&&null==c||!0!==qa.Ob(a,b)?!0!==J[a]&&10>J[a]++?window.setTimeout(function(){k(a,b)},500):(ba[a]=O,J[a]=!0):J[a]=!0}}function l(a){(a=y[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a}function m(a,b,c){b&&!/http(s)?:\/\/.+/.test(b)&&(0==b.indexOf("//")?b=window.location.protocol+
b:"/"==b.charAt(0)?b=window.location.protocol+"//"+window.location.host+b:-1==b.indexOf("://")&&(b=window.location.protocol+"//"+b));y[a]=b;"undefined"!==typeof c&&(C[a]=!!c)}function n(a,b){b=b||"";H[a]=String(b);k(a,b)}function p(a){a=(a.passReferrer||"").split(":",2);ha=a[0]||"none";oa=a[1]||"origin"}function v(b){"true"===String(b.useLegacyProtocol)&&(qa=ec.Pn||O,qa.Rb(d,a))}function z(a,b){function c(d){d=d&&d.rpc||{};p(d);var f=d.parentRelayUrl||"",f=e(aa.parent||b)+f;m("..",f,"true"===String(d.useLegacyProtocol));
v(d);n("..",a)}!aa.parent&&b?c({}):_.Sb.register("rpc",null,c)}function w(a,b,c){if(".."===a)z(c||aa.rpctoken||aa.ifpctok||"",b);else a:{var d=null;if("/"!=a.charAt(0)){if(!_.K)break a;d=window.document.getElementById(a);if(!d)throw Error("c`"+a);}d=d&&d.src;b=b||_.L.Wa(d);m(a,b);b=_.K.Ub(d);n(a,c||b.rpctoken)}}var x={},y={},C={},H={},B=0,G={},J={},aa={},ba={},fa={},ha=null,oa=null,W=window.top!==window.self,Ea=window.name,ka=function(){},za=window.console,jb=za&&za.log&&function(a){za.log(a)}||function(){},
O=function(){function a(b){return function(){jb(b+": call ignored")}}return{getCode:function(){return"noop"},isParentVerifiable:function(){return!0},init:a("init"),setup:a("setup"),call:a("call")}}();_.K&&(aa=_.K.Ub());var la=!1,ta=!1,qa=function(){if("flash"==aa.rpctx)return ec.Um;if("rmr"==aa.rpctx)return ec.mB;var a="function"===typeof window.postMessage?ec.Iu:"object"===typeof window.postMessage?ec.Iu:window.ActiveXObject?ec.Um?ec.Um:ec.Yz?ec.Yz:ec.Pn:0<window.navigator.userAgent.indexOf("WebKit")?
ec.mB:"Gecko"===window.navigator.product?ec.frameElement:ec.Pn;a||(a=O);return a}();x[""]=function(){jb("Unknown RPC service: "+this.s)};x.__cb=function(a,b){var c=G[a];c&&(delete G[a],c.call(this,b))};return{config:function(a){"function"===typeof a.tB&&(ka=a.tB)},register:function(a,b){if("__cb"===a||"__ack"===a)throw Error("d");if(""===a)throw Error("e");x[a]=b},unregister:function(a){if("__cb"===a||"__ack"===a)throw Error("f");if(""===a)throw Error("g");delete x[a]},aB:function(a){x[""]=a},DC:function(){delete x[""]},
tx:function(){},call:function(a,b,c,d){a=a||"..";var e="..";".."===a?e=Ea:"/"==a.charAt(0)&&(e=_.L.Wa(window.location.href),e="/"+Ea+(e?"|"+e:""));++B;c&&(G[B]=c);var g={s:b,f:e,c:c?B:0,a:Array.prototype.slice.call(arguments,3),t:H[a],l:!!C[a]},k;a:if("bidir"===ha||"c2p"===ha&&".."===a||"p2c"===ha&&".."!==a){k=window.location.href;var l="?";if("query"===oa)l="#";else if("hash"===oa)break a;l=k.lastIndexOf(l);l=-1===l?k.length:l;k=k.substring(0,l)}else k=null;k&&(g.r=k);if(".."===a||null!=f(a)||window.document.getElementById(a))(k=
ba[a])||null===f(a)||(k=qa),0===b.indexOf("legacy__")&&(k=qa,g.s=b.substring(8),g.c=g.c?g.c:B),g.g=!0,g.r=e,k?(C[a]&&(k=ec.Pn),!1===k.call(a,e,g)&&(ba[a]=O,qa.call(a,e,g))):fa[a]?fa[a].push(g):fa[a]=[g]},Dk:l,If:m,Qo:n,Cl:w,lh:function(a){return H[a]},wt:function(a){delete y[a];delete C[a];delete H[a];delete J[a];delete ba[a]},Zx:function(){return qa.Hi()},Jo:function(a,b){4<a.length?qa.WF(a,d):c.apply(null,a.concat(b))},XA:function(a){a.a=Array.prototype.slice.call(a.a);window.setTimeout(function(){d(a)},
0)},Wa:e,vg:function(a){var b=null,c=l(a);c?b=c:(c=f(a))?b=c.origin:b=".."==a?aa.parent:window.document.getElementById(a).src;return e(b)},Rb:function(){!1===qa.Rb(d,a)&&(qa=O);W?w(".."):_.Sb.register("rpc",null,function(a){a=a.rpc||{};p(a);v(a)})},nw:g,VF:f,I:"__ack",Kp:Ea||"..",M:0,K:1,J:2}}();_.L.Rb()};
_.L.config({tB:function(a){throw Error("h`"+a);}});_.Lb=_.Rb;_.E("gadgets.rpc.config",_.L.config);_.E("gadgets.rpc.register",_.L.register);_.E("gadgets.rpc.unregister",_.L.unregister);_.E("gadgets.rpc.registerDefault",_.L.aB);_.E("gadgets.rpc.unregisterDefault",_.L.DC);_.E("gadgets.rpc.forceParentVerifiable",_.L.tx);_.E("gadgets.rpc.call",_.L.call);_.E("gadgets.rpc.getRelayUrl",_.L.Dk);_.E("gadgets.rpc.setRelayUrl",_.L.If);_.E("gadgets.rpc.setAuthToken",_.L.Qo);_.E("gadgets.rpc.setupReceiver",_.L.Cl);_.E("gadgets.rpc.getAuthToken",_.L.lh); _.E("gadgets.rpc.removeReceiver",_.L.wt);_.E("gadgets.rpc.getRelayChannel",_.L.Zx);_.E("gadgets.rpc.receive",_.L.Jo);_.E("gadgets.rpc.receiveSameDomain",_.L.XA);_.E("gadgets.rpc.getOrigin",_.L.Wa);_.E("gadgets.rpc.getTargetOrigin",_.L.vg);

_.M={};_.Qc={};window.iframer=_.Qc;
_.Rc=function(a){var b=_.ja(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.Sc=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};_.Tc=function(a){return"number"==typeof a};_.Uc=function(a,b){return 0==a.lastIndexOf(b,0)};_.Vc=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};_.Wc=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};_.Xc=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};_.Yc=2147483648*Math.random()|0;

var qh;_.ph=function(a){return/^[\s\xa0]*$/.test(a)};qh=function(a){return Array.prototype.join.call(arguments,"")};_.rh=function(a){return(0,window.encodeURIComponent)(String(a))};_.sh=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;_.th=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
_.uh=function(a,b,c){if(_.ma(b))for(var d=0;d<b.length;d++)_.uh(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",_.rh(b))};_.vh=function(a,b){for(var c in b)_.uh(c,b[c],a);return a};_.wh=function(a,b){_.Vc(a,"/")&&(a=a.substr(0,a.length-1));_.Uc(b,"/")&&(b=b.substr(1));return qh(a,"/",b)};

var xk;_.vk=function(a){if(!_.Rc(a))return null;for(var b={},c=0;c<a.length;c++)b[a[c]]=a[c];return b};_.wk=function(a,b){var c=a.length;if(c!=b.length)return!1;for(var d=0;d<c;++d){var e=a.charCodeAt(d),f=b.charCodeAt(d);65<=e&&90>=e&&(e+=32);65<=f&&90>=f&&(f+=32);if(e!=f)return!1}return!0};xk=null;
_.yk=function(a){if(null===xk){var b=_.I("client/headers/response");b||(b=_.I("googleapis/headers/response"));xk=_.vk(b)}if(null!=xk){if(xk.hasOwnProperty(a))return!0;for(var c in xk)if(xk.hasOwnProperty(c)&&_.wk(c,a))return!0}return!1};
_.zk=function(a){a=String(a||"").split("\x00").join("");for(var b=[],c=!0,d=0,e=a.length;d<e;++d){var f=a.charAt(d),g=a.charCodeAt(d);if(55296<=g&&56319>=g&&d+1<e){var k=a.charAt(d+1),l=a.charCodeAt(d+1);56320<=l&&57343>=l&&(f+=k,g=65536+(g-55296<<10)+(l-56320),++d)}if(!(0<=g&&1114109>=g)||55296<=g&&57343>=g||64976<=g&&65007>=g||65534==(g&65534))g=65533,f=String.fromCharCode(g);k=!(32<=g&&126>=g)||" "==f||c&&":"==f||"\\"==f;!c||"/"!=f&&"?"!=f||(c=!1);"%"==f&&(d+2>=e?k=!0:(l=16*(0,window.parseInt)(a.charAt(d+
1),16)+(0,window.parseInt)(a.charAt(d+2),16),0<=l&&255>=l?(g=l,f=0==g?"":"%"+(256+l).toString(16).toUpperCase().substr(1),d+=2):k=!0));k&&(f=(0,window.encodeURIComponent)(f),1>=f.length&&(0<=g&&127>=g?f="%"+(256+g).toString(16).toUpperCase().substr(1):(g=65533,f=(0,window.encodeURIComponent)(String.fromCharCode(g)))));b.push(f)}a=b.join("");a=a.split("#")[0];a=a.split("?");b=a[0].split("/");c=[];d=0;for(e=b.length;d<e;++d)f=b[d],g=f.split("%2E").join("."),g=g.split((0,window.encodeURIComponent)("\uff0e")).join("."),
"."==g?d+1==e&&c.push(""):".."==g?(0<c.length&&c.pop(),d+1==e&&c.push("")):c.push(f);a[0]=c.join("/");for(a=a.join("?");a&&"/"==a.charAt(0);)a=a.substr(1);return"/"+a};_.Bk=function(a){var b=_.zk(a);if(String(a)!=b)throw Error("G");(a=b)&&"/"==a.charAt(a.length-1)||(a=(a||"")+"/");_.L.register("init",function(){_.Bk(a)});_.Ak=a;_.K.Ub(window.location.href)};
_.Ck="function"==typeof window.atob;
var Dk,Ek,Fk,Gk,Hk,Ik,Jk,Kk,Lk;Dk=null;Ek=function(a,b){if(null!=a)for(var c in a)if(a.hasOwnProperty(c)&&_.wk(c,b))return{name:c,value:a[c]}};Fk=null;
Gk=function(a,b,c,d){var e=Ek(b,"X-Goog-Safety-Encoding");if(null!=e){if(_.Ck)a=window.atob(a);else{if(!Dk){var f="ABCDEFGHIJKLMNOPQRSTUVWXYZ",f=f+(f.toLowerCase()+"0123456789+/=");Dk={};for(var g=0;g<f.length;g++)Dk[f.charAt(g)]=g}for(var f=Dk,g=[],k=0;k<a.length;){var l=f[a.charAt(k++)],m=k<a.length?f[a.charAt(k)]:0;++k;var n=k<a.length?f[a.charAt(k)]:0;++k;var p=k<a.length?f[a.charAt(k)]:0;++k;if(null==l||null==m||null==n||null==p)throw Error();g.push(l<<2|m>>4);64!=n&&(g.push(m<<4&240|n>>2),64!=
p&&g.push(n<<6&192|p))}a=String.fromCharCode.apply(null,g)}f=Ek(b,"X-Goog-Safety-Content-Type");b["Content-Type"]=f.value;delete b[e.name];delete b[f.name]}return{body:a,headers:b,status:c,statusText:d}};Hk=function(){try{return new window.XMLHttpRequest}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(a){}return null};Ik=function(a,b){b=b||"0.1";var c=[];c.push(a||"google-api-javascript-client");b&&(c.push("/"),c.push(b));return c.join("")};
Jk=function(a,b){if(!a||!b)return!1;for(var c=0,d=b.length;c<d;++c){var e=b.charCodeAt(c);if(!(32<=e&&126>=e))return!1}null===Fk&&((c=_.I("client/headers/request"))||(c=_.I("googleapis/headers/request")),Fk=_.vk(c));return null!=Fk?Fk.hasOwnProperty(a):!1};
Kk=function(a,b,c,d){a=a||{};var e=a.headers||{},f=a.httpMethod||"GET",g=String(a.url||""),k=a.urlParams||null,l=a.body||null,m=a.clientName||null,n=a.clientVersion||null;c=c||null;d=d||null;g=_.zk(g);g=_.Ak+String(g||"/").substr(1);g=_.th(_.vh([g],k));e["X-JavaScript-User-Agent"]=Ik(m,n);delete e["X-Origin"];c&&(e["X-Origin"]=c);delete e["X-Referer"];d&&(e["X-Referer"]=d);e["X-Goog-Encode-Response-If-Executable"]="base64";l&&"object"===typeof l&&(l=(0,_.Yb)(l));var p=Hk();if(!p)throw Error("H");
p.open(f,g);p.onreadystatechange=function(){if(4==p.readyState&&0!==p.status){var a=p.responseText;var c=p.getAllResponseHeaders(),d={};if(c)for(var c=c.split("\r\n"),e=0;e<c.length;e++){var f=c[e],g=f.indexOf(": ");if(0<g){var k=f.substring(0,g),f=f.substring(g+2);_.yk(k)&&(d[k]=f)}}a=Gk(a,d,p.status,p.statusText);b(a)}};p.onerror=function(){var c;c={error:{code:-1,message:"A network error occurred, and the request could not be completed."}};if("/rpc"==a.url){for(var d=a.body,e=[],f=0;f<d.length;f++){var g=
(0,_.Yb)(c),g=(0,_.ac)(g);g.id=d[f].id;e.push(g)}c=e}c=(0,_.Yb)(c);c=Gk(c);b(c)};for(var v in e)e.hasOwnProperty(v)&&(f=e[v],Jk(v,f)&&p.setRequestHeader(v,f));p.send(l?l:null)};Lk=function(a,b,c,d){var e={},f=0;if(0==a.length)b(e);else{var g=function(k){var l=k.key;Kk(k.params,function(c){e[l]={data:c};f++;a.length==f?b((0,_.Yb)(e)):g(a[f])},c,d)};g(a[f])}};_.bj=_.bj||{};
_.bj.XL=function(){_.L.register("makeHttpRequests",function(a){".."==this.f&&this.t==_.L.lh("..")&&this.origin==_.L.vg("..")&&Lk.call(this,a,this.callback,this.origin,this.referer)})};_.bj.Rb=function(){var a=String(window.location.pathname);18<=a.length&&"/static/proxy.html"==a.substr(a.length-18)&&(a=a.substr(0,a.length-18));a||(a="/");_.bj.vz(a)};_.bj.vz=function(a){var b=_.zk(a);if(String(a)!=b)throw Error("G");_.bj.XL();_.Bk(a);_.L.call("..","ready:"+_.L.lh(".."))};
_.E("googleapis.ApiServer.makeHttpRequests",Lk);_.E("googleapis.ApiServer.initWithPath",_.Bk);_.E("googleapis.server.init",_.bj.Rb);_.E("googleapis.server.initWithPath",_.bj.vz);
});
// Google Inc.
