__d("widget.navigatev2.navigatev2",["common.js.widget","common.js.events","common.js.cookie"],function(j,n,g,a){a("common.js.widget");var b=a("common.js.events"),e=a("common.js.cookie");$.widget("hao123.navigatev2",{options:{},_create:function(){},_bindEvent:function(){var a=this;if(!e.get("tabtip")){var d=Date.parse(new Date)/1E3;e.set("tabtip",d,{expires:365})}a.$tip.click(function(){$(this).remove();b.emit("menus.focus");setTimeout(function(){b.emit("menus.light")},500);var d=Date.parse(new Date)/
1E3-691200;e.set("tabtip",d,{expires:365})});a.$tipClose.click(function(){a.$tip.remove();e.get("tabtip_day")||e.set("tabtip_day","1",{expires:1});return!1})},destroy:function(){$.Widget.prototype.destroy.call(this)}});return g});
__d("widget.guesslikesite.guesslikesite","common.js.widget,common.js.cpcbll2,common.js.format,common.js.ctr,common.js.events,common.js.cpcctr".split(","),function(j,n,g,a){a("common.js.widget");var b=a("common.js.cpcbll2"),e=a("common.js.format");a("common.js.ctr");var q=a("common.js.events"),d=a("common.js.cpcctr");$.widget("hao123.guesslikesite",{options:{cpcClickChange:!1,cpcInitAdvance:!0,cpcTypeBegin:0,area:null},_create:function(){var d=this.options,b=this.element;this.$changeBtn=$(".changeBtn",
b);this.$changeLink=$(".js-changeLink",b);this.$row=$(".js_guesslike-industry",b);this.$row4screen=$(".guesslike-row",b);this.screenNumber=this.typeNumber=3;this.cpcInitCache=[{id:"cpc_gl_hot",initScreen:[]},{id:"cpc_gl_gouwu",initScreen:[]},{id:"cpc_gl_game",initScreen:[]},{id:"cpc_gl_mall",initScreen:[]},{id:"cpc_gl_temai",initScreen:[]},{id:"cpc_gl_caijing",initScreen:[]},{id:"cpc_gl_qiche",initScreen:[]},{id:"cpc_gl_junshi",initScreen:[]}];this.askTemaiIndex=0;this.bindEvent();d.cpcClickChange&&
this.burnAfterRead()},initCPC:function(){for(var a=this,e=0;e<a.$row.length;e++){var h=a.$row.eq(e),f=h.find(".guesslike-row").eq(0),t=f.attr("data-type"),h=h.attr("data-cpcon");(!h||"1"===h)&&function(c,f){b.init({id:a.cpcInitCache[c].id+"0",ctx:f,success:function(d){0<d.length&&(a.cpcInitCache[c].initScreen[0]=1)},complete:function(){d.sendCtrLog(f)}})}(t,f)}},bindEvent:function(){var a=this;if(a.options.cpcInitAdvance)a.initCPC();else q.on("guesslikesite.initcpcnext",function(){a.initCPC();q.un("guesslikesite.initcpcnext")});
a.$row.hover(function(){$(this).addClass("g-bg1")},function(){$(this).removeClass("g-bg1")});a.$changeBtn.click(function(){var e=$(this).parents(".guesslike-industry"),h=e.find(".guesslike-row"),f=h.siblings(".show"),t=e.data("type"),c=(f.data("screen")+1)%h.length,h=h.eq(c);f.removeClass("show");h.addClass("show");e=e.attr("data-cpcon");if(!e||"1"===e){var i=t||0,A=c||0;a.cpcInitCache[i].initScreen[A]||function(c){b.init({id:a.cpcInitCache[i].id+A,ctx:c,success:function(d){0<d.length&&(a.cpcInitCache[i].initScreen[A]=
1)},complete:function(){d.sendCtrLog(c)}})}($('.guesslike-row[data-type="'+i+'"]').eq(A))}return!1})},burnAfterRead:function(){function a(d,c){0<f[c].data.length&&(clearTimeout(s),s=setTimeout(function(){var a=f[c].data.shift(),b=a.tit;d.attr("href",a.curl);d.text(b);d.attr("alog-custom",e(h,{recom:1}))},500))}var s,h="recom:#{recom}",f=[{id:"cpc_gl_hot3",hasRequest:0,data:[]},{id:"cpc_gl_gouwu3",hasRequest:0,data:[]},{id:"cpc_gl_game3",hasRequest:0,data:[]},{id:"cpc_gl_mall3",hasRequest:0,data:[]},
{id:"cpc_gl_temai3",hasRequest:0,data:[]},{id:"cpc_gl_caijing3",hasRequest:0,data:[]},{id:"cpc_gl_qiche3",hasRequest:0,data:[]},{id:"cpc_gl_junshi3",hasRequest:0,data:[]}];this.$changeLink.click(function(){var e=$(this),c=e.parents(".guesslike-industry"),i=c.data("type"),c=c.attr("data-cpcon");if(!c||"1"===c)0===f[i].hasRequest?b.init({id:f[i].id,doNotRewriteDom:!0,success:function(c,b,h){f[i].hasRequest=1;f[i].data=c.slice();f[i].appid=b;f[i].flowinfo=h;d.saveLinkCtrInfo(e,f[i].data[0],b,h);a(e,
i);d.sendCtrLog(e,"link")}}):(d.saveLinkCtrInfo(e,f[i].data[0],f[i].appid,f[i].flowinfo),a(e,i),d.sendCtrLog(e,"link"))})},findChangeAgain:function(d){var a=this,e=[];$(".js-changeLink",d).each(function(){0>$(this).attr("alog-custom").indexOf("atd:2")&&e.push($(this).get(0))});0<e.length&&b.init({id:"cpc_gl_temai"+a.askTemaiIndex,links:e,complete:function(){a.askTemaiIndex+=1}})},destroy:function(){$.Widget.prototype.destroy.call(this)}});return g});
__d("widget.popup.popupVip","common.js.login,common.js.format,common.js.cookie,common.js.pageEvents,widget.popup.base,common.js.widget".split(","),function(j,n,g,a){function b(d){var a=(h.getViewport().height-d.height())/2;d.css({opacity:0,top:a+50}).animate({opacity:1,top:a})}function e(d){$.getJSON(f,{tid:d,c:s.getCSRFId()},function(d){d.errno==i&&$.getJSON(t,{tid:d.data,c:s.getCSRFId()})})}function q(d,a){$.getJSON(c,{gid:d,c:s.getCSRFId()},function(d){d.errno==i?a(!0,d.data):a(!1)})}var d=a("common.js.login"),
r=a("common.js.format"),s=a("common.js.cookie"),h=a("common.js.pageEvents");a("widget.popup.base");a("common.js.widget");var f="http://vip.hao123.com/vip/dotask?callback=?",t="http://vip.hao123.com/vip/getcoin?callback=?",c="http://vip.hao123.com/vip/getremain?callback=?",i=0;$.widget("hao123.viplogin",$.lottery.popup,{options:{isModel:!0,hoverCls:"hover",activeCls:"active"},_create:function(){var d=this.element;this._baseCreate();this.$close=$(".close-hook",d);this.$login=$(".login-hook",d);this.show();
this._bindEvent()},_bindEvent:function(){var a=this,c=a.options;a.$close.click(function(){a.remove();return!1});a.$login.on("mousedown",function(){$(this).addClass(c.activeCls)}).on("mouseover",function(){$(this).addClass(c.hoverCls)}).on("mouseout",function(){$(this).removeClass(c.hoverCls);$(this).removeClass(c.activeCls)}).on("mouseup",function(){$(this).removeClass(c.activeCls)}).on("click",function(){a.remove();d.show(function(d){h.emit("login.signin",d);q(c.gid,function(d,a){if(d){if(0==a){var b=
c.tid;$(r("<div class='popup-vip-sorry'><a href='#' class='close close-hook'></a><img src='#{img}' class='goods' width='170' height='120' /><a class='vip vip-hook' href='#{url}' target='_blank'></a></div>",{img:c.img,url:c.url})).vipresult()}else b=c.tid,$(r("<div class='popup-vip-success'><a href='#' class='close close-hook'></a><img src='#{img}' class='goods' width='170' height='120' /><div class='success'></div><a class='vip vip-hook' href='#{url}' target='_blank'></a></div>",{img:c.img,url:c.url})).vipresult();
e(b)}})});return!1})},show:function(){this._baseShow(b)}});$.widget("hao123.vipresult",$.lottery.popup,{options:{isModel:!0,hoverCls:"hover",activeCls:"active"},_create:function(){var d=this.element;this._baseCreate();this.$close=$(".close-hook",d);this.$vip=$(".vip-hook",d);this.show();this._bindEvent()},_bindEvent:function(){var d=this,a=d.options;d.$close.click(function(){d.remove();return!1});d.$vip.on("mousedown",function(){$(this).addClass(a.activeCls)}).on("mouseover",function(){$(this).addClass(a.hoverCls)}).on("mouseout",
function(){$(this).removeClass(a.hoverCls);$(this).removeClass(a.activeCls)}).on("mouseup",function(){$(this).removeClass(a.activeCls)}).on("click",function(){d.remove()})},show:function(){this._baseShow(b)}});n.exports={getPrize:function(a,c,b,f){d.isLogin()?q(a,function(d,a){d&&(0==a?$(r("<div class='popup-vip-sorry'><a href='#' class='close close-hook'></a><img src='#{img}' class='goods' width='170' height='120' /><a class='vip vip-hook' href='#{url}' target='_blank'></a></div>",{img:b,url:f})).vipresult():
$(r("<div class='popup-vip-success'><a href='#' class='close close-hook'></a><img src='#{img}' class='goods' width='170' height='120' /><div class='success'></div><a class='vip vip-hook' href='#{url}' target='_blank'></a></div>",{img:b,url:f})).vipresult(),e(c))}):q(a,function(d,e){d&&$(r("<div class='popup-vip-login'><a href='#' class='close close-hook'></a><img src='#{img}' class='goods' width='170' height='120' /><span class='remain remain-hook'>#{remain}</span><a href='#' class='login login-hook'></a></div>",
{img:b,remain:e})).viplogin({gid:a,tid:c,img:b,url:f})})}};return g});
__d("common.js.slider",["common.js.jquery"],function(j,n,g,a){var b=a("common.js.jquery");return function(a){function g(){if("fade"==t)0==k?f(v-1):f(k-1);else{if(l.is(":animated"))return!1;k--;0>k&&(k=v-1,l.css("left",-v*y));s();l.stop(!0,!0).animate({left:"+="+y},250,"linear",function(){k==v-1&&l.css("left",-k*y);h()})}}function d(){if("fade"==t)k+1==v?f(0):f(k+1);else{if(l.is(":animated"))return!1;k++;k==v&&(k=0);s();l.stop(!0,!0).animate({left:"-="+y},250,"linear",function(){0==k&&l.css("left",
0);h()})}}function r(a,d){if(0!=a-k||d)k=a,s(),l.stop(!0,!0).animate({left:-k*y},500,"linear",function(){h()})}function s(){0!=w.length&&w.each(function(){b(this).removeClass(i);b(this).data("index")==k&&b(this).addClass(i)})}function h(){m&&!n&&(clearInterval(B),B=setInterval(function(){d()},F))}function f(a){a!=k&&(x.eq(k).removeClass(i).addClass(u).css({opacity:1}).stop().animate({opacity:0},800,function(){b(this).css("filter","none").removeClass(u)}),x.eq(a).addClass(i+" "+u).css({opacity:0}).stop().animate({opacity:1},
800,function(){b(this).css("filter","none").removeClass(u);j&&b(this).css("opacity","")}),k=a,s(),h())}var t=a.type||"l2r",c=a.trigger||"click",i=a.selectCls||"selected",A=a.gridhoverCls||"grid_hover",m=a.auto||!1,n=!1,j=a.clearOpacity,u="animating",o=a.context?b(a.slider,a.context):b(a.slider),l=b(a.slides,o),x=b(a.slides,o).children(),p=b(a.prev,o),z=b(a.next,o),w=b(a.points,o).children(),E=b(a.grid,o),C=x.eq(0),y=a.width||C.width();C.height();var v=x.length,k=0;"l2r"==t&&(C.clone().insertAfter(x.eq(v-
1)),l.css({width:y*(v+1)+"px"}));(function(){p.click(function(){g();return!1});p.mousedown(function(a){a.preventDefault()});z.click(function(){d();return!1});z.mousedown(function(a){a.preventDefault()});"click"==c?w.click(function(){"fade"==t?f(b(this).data("index")):r(b(this).data("index"))}):"hover"==c&&w.hover(function(){"fade"==t?f(b(this).data("index")):r(b(this).data("index"))},function(){});E.hover(function(){b(this).addClass(A)},function(){b(this).removeClass(A)});m&&E.hover(function(){clearInterval(B)},
function(){h()});"fade"==t&&!a.notAutoHide&&o.hover(function(){p.show();z.show()},function(){p.hide();z.hide()})})();if(m){var B,F=a.interval||1E4;h()}return{dispose:function(){n=!0;clearInterval(B);p.unbind("click").unbind("mousedown");z.unbind("click").unbind("mousedown");"click"==c?w.unbind("click"):"hover"==c&&w.unbind("mouseenter").unbind("mouseleave");E.unbind("mouseenter").unbind("mouseleave");"fade"==t?o.unbind("mouseenter").unbind("mouseleave"):l.css("left",0)},resize:function(a){a=a||{};
y=a.width||C.width();l.css({width:y*(v+1)+"px"});r(k,!0)}}}});
__d("widget.coolsite.coolsite","common.js.jquery,common.js.adjust,common.js.slider,common.js.cookie,common.js.log,common.js.cpcbll2,common.js.format,common.js.browser,common.js.events".split(","),function(j,n,g,a){a("common.js.jquery");var b=a("common.js.adjust"),e=a("common.js.slider");a("common.js.cookie");var q=a("common.js.log"),d=a("common.js.cpcbll2"),r=a("common.js.format"),s=a("common.js.browser"),h=a("common.js.events");$.widget("hao123.coolsiteCPC",{options:{hoverCls:"g-bg1",recommend:0,
config:{youxi:{title:"\u6e38\u620f",switchTpl:'<a alog-text="\u4e0a\u4e00\u9875" href="#" class="arrow pre pre-hook"></a><a alog-text="\u4e0b\u4e00\u9875" href="#" class="arrow next next-hook"></a>',listTpl:'<li class="g-ib list"></li>',itemTpl:'<a class="item #{customClass}" href="#{url}" title="#{title}" #{cpcflag} cls="#{cls}"><img class="cpcimg #{customImgClass}" src="#{img}" data-cpc="img" width="62" height="62" /><span class="desc recommend-text" data-cpc="txt">#{title}</span></a>',colLen:10,
rowLen:2,type:"smallimg",narrowHide:2,cpcId:"cpckzyx"},junshi:{title:"\u519b\u4e8b",switchTpl:null,listTpl:'<li class="textlist" style="#{customStyle}"></li>',itemTpl:'<span class="item textitem #{customClass}"><i class="rank g-ib"></i><a class="textitem-link recommend-text" href="#{url}" title="#{title}" #{cpcflag} cls="#{cls}">#{title}</a></span>',colLen:5,rowLen:2,type:"longtext",narrowHide:1,cpcId:"cpc_kz_longtext_junshi"},zixun:{title:"\u65b0\u95fb",switchTpl:null,listTpl:'<li class="textlist" style="#{customStyle}"></li>',
itemTpl:'<span class="item textitem #{customClass}"><i class="rank g-ib"></i><a class="textitem-link recommend-text" href="#{url}" title="#{title}" #{cpcflag} cls="#{cls}">#{title}</a></span>',colLen:5,rowLen:2,type:"longtext",narrowHide:1,cpcId:"cpc_kz_longtext_zixun"},gouwu:{title:"\u8d2d\u7269",switchTpl:null,listTpl:'<li class="g-ib list"></li>',itemTpl:'<a class="item #{customClass}" href="#{url}" title="#{title}" #{cpcflag} cls="#{cls}"><img class="cpcimg #{customImgClass}" src="#{img}" data-cpc="img" width="62" height="62" /><span class="desc recommend-text" data-cpc="txt">#{title}</span></a>',
colLen:5,rowLen:1,type:"bigimg",narrowHide:1,cpcId:"cpc_kz_bigimg_gouwu"},lvyou:{title:"\u65c5\u6e38",switchTpl:null,listTpl:'<li class="g-ib list"></li>',itemTpl:'<a class="item #{customClass}" href="#{url}" title="#{title}" #{cpcflag} cls="#{cls}"><img class="cpcimg #{customImgClass}" src="#{img}" data-cpc="img" width="62" height="62" /><span class="desc recommend-text" data-cpc="txt">#{title}</span></a>',colLen:5,rowLen:1,type:"bigimg",narrowHide:1,cpcId:"cpc_kz_bigimg_lvyou"},qiche:{title:"\u6c7d\u8f66",
switchTpl:null,listTpl:'<li class="textlist" style="#{customStyle}"></li>',itemTpl:'<span class="item textitem #{customClass}"><i class="rank g-ib"></i><a class="textitem-link recommend-text" href="#{url}" title="#{title}" #{cpcflag} cls="#{cls}">#{title}</a></span>',colLen:6,rowLen:3,type:"shorttext",narrowHide:1,cpcId:"cpc_kz_shorttext_qiche"}},recomIsShow:{youxi:"0",junshi:"0",zixun:"0",gouwu:"0",lvyou:"0",qiche:"0"},recomOrder:"youxi,junshi,gouwu,qiche,lvyou,zixun".split(","),recomData:{youxi:null,
zixun:null,xinwen:null,gouwu:null,lvyou:null,qiche:null}},_init:function(){var a=this.options;this.showKey="";a.recomIsShow||(a.recomIsShow={youxi:"0",junshi:"0",zixun:"0",gouwu:"0",lvyou:"0",qiche:"0"});if(1===a.recommend&&(this.showKey=this.checkIfShow()))this.$recomContainer=this.render(this.showKey,a.recomData[this.showKey]),this.bindEvent()},bindEvent:function(){this.$recomContainer&&0<this.$recomContainer.length&&this.$recomContainer.hover(function(){$(this).addClass("recommend-hover")},function(){$(this).removeClass("recommend-hover")})},
checkIfShow:function(){for(var a=this.options,d=null,c=a.recomOrder,b=0;b<c.length;b++){var e=c[b];if(a.recomIsShow[e]&&"1"===a.recomIsShow[e]+""){d=e;break}}return d},findTargetRow:function(a){var d=this.options.config[a],c=null,b=null;$("li.coolsite-item",this.element).each(function(){if((b=$(".coolsite-itemname",$(this)))&&b.text()&&b.text().replace(/\s/g,"")===d.title)return c=$(this),!1});return c},render:function(a,g){var c=this.options,i=this.element;if(g&&g[0]&&g[0].data){var c=c.config[a],
n=g[0].data.slice(0,c.rowLen*c.colLen),m=this.findTargetRow(a),j=null;if(m&&0<m.length){q({type:"auto",k:"kzcpc-"+a});var D="height:"+(28*c.rowLen-14)+"px",j=$(r('<li class="recommend recommend-hook" monkey="kztjcpc-#{monkey}">   <div class="viewport" style="#{customStyle}">       <ul class="screen screen-hook">       </ul>   </div>   #{switchLink}   <i class="up"></i></li>',{switchLink:c.switchTpl,customStyle:-1<c.type.indexOf("text")?D:null,monkey:a})),u=$(".g_fr",m),D=$(".screen-hook",j),o,l,x=
!1;j.insertAfter(m);o=$('<a alog-text="\u5c55\u5f00\u6536\u8d77\u5f00\u5173" class="fold" href="#">\u5c55\u5f00</a>');if(window.localStorage){var m=window.localStorage.getItem("cpckuzhan-"+a),p=+new Date;m&&6048E5>p-m?x=!0:(j.slideDown(function(){$(this).css("overflow","visible");b.adjust()}),o.text("\u6536\u8d77"))}else j.slideDown(function(){$(this).css("overflow","visible");b.adjust()}),o.text("\u6536\u8d77");"6.0"!==s.ie&&(u.html(o),u.click(function(){j.slideToggle(function(){$(this).css("overflow",
"visible");(x=!x)?(o.text("\u5c55\u5f00"),window.localStorage&&(window.localStorage.removeItem("cpckuzhan-"+a),window.localStorage.setItem("cpckuzhan-"+a,+new Date))):(o.text("\u6536\u8d77"),window.localStorage&&window.localStorage.removeItem("cpckuzhan-"+a));b.adjust()});return!1}));for(m=0;m<c.rowLen;m++){u=$(r(c.listTpl,{customStyle:m+1===c.rowLen?"margin-bottom:0;":null})).appendTo(D);for(p=0;p<c.colLen;p++){l=n[p+c.rowLen*m];var z='data-cpc="link"';0===m+p&&"youxi"===a&&(z="");l=$(r(c.itemTpl,
{cpcflag:z,url:l.url,img:HAO.httpsTrans(l.imgurl),title:l.title,cls:l.cls,customClass:c.type,customImgClass:"cpc"+c.type})).appendTo(u);p===c.colLen-c.narrowHide-1&&l.addClass("width-nr-last");p===c.colLen-c.narrowHide&&l.addClass("width-nr-hide");p===c.colLen-1&&l.addClass("last").addClass("width-nr-hide")}}if("smallimg"===c.type){var w=e({context:i,slider:".recommend-hook",slides:".screen-hook",prev:".pre-hook",next:".next-hook"});h.on("wideversion.viewportchange",function(a){w&&w.resize({width:"wide"===
a?838:638})})}c.cpcId&&d.init({id:c.cpcId,ctx:j})}return j}},destroy:function(){$.Widget.prototype.destroy.call(this)}});return g});
__d("widget.toppicture.toppicture","common.js.widget,common.js.lazy,common.js.events,common.js.store,common.js.format,common.js.ctr".split(","),function(j,n,g,a){a("common.js.widget");var b=a("common.js.lazy");a("common.js.events");a("common.js.store");var e=a("common.js.format"),q=a("common.js.ctr");$.widget("hao123.toppicture",{options:{selectCls:"selected",interval:1E4,lazy:!1,picturedata:[],areaFlag:"",recomFlag:0,"switch":"off"},_create:function(){var a=this.element;this.$imglist=$(".js_content li",
a);this.$imgs=this.$imglist.find("img");this.$links=$(".pic",a);this.$next=$(".js_next",a);this.$pre=$(".js_pre",a)},_init:function(){this.$imgs&&(this.options.lazy&&b.add(this.$imgs.eq(0)),this.imgCount=this.$imglist.length,this.currentIndex=0,this.loadMore=this.options.loadMore||!1,this._bindEvent(),1<this.imgCount&&this._autoPlay(),"off"!==this.options["switch"]&&9!==this.recomFlag&&this._clickPlay())},_bindEvent:function(){var a=this;this.$imglist.hover(function(){clearTimeout(a.hideTimer);a._slideShow()},
function(){a.hideTimer=setTimeout(function(){a._slideHide()},100)});this.$next.click(function(){a._goNext();a._autoPlay();return!1});this.$pre.click(function(){a._goPre();a._autoPlay();return!1});this.$next.hover(function(){clearTimeout(a.hideTimer);a._slideShow()},function(){a.hideTimer=setTimeout(function(){a._slideHide()},100)});this.$pre.hover(function(){clearTimeout(a.hideTimer);a._slideShow()},function(){a.hideTimer=setTimeout(function(){a._slideHide()},100)})},_slideHide:function(){this.$next.hide();
this.$pre.hide()},_slideShow:function(){this.$next.show();this.$pre.show()},_autoPlay:function(){var a=this,b=a.options;clearInterval(this.timer);this.timer=setInterval(function(){a._goNext()},b.interval)},_goNext:function(){var a=this.currentIndex;++this.currentIndex==this.imgCount&&(this.currentIndex=0);this._display(a)},_goPre:function(){var a=this.currentIndex;0>--this.currentIndex&&(this.currentIndex=this.imgCount-1);this._display(a)},_clickPlay:function(){var a=this;this.$links.click(function(){a._changeLink($(this))})},
_changeLink:function(a){var b=this.options,g,h,f,j=(+new Date%6048E5).toString(36);g=a.data("index");h=$("img",a);f=$(".pic-txt",a);var c="";b.picturedata&&0<b.picturedata.length&&(c=b.picturedata.shift());c&&setTimeout(function(){f.text(c.title);h.attr("src",HAO.httpsTrans(c.img));h.attr("data-src",HAO.httpsTrans(c.img));a.attr("href",c.url);a.attr("title",c.title);a.attr("alog-custom",e("index:#{index},recom:#{recom},abtest:#{abtest},hash:#{hash},ts:#{ts}",{index:g,recom:c.is_backup||0,abtest:b.area,
hash:c.link_hash||"",ts:j}));a.attr("data-ctr",e("area:#{area},type:link,hash:#{hash},recom:#{recom},index:#{index},ts:#{ts}",{index:g,type:"link",recom:c.is_backup||0,area:b.area,hash:c.link_hash||"",ts:j}));a.attr("data-ctr-status",0);q.callCTR(a)},600)},_display:function(a){var e=this.options;this.loadMore||(this.loadMore=!0,b.add(this.$imgs.not(":first")));this.$imglist.eq(a).removeClass(e.selectCls);this.$imglist.eq(this.currentIndex).addClass(e.selectCls);this._animateShow(a)},_animateShow:function(a){this.$imglist.eq(a).css({opacity:1}).stop().addClass("animating").animate({opacity:0},
800,function(){$(this).css("filter","none").removeClass("animating")});this.$imglist.eq(this.currentIndex).css({opacity:0,display:"block"}).stop().addClass("animating").animate({opacity:1},800,function(){$(this).css("filter","none").removeClass("animating")})},destroy:function(){clearInterval(this.timer);$.Widget.prototype.destroy.call(this)}});return g});
__d("common.js.microTemplate",[],function(){function j(g,a){var b=!/\W/.test(g)?n[g]=n[g]||j(document.getElementById(g).innerHTML):new Function("data","var p=[];p.push('"+g.replace(/[\r\t\n]/g," ").split("<%").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("p.push('").split("\r").join("\\'")+"');return p.join('');");return a?b(a):b}var n={};return j});
__d("widget.guesslike.guesslike",["common.js.widget","common.js.config","common.js.profile","common.js.events"],function(j,n,g,a){a("common.js.widget");var b=a("common.js.config"),e=a("common.js.profile"),q=a("common.js.events");$.widget("hao123.guesslike",{_create:function(){var a=this;a._showGuess(e.get("navigate"));q.on("navigate.inited",function(b){a._showGuess(b)});q.on("navigate.tabchange",function(b){a._showGuess(b)})},_showGuess:function(a){var b=this.element.parent();this._needShow(a)?b.show():
b.hide()},_needShow:function(a){return"hao123-indexguess"==b.get("pageId")||0==a},destroy:function(){$.Widget.prototype.destroy.call(this)}});return g});
__d("widget.hlbar.hlbar",["common.js.widget"],function(j,n,g,a){a("common.js.widget");$.widget("hao123.hlbar",{_create:function(){this._initAlog()},_initAlog:function(){var a;$("a",this.element).each(function(){var e=$(this).attr("cls"),g="";e&&(a=e.split(","),1==a.length?g="ind:"+a[0]:2==a.length&&("y"==a[1]?a[1]=1:"n"==a[1]&&(a[1]=0),g="ind:"+a[0]+",sal:"+a[1]));$(this).attr("alog-custom",g)})},destroy:function(){$.Widget.prototype.destroy.call(this)}});return g});window.js_NUtvLyqFuX&&window.js_NUtvLyqFuX(!0);
